const colors = {
  light: {
    text: "#1A0A00",
    tint: "#3B1F0E",
    background: "#FAF1E4",
    foreground: "#1A0A00",
    card: "#FFFDF8",
    cardForeground: "#1A0A00",
    primary: "#3B1F0E",
    primaryForeground: "#FFFFFF",
    secondary: "#F0E7DB",
    secondaryForeground: "#3B1F0E",
    muted: "#EDE0CC",
    mutedForeground: "#7A6248",
    accent: "#C9922B",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E0D0BC",
    input: "#E0D0BC",
    success: "#2D7A4F",
    successForeground: "#FFFFFF",
  },
  dark: {
    text: "#F5EDD8",
    tint: "#C9922B",
    background: "#0D0500",
    foreground: "#F5EDD8",
    card: "#1A0D05",
    cardForeground: "#F5EDD8",
    primary: "#C9922B",
    primaryForeground: "#1A0A00",
    secondary: "#271508",
    secondaryForeground: "#F5EDD8",
    muted: "#1F0E06",
    mutedForeground: "#9E8060",
    accent: "#D4873A",
    accentForeground: "#1A0A00",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1508",
    input: "#2D1508",
    success: "#3D9E6A",
    successForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
