const colors = {
  light: {
    text: "#3A1F0E",
    tint: "#7B5408",
    background: "#FAF6EF",
    foreground: "#3A1F0E",
    card: "#FFFFFF",
    cardForeground: "#3A1F0E",
    primary: "#7B5408",
    primaryForeground: "#FFFFFF",
    secondary: "#F0E8D8",
    secondaryForeground: "#3A1F0E",
    muted: "#E8DDC8",
    mutedForeground: "#7A5530",
    accent: "#5C3D06",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#DDD0B8",
    input: "#DDD0B8",
    success: "#2D7A4F",
    successForeground: "#FFFFFF",
  },
  dark: {
    text: "#FAF6EF",
    tint: "#CA922B",
    background: "#1C0E06",
    foreground: "#FAF6EF",
    card: "#2A1500",
    cardForeground: "#FAF6EF",
    primary: "#CA922B",
    primaryForeground: "#FFFFFF",
    secondary: "#3A1F0E",
    secondaryForeground: "#FAF6EF",
    muted: "#2A1500",
    mutedForeground: "#A87A40",
    accent: "#E8A830",
    accentForeground: "#1C0E06",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#442A19",
    input: "#442A19",
    success: "#3D9E6A",
    successForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
