import type { AlertItem, Business, CommunityPost, Event } from "./types";

export const BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Sweet Auburn BBQ",
    category: "Food & Beverage",
    subcategory: "Barbecue",
    address: "656 N Highland Ave NE",
    city: "Atlanta",
    state: "GA",
    rating: 4.8,
    reviewCount: 312,
    verified: true,
    featured: true,
    confidenceScore: 94,
    blackOwned: true,
    ownershipDesignations: ["minority-owned", "women-owned", "veteran-owned"],
    verifiedDesignations: ["minority-owned", "women-owned"],
    safetyRating: 4.9,
    wouldReturnAlone: 97,
    recommendationRate: 98,
    description:
      "Award-winning BBQ rooted in Atlanta's historic Sweet Auburn district. We honor the traditions of Southern BBQ with bold flavors and community warmth.",
    latitude: 33.7641,
    longitude: -84.3605,
    tags: ["BBQ", "Southern", "Takeout", "Dine-In"],
    phone: "(404) 555-0191",
    website: "sweetauburnbbq.com",
    hours: "Mon–Sun 11am–9pm",
    priceRange: "$$",
    reviews: [
      { id: "r1", author: "Simone W.", initials: "SW", color: "#C4622D", rating: 5, text: "Absolutely amazing! The quality and service exceeded all expectations. Will definitely be back.", timeAgo: "3 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Marcus T.", initials: "MT", color: "#D4873A", rating: 4, text: "Great experience overall. The staff was incredibly welcoming and knowledgeable. Highly recommend to anyone in the community.", timeAgo: "1 week ago", wouldReturnAlone: true },
      { id: "r3", author: "Aisha B.", initials: "AB", color: "#2D7A4F", rating: 5, text: "This place is a gem. So proud to support minority-owned businesses like this one. They really care about their customers.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "2",
    name: "Essence Beauty Lounge",
    category: "Beauty & Personal Care",
    subcategory: "Salon & Spa",
    address: "3412 Westheimer Rd",
    city: "Houston",
    state: "TX",
    rating: 4.9,
    reviewCount: 218,
    verified: true,
    featured: true,
    confidenceScore: 91,
    blackOwned: true,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 5.0,
    wouldReturnAlone: 99,
    recommendationRate: 100,
    description:
      "A full-service beauty experience specializing in natural hair care, braids, locs, and luxury skin treatments designed for melanin-rich skin.",
    latitude: 29.7384,
    longitude: -95.4620,
    tags: ["Hair", "Natural", "Spa", "Locs", "Braids"],
    phone: "(713) 555-0247",
    website: "essencebeautylounge.com",
    hours: "Tue–Sat 9am–7pm",
    priceRange: "$$$",
    reviews: [
      { id: "r1", author: "Keisha J.", initials: "KJ", color: "#C4622D", rating: 5, text: "Best salon experience I've ever had. They truly understand natural hair and it shows!", timeAgo: "5 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Tamara L.", initials: "TL", color: "#2D7A4F", rating: 5, text: "My locs look absolutely stunning. The staff made me feel like royalty.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "3",
    name: "Harambee Tech Hub",
    category: "Technology",
    subcategory: "Coworking & Education",
    address: "1401 S Wabash Ave",
    city: "Chicago",
    state: "IL",
    rating: 4.7,
    reviewCount: 94,
    verified: true,
    featured: false,
    confidenceScore: 87,
    blackOwned: true,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 4.8,
    wouldReturnAlone: 95,
    recommendationRate: 96,
    description:
      "A community-centered tech hub offering coworking space, coding bootcamps, and mentorship programs focused on underrepresented founders.",
    latitude: 41.8655,
    longitude: -87.6252,
    tags: ["Tech", "Coworking", "Education", "Startup"],
    phone: "(312) 555-0382",
    website: "harambeetehhub.com",
    hours: "Mon–Fri 8am–8pm",
    priceRange: "$",
    reviews: [
      { id: "r1", author: "Darius P.", initials: "DP", color: "#C4622D", rating: 5, text: "This space changed my career trajectory. The mentorship and community here are unmatched.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "4",
    name: "Roots & Culture Bookstore",
    category: "Shopping & Retail",
    subcategory: "Books & Media",
    address: "2124 Georgia Ave NW",
    city: "Washington",
    state: "DC",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    featured: false,
    confidenceScore: 89,
    blackOwned: true,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 4.9,
    wouldReturnAlone: 98,
    recommendationRate: 97,
    description:
      "A beloved independent bookstore celebrating Black authors, African literature, cultural history, and community storytelling since 2009.",
    latitude: 38.9186,
    longitude: -77.0178,
    tags: ["Books", "Culture", "Community", "Independent"],
    phone: "(202) 555-0419",
    website: "rootsandculturebooks.com",
    hours: "Mon–Sat 10am–7pm, Sun 12–5pm",
    priceRange: "$",
    reviews: [
      { id: "r1", author: "Nadia C.", initials: "NC", color: "#D4873A", rating: 5, text: "Every visit feels like coming home. The selection of Black literature here is incredible.", timeAgo: "4 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Jerome F.", initials: "JF", color: "#2D7A4F", rating: 5, text: "A DC institution. I've been coming here for years and it only gets better.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "5",
    name: "Ujima Wellness Center",
    category: "Health & Wellness",
    subcategory: "Holistic Health",
    address: "789 Malcolm X Blvd",
    city: "New York",
    state: "NY",
    rating: 4.6,
    reviewCount: 189,
    verified: true,
    featured: true,
    confidenceScore: 82,
    blackOwned: true,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 4.7,
    wouldReturnAlone: 94,
    recommendationRate: 92,
    description:
      "Holistic healthcare and wellness services including acupuncture, therapy, nutrition counseling, and fitness programming rooted in African healing traditions.",
    latitude: 40.8030,
    longitude: -73.9500,
    tags: ["Wellness", "Therapy", "Holistic", "Fitness"],
    phone: "(212) 555-0572",
    website: "ujimawellness.com",
    hours: "Mon–Fri 9am–7pm, Sat 10am–4pm",
    priceRange: "$$",
    reviews: [
      { id: "r1", author: "Brianna M.", initials: "BM", color: "#C4622D", rating: 5, text: "Finally a wellness center that understands my body and my culture. The practitioners are exceptional.", timeAgo: "6 days ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "6",
    name: "Carter & Associates Law",
    category: "Professional Services",
    subcategory: "Business & Civil Rights",
    address: "5050 Wilshire Blvd",
    city: "Los Angeles",
    state: "CA",
    rating: 4.9,
    reviewCount: 67,
    verified: true,
    featured: false,
    confidenceScore: 96,
    blackOwned: true,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 5.0,
    wouldReturnAlone: 100,
    recommendationRate: 99,
    description:
      "Experienced legal counsel for businesses, civil rights matters, real estate, and estate planning. Trusted advocates for our community for over 20 years.",
    latitude: 34.0625,
    longitude: -118.3396,
    tags: ["Legal", "Business", "Civil Rights", "Real Estate"],
    phone: "(310) 555-0638",
    website: "carterandassociates.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$$",
    reviews: [
      { id: "r1", author: "Reginald B.", initials: "RB", color: "#2D7A4F", rating: 5, text: "Attorney Carter fought for us when no one else would. Exceptional representation.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "7",
    name: "Kingdom Cuts Barbershop",
    category: "Beauty & Personal Care",
    subcategory: "Barbershop",
    address: "1807 Peachtree Rd NE",
    city: "Atlanta",
    state: "GA",
    rating: 4.7,
    reviewCount: 445,
    verified: false,
    featured: false,
    confidenceScore: 71,
    blackOwned: true,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 4.6,
    wouldReturnAlone: 89,
    recommendationRate: 91,
    description:
      "The neighborhood barbershop where cuts and conversations flow freely. Master barbers specializing in fades, lineups, and beard grooming.",
    latitude: 33.7982,
    longitude: -84.3749,
    tags: ["Barbershop", "Fades", "Beard", "Walk-In"],
    phone: "(404) 555-0714",
    hours: "Mon–Sat 8am–7pm",
    priceRange: "$",
    reviews: [
      { id: "r1", author: "Malik J.", initials: "MJ", color: "#C4622D", rating: 5, text: "Best fades in Atlanta, period. The barbers here know their craft.", timeAgo: "2 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Andre P.", initials: "AP", color: "#D4873A", rating: 4, text: "Great cuts, sometimes a wait but worth it every time.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
  },
  {
    id: "8",
    name: "Melanin Money Financial",
    category: "Professional Services",
    subcategory: "Financial Planning",
    address: "3200 Main St",
    city: "Houston",
    state: "TX",
    rating: 4.8,
    reviewCount: 103,
    verified: true,
    featured: false,
    confidenceScore: 85,
    blackOwned: false,
    ownershipDesignations: [],
    verifiedDesignations: [],
    safetyRating: 4.8,
    wouldReturnAlone: 93,
    recommendationRate: 95,
    description:
      "Financial planning, investment advisory, and wealth-building services designed to close the racial wealth gap one family at a time.",
    latitude: 29.7449,
    longitude: -95.3698,
    tags: ["Finance", "Investing", "Wealth", "Planning"],
    phone: "(713) 555-0826",
    website: "melaninmoney.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$",
    reviews: [
      { id: "r1", author: "Denise H.", initials: "DH", color: "#2D7A4F", rating: 5, text: "They helped me build my first investment portfolio. Truly life-changing advice.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
  },
];

export const EVENTS: Event[] = [
  {
    id: "e1",
    title: "Juneteenth Freedom Festival",
    description:
      "Join us for Atlanta's biggest Juneteenth celebration featuring live music, local vendors, cultural performances, and community leaders. A family-friendly day honoring freedom and heritage.",
    date: "June 19, 2026",
    dateShort: "Jun 19",
    time: "12:00 PM – 8:00 PM",
    location: "Centennial Olympic Park",
    city: "Atlanta",
    state: "GA",
    category: "Cultural",
    attendees: 1240,
    organizer: "Atlanta Cultural Alliance",
    price: "Free",
    isFree: true,
    latitude: 33.7609,
    longitude: -84.3939,
    featured: true,
  },
  {
    id: "e2",
    title: "Black Tech Founders Summit",
    description:
      "Connect with over 500 Black tech founders, investors, and innovators. Panels, pitch competitions, networking, and workshops on scaling your startup.",
    date: "July 12, 2026",
    dateShort: "Jul 12",
    time: "9:00 AM – 6:00 PM",
    location: "McCormick Place",
    city: "Chicago",
    state: "IL",
    category: "Business",
    attendees: 540,
    organizer: "Black Founders Network",
    price: "$45",
    isFree: false,
    latitude: 41.8527,
    longitude: -87.6158,
    featured: true,
  },
  {
    id: "e3",
    title: "Harlem Jazz & Soul Food Night",
    description:
      "An evening of live jazz performances paired with the best soul food from Harlem's finest minority-owned restaurants. Celebrate our musical and culinary heritage.",
    date: "July 20, 2026",
    dateShort: "Jul 20",
    time: "6:00 PM – 11:00 PM",
    location: "Marcus Garvey Park",
    city: "New York",
    state: "NY",
    category: "Cultural",
    attendees: 380,
    organizer: "Harlem Cultural Society",
    price: "Free",
    isFree: true,
    latitude: 40.8004,
    longitude: -73.9464,
  },
  {
    id: "e4",
    title: "Melanin Beauty Expo",
    description:
      "The premier beauty expo celebrating melanin beauty, featuring 80+ minority-owned beauty brands, live demonstrations, masterclasses, and celebrity stylists.",
    date: "August 3, 2026",
    dateShort: "Aug 3",
    time: "10:00 AM – 6:00 PM",
    location: "DC Convention Center",
    city: "Washington",
    state: "DC",
    category: "Beauty",
    attendees: 1820,
    organizer: "Melanin Beauty Collective",
    price: "$25",
    isFree: false,
    latitude: 38.9017,
    longitude: -77.0229,
    featured: true,
  },
  {
    id: "e5",
    title: "Community Wealth Building Workshop",
    description:
      "Free financial literacy workshop covering homeownership, investing, generational wealth, and business credit. Presented by Black financial advisors.",
    date: "August 15, 2026",
    dateShort: "Aug 15",
    time: "10:00 AM – 2:00 PM",
    location: "Third Ward Community Center",
    city: "Houston",
    state: "TX",
    category: "Finance",
    attendees: 212,
    organizer: "Black Wealth Alliance",
    price: "Free",
    isFree: true,
    latitude: 29.7355,
    longitude: -95.3615,
  },
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "p1",
    author: "Zara M.",
    authorInitials: "ZM",
    authorColor: "#C4622D",
    content: "Just discovered this incredible minority-owned bookstore in DC — Roots & Culture. If you haven't been, GO! The selection of Afrofuturism and Black history books is unmatched. 📚✊🏾",
    likes: 47,
    comments: 12,
    timeAgo: "2h ago",
    category: "recommendation",
    postType: "community",
    liked: false,
  },
  {
    id: "p2",
    author: "Kwame A.",
    authorInitials: "KA",
    authorColor: "#2D7A4F",
    content: "Heads up to the Atlanta community — there's been an uptick of incidents near the West End corridor after 10pm. Stay aware and travel in groups. Keep each other safe out there. 🙏🏾",
    likes: 89,
    comments: 24,
    timeAgo: "4h ago",
    category: "alert",
    postType: "community",
    liked: false,
  },
  {
    id: "p3",
    author: "Imani T.",
    authorInitials: "IT",
    authorColor: "#D4873A",
    content: "Has anyone tried Ujima Wellness in Harlem? I've been looking for a holistic health center that really understands melanin-rich skincare. Would love recommendations!",
    likes: 31,
    comments: 19,
    timeAgo: "6h ago",
    category: "question",
    postType: "question",
    liked: false,
  },
  {
    id: "p4",
    author: "Darius K.",
    authorInitials: "DK",
    authorColor: "#7B3F00",
    content: "Shoutout to the Harambee Tech Hub in Chicago for hosting another amazing free coding workshop yesterday. 40 young Black developers got their first intro to Python. This is how we build generational wealth. 💻🔥",
    likes: 124,
    comments: 31,
    timeAgo: "1d ago",
    category: "discussion",
    postType: "community",
    liked: true,
  },
];

export const ALERTS: AlertItem[] = [
  {
    id: "a1",
    type: "safety",
    title: "Package Theft Alert",
    message: "Multiple reports of package theft near Auburn Ave between 2–5pm. Stay vigilant.",
    location: "Auburn Ave, Atlanta",
    timeAgo: "1h ago",
    severity: "medium",
  },
];

export const CATEGORIES = [
  "All",
  "Food & Beverage",
  "Shopping & Retail",
  "Beauty & Personal Care",
  "Health & Wellness",
  "Professional Services",
  "Technology",
  "Creative Services",
  "Events & Entertainment",
  "Home & Real Estate",
  "Home Improvement",
  "Automotive",
  "Travel & Hospitality",
  "Family & Education",
  "Pet Services",
  "Community & Nonprofits",
  "Government & Public Resources",
  "Black Professionals",
  "Online & Mobile Businesses",
];

export const EVENT_CATEGORIES = ["All", "Cultural", "Business", "Beauty", "Finance", "Music", "Food", "Wellness"];
