import type { AlertItem, Business, CommunityPost, Event } from "./types";

export const BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Sweet Auburn BBQ",
    category: "Food",
    subcategory: "Barbecue",
    address: "656 N Highland Ave NE",
    city: "Atlanta",
    state: "GA",
    rating: 4.8,
    reviewCount: 312,
    verified: true,
    featured: true,
    description:
      "Award-winning BBQ rooted in Atlanta's historic Sweet Auburn district. We honor the traditions of Southern BBQ with bold flavors and community warmth.",
    latitude: 33.7641,
    longitude: -84.3605,
    tags: ["BBQ", "Southern", "Takeout", "Dine-In"],
    phone: "(404) 555-0191",
    website: "sweetauburnbbq.com",
    hours: "Mon–Sun 11am–9pm",
    priceRange: "$$",
  },
  {
    id: "2",
    name: "Essence Beauty Lounge",
    category: "Beauty",
    subcategory: "Salon & Spa",
    address: "3412 Westheimer Rd",
    city: "Houston",
    state: "TX",
    rating: 4.9,
    reviewCount: 218,
    verified: true,
    featured: true,
    description:
      "A full-service beauty experience specializing in natural hair care, braids, locs, and luxury skin treatments designed for melanin-rich skin.",
    latitude: 29.7384,
    longitude: -95.4620,
    tags: ["Hair", "Natural", "Spa", "Locs", "Braids"],
    phone: "(713) 555-0247",
    website: "essencebeautylounge.com",
    hours: "Tue–Sat 9am–7pm",
    priceRange: "$$$",
  },
  {
    id: "3",
    name: "Harambee Tech Hub",
    category: "Tech",
    subcategory: "Coworking & Education",
    address: "1401 S Wabash Ave",
    city: "Chicago",
    state: "IL",
    rating: 4.7,
    reviewCount: 94,
    verified: true,
    featured: false,
    description:
      "A community-centered tech hub offering coworking space, coding bootcamps, and mentorship programs focused on underrepresented founders.",
    latitude: 41.8655,
    longitude: -87.6252,
    tags: ["Tech", "Coworking", "Education", "Startup"],
    phone: "(312) 555-0382",
    website: "harambeetehhub.com",
    hours: "Mon–Fri 8am–8pm",
    priceRange: "$",
  },
  {
    id: "4",
    name: "Roots & Culture Bookstore",
    category: "Retail",
    subcategory: "Books & Media",
    address: "2124 Georgia Ave NW",
    city: "Washington",
    state: "DC",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    featured: false,
    description:
      "A beloved independent bookstore celebrating Black authors, African literature, cultural history, and community storytelling since 2009.",
    latitude: 38.9186,
    longitude: -77.0178,
    tags: ["Books", "Culture", "Community", "Independent"],
    phone: "(202) 555-0419",
    website: "rootsandculturebooks.com",
    hours: "Mon–Sat 10am–7pm, Sun 12–5pm",
    priceRange: "$",
  },
  {
    id: "5",
    name: "Ujima Wellness Center",
    category: "Health",
    subcategory: "Holistic Health",
    address: "789 Malcolm X Blvd",
    city: "New York",
    state: "NY",
    rating: 4.6,
    reviewCount: 189,
    verified: true,
    featured: true,
    description:
      "Holistic healthcare and wellness services including acupuncture, therapy, nutrition counseling, and fitness programming rooted in African healing traditions.",
    latitude: 40.8030,
    longitude: -73.9500,
    tags: ["Wellness", "Therapy", "Holistic", "Fitness"],
    phone: "(212) 555-0572",
    website: "ujimawellness.com",
    hours: "Mon–Fri 9am–7pm, Sat 10am–4pm",
    priceRange: "$$",
  },
  {
    id: "6",
    name: "Carter & Associates Law",
    category: "Legal",
    subcategory: "Business & Civil Rights",
    address: "5050 Wilshire Blvd",
    city: "Los Angeles",
    state: "CA",
    rating: 4.9,
    reviewCount: 67,
    verified: true,
    featured: false,
    description:
      "Experienced legal counsel for businesses, civil rights matters, real estate, and estate planning. Trusted advocates for our community for over 20 years.",
    latitude: 34.0625,
    longitude: -118.3396,
    tags: ["Legal", "Business", "Civil Rights", "Real Estate"],
    phone: "(310) 555-0638",
    website: "carterandassociates.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$$",
  },
  {
    id: "7",
    name: "Kingdom Cuts Barbershop",
    category: "Beauty",
    subcategory: "Barbershop",
    address: "1807 Peachtree Rd NE",
    city: "Atlanta",
    state: "GA",
    rating: 4.7,
    reviewCount: 445,
    verified: false,
    featured: false,
    description:
      "The neighborhood barbershop where cuts and conversations flow freely. Master barbers specializing in fades, lineups, and beard grooming.",
    latitude: 33.7982,
    longitude: -84.3749,
    tags: ["Barbershop", "Fades", "Beard", "Walk-In"],
    phone: "(404) 555-0714",
    hours: "Mon–Sat 8am–7pm",
    priceRange: "$",
  },
  {
    id: "8",
    name: "Melanin Money Financial",
    category: "Finance",
    subcategory: "Financial Planning",
    address: "3200 Main St",
    city: "Houston",
    state: "TX",
    rating: 4.8,
    reviewCount: 103,
    verified: true,
    featured: false,
    description:
      "Financial planning, investment advisory, and wealth-building services designed to close the racial wealth gap one family at a time.",
    latitude: 29.7449,
    longitude: -95.3698,
    tags: ["Finance", "Investing", "Wealth", "Planning"],
    phone: "(713) 555-0826",
    website: "melaninmoney.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$",
  },
];

export const EVENTS: Event[] = [
  {
    id: "e1",
    title: "Juneteenth Freedom Festival",
    description:
      "Join us for Atlanta's biggest Juneteenth celebration featuring live music, local vendors, cultural performances, and community leaders. A family-friendly day honoring freedom and heritage.",
    date: "June 19, 2025",
    dateShort: "Jun 19",
    time: "12:00 PM – 8:00 PM",
    location: "Centennial Olympic Park",
    city: "Atlanta",
    state: "GA",
    category: "Cultural",
    attendees: 1240,
    organizer: "Atlanta Cultural Alliance",
    price: "Free",
    isFree: true,
    latitude: 33.7609,
    longitude: -84.3939,
    featured: true,
  },
  {
    id: "e2",
    title: "Black Tech Summit 2025",
    description:
      "A two-day conference connecting Black founders, engineers, and investors. Keynotes, panels, and networking sessions focused on innovation, funding, and community.",
    date: "July 12–13, 2025",
    dateShort: "Jul 12",
    time: "9:00 AM – 6:00 PM",
    location: "Walter E. Washington Convention Center",
    city: "Washington",
    state: "DC",
    category: "Business",
    attendees: 890,
    organizer: "Black Tech Collective",
    price: "$149",
    isFree: false,
    latitude: 38.9047,
    longitude: -77.0217,
    featured: true,
  },
  {
    id: "e3",
    title: "Soulful Saturdays: Jazz & Blues Night",
    description:
      "An intimate evening of live jazz and blues performances at Chicago's iconic jazz club. Dinner and drinks available. Dress code: smart casual.",
    date: "July 5, 2025",
    dateShort: "Jul 5",
    time: "7:00 PM – 11:00 PM",
    location: "Green Mill Jazz Club",
    city: "Chicago",
    state: "IL",
    category: "Entertainment",
    attendees: 180,
    organizer: "Chicago Jazz Society",
    price: "$25",
    isFree: false,
    latitude: 41.9658,
    longitude: -87.6558,
    featured: false,
  },
  {
    id: "e4",
    title: "Natural Hair & Beauty Expo",
    description:
      "Houston's premier natural hair and beauty event featuring 50+ vendors, live demos, giveaways, and workshops on hair care, skincare, and wellness.",
    date: "July 19, 2025",
    dateShort: "Jul 19",
    time: "10:00 AM – 5:00 PM",
    location: "George R. Brown Convention Center",
    city: "Houston",
    state: "TX",
    category: "Beauty",
    attendees: 2100,
    organizer: "Naturally Houston",
    price: "$15",
    isFree: false,
    latitude: 29.7531,
    longitude: -95.3677,
    featured: false,
  },
  {
    id: "e5",
    title: "Harlem Business Mixer",
    description:
      "Monthly networking event for Black entrepreneurs in the NYC metro area. Meet investors, mentors, and fellow founders over cocktails and great conversation.",
    date: "July 8, 2025",
    dateShort: "Jul 8",
    time: "6:00 PM – 9:00 PM",
    location: "Harlem Biospace",
    city: "New York",
    state: "NY",
    category: "Networking",
    attendees: 145,
    organizer: "Harlem Entrepreneurs Network",
    price: "Free",
    isFree: true,
    latitude: 40.8116,
    longitude: -73.9465,
    featured: false,
  },
  {
    id: "e6",
    title: "Afrofusion Wellness Retreat",
    description:
      "A weekend wellness retreat blending African healing traditions, yoga, meditation, and nutrition. Limited spots available. Nourish your body and spirit.",
    date: "August 2–3, 2025",
    dateShort: "Aug 2",
    time: "All Day",
    location: "Piedmont Park",
    city: "Atlanta",
    state: "GA",
    category: "Health",
    attendees: 75,
    organizer: "Ujima Wellness",
    price: "$89",
    isFree: false,
    latitude: 33.7874,
    longitude: -84.3733,
    featured: false,
  },
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "p1",
    author: "Jasmine R.",
    authorInitials: "JR",
    authorColor: "#C4622D",
    content:
      "Just had the most incredible experience at Sweet Auburn BBQ in Atlanta! The brisket was fall-off-the-bone perfect and the owner personally came out to greet us. This is what community dining looks like! Highly recommend for anyone visiting ATL. 🙌",
    likes: 47,
    comments: 12,
    timeAgo: "2h ago",
    category: "recommendation",
    liked: false,
  },
  {
    id: "p2",
    author: "Marcus T.",
    authorInitials: "MT",
    authorColor: "#D4873A",
    content:
      "Question for the Houston community: Anyone have recommendations for a Black-owned CPA or financial advisor in the Midtown area? Looking to get my business finances in order before Q3. Happy to share referrals in return!",
    likes: 23,
    comments: 31,
    timeAgo: "4h ago",
    category: "question",
    liked: true,
  },
  {
    id: "p3",
    author: "Community Alert",
    authorInitials: "CA",
    authorColor: "#DC2626",
    content:
      "⚠️ Safety Notice: Several businesses on Auburn Ave have reported an uptick in package theft between 2–5pm this week. Please be vigilant and consider adjusting delivery schedules. If you witness anything suspicious, contact Atlanta PD at 404-577-3246.",
    likes: 89,
    comments: 18,
    timeAgo: "6h ago",
    category: "alert",
    liked: false,
  },
  {
    id: "p4",
    author: "Aaliyah M.",
    authorInitials: "AM",
    authorColor: "#2D7A4F",
    content:
      "Attended the Harlem Business Mixer last night and wow — the energy was incredible. Met three potential collaborators and a VC who's actively looking to fund Black founders. These events are EVERYTHING. See you all next month! 🙌✨",
    likes: 64,
    comments: 9,
    timeAgo: "1d ago",
    category: "discussion",
    liked: false,
  },
  {
    id: "p5",
    author: "DeShawn P.",
    authorInitials: "DP",
    authorColor: "#5C3D2E",
    content:
      "Starting a list of all the Black-owned banks and credit unions across the US. So far I have: OneUnited Bank, Carver Federal, Liberty Bank, Broadway Federal. Drop yours below and let's build the most comprehensive list ever! 💪",
    likes: 128,
    comments: 56,
    timeAgo: "1d ago",
    category: "discussion",
    liked: true,
  },
];

export const ALERTS: AlertItem[] = [
  {
    id: "a1",
    type: "safety",
    title: "Package Theft Alert",
    message:
      "Multiple reports of package theft near Auburn Ave between 2–5pm. Stay vigilant.",
    location: "Auburn Ave, Atlanta, GA",
    timeAgo: "6h ago",
    severity: "medium",
  },
];

export const CATEGORIES = [
  "All",
  "Food",
  "Beauty",
  "Health",
  "Legal",
  "Tech",
  "Retail",
  "Finance",
];

export const EVENT_CATEGORIES = [
  "All",
  "Cultural",
  "Business",
  "Entertainment",
  "Beauty",
  "Networking",
  "Health",
];
