export interface DiasporaCountry {
  code: string;
  name: string;
  region: "Africa" | "Caribbean" | "Americas" | "Europe & Other";
}

export function getFlag(code: string): string {
  return [...code.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join("");
}

export const DIASPORA_COUNTRIES: DiasporaCountry[] = [
  { code: "DZ", name: "Algeria", region: "Africa" },
  { code: "AO", name: "Angola", region: "Africa" },
  { code: "BJ", name: "Benin", region: "Africa" },
  { code: "BW", name: "Botswana", region: "Africa" },
  { code: "BF", name: "Burkina Faso", region: "Africa" },
  { code: "BI", name: "Burundi", region: "Africa" },
  { code: "CV", name: "Cabo Verde", region: "Africa" },
  { code: "CM", name: "Cameroon", region: "Africa" },
  { code: "CF", name: "Central African Republic", region: "Africa" },
  { code: "TD", name: "Chad", region: "Africa" },
  { code: "KM", name: "Comoros", region: "Africa" },
  { code: "CD", name: "DR Congo", region: "Africa" },
  { code: "CG", name: "Republic of Congo", region: "Africa" },
  { code: "CI", name: "Côte d'Ivoire", region: "Africa" },
  { code: "DJ", name: "Djibouti", region: "Africa" },
  { code: "EG", name: "Egypt", region: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", region: "Africa" },
  { code: "ER", name: "Eritrea", region: "Africa" },
  { code: "SZ", name: "Eswatini", region: "Africa" },
  { code: "ET", name: "Ethiopia", region: "Africa" },
  { code: "GA", name: "Gabon", region: "Africa" },
  { code: "GM", name: "Gambia", region: "Africa" },
  { code: "GH", name: "Ghana", region: "Africa" },
  { code: "GN", name: "Guinea", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", region: "Africa" },
  { code: "KE", name: "Kenya", region: "Africa" },
  { code: "LS", name: "Lesotho", region: "Africa" },
  { code: "LR", name: "Liberia", region: "Africa" },
  { code: "LY", name: "Libya", region: "Africa" },
  { code: "MG", name: "Madagascar", region: "Africa" },
  { code: "MW", name: "Malawi", region: "Africa" },
  { code: "ML", name: "Mali", region: "Africa" },
  { code: "MR", name: "Mauritania", region: "Africa" },
  { code: "MU", name: "Mauritius", region: "Africa" },
  { code: "MA", name: "Morocco", region: "Africa" },
  { code: "MZ", name: "Mozambique", region: "Africa" },
  { code: "NA", name: "Namibia", region: "Africa" },
  { code: "NE", name: "Niger", region: "Africa" },
  { code: "NG", name: "Nigeria", region: "Africa" },
  { code: "RW", name: "Rwanda", region: "Africa" },
  { code: "ST", name: "São Tomé & Príncipe", region: "Africa" },
  { code: "SN", name: "Senegal", region: "Africa" },
  { code: "SC", name: "Seychelles", region: "Africa" },
  { code: "SL", name: "Sierra Leone", region: "Africa" },
  { code: "SO", name: "Somalia", region: "Africa" },
  { code: "ZA", name: "South Africa", region: "Africa" },
  { code: "SS", name: "South Sudan", region: "Africa" },
  { code: "SD", name: "Sudan", region: "Africa" },
  { code: "TZ", name: "Tanzania", region: "Africa" },
  { code: "TG", name: "Togo", region: "Africa" },
  { code: "TN", name: "Tunisia", region: "Africa" },
  { code: "UG", name: "Uganda", region: "Africa" },
  { code: "ZM", name: "Zambia", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", region: "Africa" },

  { code: "AG", name: "Antigua & Barbuda", region: "Caribbean" },
  { code: "AW", name: "Aruba", region: "Caribbean" },
  { code: "BS", name: "Bahamas", region: "Caribbean" },
  { code: "BB", name: "Barbados", region: "Caribbean" },
  { code: "CU", name: "Cuba", region: "Caribbean" },
  { code: "CW", name: "Curaçao", region: "Caribbean" },
  { code: "DM", name: "Dominica", region: "Caribbean" },
  { code: "DO", name: "Dominican Republic", region: "Caribbean" },
  { code: "GD", name: "Grenada", region: "Caribbean" },
  { code: "GP", name: "Guadeloupe", region: "Caribbean" },
  { code: "HT", name: "Haiti", region: "Caribbean" },
  { code: "JM", name: "Jamaica", region: "Caribbean" },
  { code: "MQ", name: "Martinique", region: "Caribbean" },
  { code: "MS", name: "Montserrat", region: "Caribbean" },
  { code: "PR", name: "Puerto Rico", region: "Caribbean" },
  { code: "KN", name: "St. Kitts & Nevis", region: "Caribbean" },
  { code: "LC", name: "St. Lucia", region: "Caribbean" },
  { code: "VC", name: "St. Vincent & Grenadines", region: "Caribbean" },
  { code: "TT", name: "Trinidad & Tobago", region: "Caribbean" },
  { code: "TC", name: "Turks & Caicos", region: "Caribbean" },
  { code: "VI", name: "US Virgin Islands", region: "Caribbean" },

  { code: "BZ", name: "Belize", region: "Americas" },
  { code: "BR", name: "Brazil", region: "Americas" },
  { code: "CO", name: "Colombia", region: "Americas" },
  { code: "CR", name: "Costa Rica", region: "Americas" },
  { code: "EC", name: "Ecuador", region: "Americas" },
  { code: "GF", name: "French Guiana", region: "Americas" },
  { code: "GT", name: "Guatemala", region: "Americas" },
  { code: "GY", name: "Guyana", region: "Americas" },
  { code: "HN", name: "Honduras", region: "Americas" },
  { code: "NI", name: "Nicaragua", region: "Americas" },
  { code: "PA", name: "Panama", region: "Americas" },
  { code: "PE", name: "Peru", region: "Americas" },
  { code: "SR", name: "Suriname", region: "Americas" },
  { code: "VE", name: "Venezuela", region: "Americas" },

  { code: "BE", name: "Belgium", region: "Europe & Other" },
  { code: "FR", name: "France", region: "Europe & Other" },
  { code: "DE", name: "Germany", region: "Europe & Other" },
  { code: "NL", name: "Netherlands", region: "Europe & Other" },
  { code: "PT", name: "Portugal", region: "Europe & Other" },
  { code: "ES", name: "Spain", region: "Europe & Other" },
  { code: "GB", name: "United Kingdom", region: "Europe & Other" },
];

export const REGIONS: DiasporaCountry["region"][] = [
  "Africa",
  "Caribbean",
  "Americas",
  "Europe & Other",
];

export const REGION_EMOJI: Record<DiasporaCountry["region"], string> = {
  Africa: "🌍",
  Caribbean: "🌊",
  Americas: "🌎",
  "Europe & Other": "🌐",
};
