import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build as esbuild } from "esbuild";
import esbuildPluginPino from "esbuild-plugin-pino";
import { rm, copyFile, cp, readFile, mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { execSync } from "node:child_process";

// Plugins (e.g. 'esbuild-plugin-pino') may use `require` to resolve dependencies
globalThis.require = createRequire(import.meta.url);

const artifactDir = path.dirname(fileURLToPath(import.meta.url));

// Generate src/generated/spaHtml.ts BEFORE esbuild runs so it can be bundled.
// Generate src/generated/buildIdentity.ts BEFORE esbuild runs so the git SHA
// and build timestamp are compiled directly into the bundle as TypeScript exports.
// This is the same pattern as spaHtml.ts — esbuild bundles the generated file,
// so the values are embedded in dist/index.mjs regardless of whether Railway
// uses the committed dist/ or rebuilds from source.
async function generateBuildIdentity() {
  const genDir = path.resolve(artifactDir, "src", "generated");
  const genFile = path.resolve(genDir, "buildIdentity.ts");

  // Try git first; fall back to RAILWAY_GIT_COMMIT_SHA (set as Docker build arg)
  // so the SHA is embedded even when .git is absent from the Docker build context.
  let gitSha = process.env.RAILWAY_GIT_COMMIT_SHA ?? "unknown";
  try { gitSha = execSync("git rev-parse HEAD", { encoding: "utf8" }).trim(); } catch {}
  const buildAt = new Date().toISOString();

  await mkdir(genDir, { recursive: true });
  await writeFile(genFile,
    `// AUTO-GENERATED by build.mjs — do not edit\n` +
    `// Embed build identity directly in the bundle so /api/version always returns\n` +
    `// tamper-proof values regardless of runtime environment variables.\n` +
    `export const BUILT_FROM_SHA = ${JSON.stringify(gitSha)};\n` +
    `export const BUILD_AT = ${JSON.stringify(buildAt)};\n`
  );
  console.log(`BUILD_IDENTITY generated: sha=${gitSha.slice(0,12)}... at=${buildAt}`);
}

async function generateSpaHtml() {
  const htmlSrc = path.resolve(artifactDir, "web-static", "index.html");
  const genDir = path.resolve(artifactDir, "src", "generated");
  const genFile = path.resolve(genDir, "spaHtml.ts");
  try {
    const html = await readFile(htmlSrc, "utf8");
    await mkdir(genDir, { recursive: true });
    const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    await writeFile(genFile, `// AUTO-GENERATED by build.mjs — do not edit\nexport const SPA_HTML = \`${escaped}\`;\n`);
    console.log(`SPA html embedded (${html.length} bytes)`);
  } catch (e) {
    // First build or missing web-static — write an empty fallback so TS compiles
    await mkdir(path.resolve(artifactDir, "src", "generated"), { recursive: true });
    await writeFile(path.resolve(artifactDir, "src", "generated", "spaHtml.ts"),
      `// AUTO-GENERATED — fallback when web-static/index.html is absent\nexport const SPA_HTML = "";\n`);
    console.warn("SPA html fallback written:", e.message);
  }
}

async function buildAll() {
  const distDir = path.resolve(artifactDir, "dist");
  await rm(distDir, { recursive: true, force: true });

  // ── Embed build identity directly into the bundle via esbuild define ────────
  // These constants are compiled into dist/index.mjs itself — not read from a
  // file or env var at runtime. Any external party can verify provenance by
  // comparing __BUILT_FROM_SHA__ (returned by /api/version) with the git log.
  let _builtFromSha = "unknown";
  let _buildAt = new Date().toISOString();
  try { _builtFromSha = execSync("git rev-parse HEAD", { encoding: "utf8" }).trim(); } catch {}
  console.log(`BUILD define: __BUILT_FROM_SHA__=${_builtFromSha.slice(0,12)}... __BUILD_AT__=${_buildAt}`);

  await esbuild({
    entryPoints: [path.resolve(artifactDir, "src/index.ts")],
    platform: "node",
    bundle: true,
    format: "esm",
    outdir: distDir,
    outExtension: { ".js": ".mjs" },
    logLevel: "info",
    // Compile-time constants — baked into every line of dist/index.mjs.
    // Unlike env vars, these cannot be changed after the build.
    define: {
      "__BUILT_FROM_SHA__": JSON.stringify(_builtFromSha),
      "__BUILD_AT__": JSON.stringify(_buildAt),
    },
    // Some packages may not be bundleable, so we externalize them, we can add more here as needed.
    // Some of the packages below may not be imported or installed, but we're adding them in case they are in the future.
    // Examples of unbundleable packages:
    // - uses native modules and loads them dynamically (e.g. sharp)
    // - use path traversal to read files (e.g. @google-cloud/secret-manager loads sibling .proto files)
    external: [
      "*.node",
      "sharp",
      "better-sqlite3",
      "sqlite3",
      "canvas",
      "bcrypt",
      "argon2",
      "fsevents",
      "re2",
      "farmhash",
      "xxhash-addon",
      "bufferutil",
      "utf-8-validate",
      "ssh2",
      "cpu-features",
      "dtrace-provider",
      "isolated-vm",
      "lightningcss",
      "pg-native",
      "oracledb",
      "mongodb-client-encryption",
      "nodemailer",
      "handlebars",
      "knex",
      "typeorm",
      "protobufjs",
      "onnxruntime-node",
      "@tensorflow/*",
      "@prisma/client",
      "@mikro-orm/*",
      "@grpc/*",
      "@swc/*",
      "@aws-sdk/*",
      "@azure/*",
      "@opentelemetry/*",
      "@google-cloud/secret-manager",
      "@google-cloud/bigquery",
      "@google-cloud/pubsub",
      "@google-cloud/spanner",
      "@google-cloud/datastore",
      "@google-cloud/firestore",
      "@google/*",
      "googleapis",
      "firebase-admin",
      "@parcel/watcher",
      "@sentry/profiling-node",
      "@resvg/*",
      "@tree-sitter/*",
      "aws-sdk",
      "classic-level",
      "dd-trace",
      "ffi-napi",
      "grpc",
      "hiredis",
      "kerberos",
      "leveldown",
      "miniflare",
      "mysql2",
      "newrelic",
      "odbc",
      "piscina",
      "realm",
      "ref-napi",
      "rocksdb",
      "sass-embedded",
      "sequelize",
      "serialport",
      "snappy",
      "tinypool",
      "usb",
      "workerd",
      "wrangler",
      "zeromq",
      "zeromq-prebuilt",
      "playwright",
      "puppeteer",
      "puppeteer-core",
      "electron",
    ],
    sourcemap: "linked",
    plugins: [
      // pino relies on workers to handle logging, instead of externalizing it we use a plugin to handle it
      esbuildPluginPino({ transports: ["pino-pretty"] })
    ],
    // Make sure packages that are cjs only (e.g. express) but are bundled continue to work in our esm output file
    banner: {
      js: `import { createRequire as __bannerCrReq } from 'node:module';
import __bannerPath from 'node:path';
import __bannerUrl from 'node:url';

globalThis.require = __bannerCrReq(import.meta.url);
globalThis.__filename = __bannerUrl.fileURLToPath(import.meta.url);
globalThis.__dirname = __bannerPath.dirname(globalThis.__filename);
    `,
    },
  });
}

// ── Build-identity helpers ────────────────────────────────────────────────────
// Computes a SHA-256 hash of the compiled bundle and writes it alongside the
// git SHA and build timestamp into dist/BUILD_IDENTITY. The /api/version route
// reads this file at startup and returns all three values so any external party
// can independently verify that the running artifact matches the source commit:
//
//   1. bundle_sha256 — hash of dist/index.mjs; must match a local build to prove
//      Railway is running the expected artifact (not a cached or stale one).
//   2. built_from_sha — git SHA embedded at BUILD TIME (not a runtime env var),
//      so it is part of the compiled artifact and cannot be faked.
//   3. built_at — ISO timestamp of when `node build.mjs` was executed.


async function writeBuildIdentity(distDir) {
  const bundlePath = path.resolve(distDir, "index.mjs");
  const identityPath = path.resolve(distDir, "BUILD_IDENTITY");

  let gitSha = "unknown";
  try {
    gitSha = execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
  } catch {}

  let bundleHash = "unknown";
  try {
    const { readFile: _readFile } = await import("node:fs/promises");
    const buf = await _readFile(bundlePath);
    bundleHash = createHash("sha256").update(buf).digest("hex");
  } catch (e) {
    console.warn("BUILD_IDENTITY: could not hash bundle:", e.message);
  }

  const identity = {
    bundle_sha256: bundleHash,
    built_from_sha: gitSha,
    built_at: new Date().toISOString(),
  };

  await writeFile(identityPath, JSON.stringify(identity, null, 2) + "\n");
  console.log("BUILD_IDENTITY written:", JSON.stringify(identity));
}

generateBuildIdentity()
  .then(() => generateSpaHtml())
  .then(() => buildAll())
  .then(() =>
    copyFile(
      path.resolve(artifactDir, "src/assets/NotoSans-Regular.ttf"),
      path.resolve(artifactDir, "dist/NotoSans-Regular.ttf"),
    )
  )
  .then(() => {
    const webStaticSrc = path.resolve(artifactDir, "web-static");
    const webStaticDst = path.resolve(artifactDir, "dist/public");
    return cp(webStaticSrc, webStaticDst, { recursive: true });
  })
  .then(() => console.log("Web static files copied to dist/public/"))
  .then(() => writeBuildIdentity(path.resolve(artifactDir, "dist")))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
