export {
  openai,
  audioOpenai,
  resolveAudioOpenAIConfiguration,
  detectAudioFormat,
  convertToWav,
  ensureCompatibleFormat,
  type AudioFormat,
  voiceChat,
  voiceChatStream,
  textToSpeech,
  textToSpeechWithStyle,
  textToSpeechStream,
  speechToText,
  speechToTextStream,
} from "./client";
