import { db, businessesTable } from "@workspace/db";

const businesses = [
  {
    id: "1",
    name: "Sweet Auburn BBQ",
    category: "Food",
    subcategory: "Barbecue",
    address: "656 N Highland Ave NE",
    city: "Atlanta",
    state: "GA",
    rating: "4.8",
    reviewCount: 312,
    verified: true,
    featured: true,
    confidenceScore: 94,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 98,
    description: "Award-winning BBQ rooted in Atlanta's historic Sweet Auburn district. We honor the traditions of Southern BBQ with bold flavors and community warmth.",
    latitude: "33.7641000",
    longitude: "-84.3605000",
    tags: ["BBQ", "Southern", "Takeout", "Dine-In"],
    reviews: [
      { id: "r1", author: "Simone W.", initials: "SW", color: "#C4622D", rating: 5, text: "Absolutely amazing! The quality and service exceeded all expectations. Will definitely be back.", timeAgo: "3 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Marcus T.", initials: "MT", color: "#D4873A", rating: 4, text: "Great experience overall. The staff was incredibly welcoming and knowledgeable. Highly recommend to anyone in the community.", timeAgo: "1 week ago", wouldReturnAlone: true },
      { id: "r3", author: "Aisha B.", initials: "AB", color: "#2D7A4F", rating: 5, text: "This place is a gem. So proud to support Black-owned businesses like this one. They really care about their customers.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-0191",
    website: "sweetauburnbbq.com",
    hours: "Mon–Sun 11am–9pm",
    priceRange: "$$",
  },
  {
    id: "2",
    name: "Essence Beauty Lounge",
    category: "Beauty",
    subcategory: "Salon & Spa",
    address: "3412 Westheimer Rd",
    city: "Houston",
    state: "TX",
    rating: "4.9",
    reviewCount: 218,
    verified: true,
    featured: true,
    confidenceScore: 91,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 99,
    recommendationRate: 100,
    description: "A full-service beauty experience specializing in natural hair care, braids, locs, and luxury skin treatments designed for melanin-rich skin.",
    latitude: "29.7384000",
    longitude: "-95.4620000",
    tags: ["Hair", "Natural", "Spa", "Locs", "Braids"],
    reviews: [
      { id: "r1", author: "Keisha J.", initials: "KJ", color: "#C4622D", rating: 5, text: "Best salon experience I've ever had. They truly understand natural hair and it shows!", timeAgo: "5 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Tamara L.", initials: "TL", color: "#2D7A4F", rating: 5, text: "My locs look absolutely stunning. The staff made me feel like royalty.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(713) 555-0247",
    website: "essencebeautylounge.com",
    hours: "Tue–Sat 9am–7pm",
    priceRange: "$$$",
  },
  {
    id: "3",
    name: "Harambee Tech Hub",
    category: "Tech",
    subcategory: "Coworking & Education",
    address: "1401 S Wabash Ave",
    city: "Chicago",
    state: "IL",
    rating: "4.7",
    reviewCount: 94,
    verified: true,
    featured: false,
    confidenceScore: 87,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 95,
    recommendationRate: 96,
    description: "A community-centered tech hub offering coworking space, coding bootcamps, and mentorship programs focused on underrepresented founders.",
    latitude: "41.8655000",
    longitude: "-87.6252000",
    tags: ["Tech", "Coworking", "Education", "Startup"],
    reviews: [
      { id: "r1", author: "Darius P.", initials: "DP", color: "#C4622D", rating: 5, text: "This space changed my career trajectory. The mentorship and community here are unmatched.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(312) 555-0382",
    website: "harambeetehhub.com",
    hours: "Mon–Fri 8am–8pm",
    priceRange: "$",
  },
  {
    id: "4",
    name: "Roots & Culture Bookstore",
    category: "Retail",
    subcategory: "Books & Media",
    address: "2124 Georgia Ave NW",
    city: "Washington",
    state: "DC",
    rating: "4.8",
    reviewCount: 156,
    verified: true,
    featured: false,
    confidenceScore: 89,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 98,
    recommendationRate: 97,
    description: "A beloved independent bookstore celebrating Black authors, African literature, cultural history, and community storytelling since 2009.",
    latitude: "38.9186000",
    longitude: "-77.0178000",
    tags: ["Books", "Culture", "Community", "Independent"],
    reviews: [
      { id: "r1", author: "Nadia C.", initials: "NC", color: "#D4873A", rating: 5, text: "Every visit feels like coming home. The selection of Black literature here is incredible.", timeAgo: "4 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Jerome F.", initials: "JF", color: "#2D7A4F", rating: 5, text: "A DC institution. I've been coming here for years and it only gets better.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(202) 555-0419",
    website: "rootsandculturebooks.com",
    hours: "Mon–Sat 10am–7pm, Sun 12–5pm",
    priceRange: "$",
  },
  {
    id: "5",
    name: "Ujima Wellness Center",
    category: "Health",
    subcategory: "Holistic Health",
    address: "789 Malcolm X Blvd",
    city: "New York",
    state: "NY",
    rating: "4.6",
    reviewCount: 189,
    verified: true,
    featured: true,
    confidenceScore: 82,
    blackOwned: true,
    safetyRating: "4.7",
    wouldReturnAlone: 94,
    recommendationRate: 92,
    description: "Holistic healthcare and wellness services including acupuncture, therapy, nutrition counseling, and fitness programming rooted in African healing traditions.",
    latitude: "40.8030000",
    longitude: "-73.9500000",
    tags: ["Wellness", "Therapy", "Holistic", "Fitness"],
    reviews: [
      { id: "r1", author: "Brianna M.", initials: "BM", color: "#C4622D", rating: 5, text: "Finally a wellness center that understands my body and my culture. The practitioners are exceptional.", timeAgo: "6 days ago", wouldReturnAlone: true },
    ],
    phone: "(212) 555-0572",
    website: "ujimawellness.com",
    hours: "Mon–Fri 9am–7pm, Sat 10am–4pm",
    priceRange: "$$",
  },
  {
    id: "6",
    name: "Carter & Associates Law",
    category: "Legal",
    subcategory: "Business & Civil Rights",
    address: "5050 Wilshire Blvd",
    city: "Los Angeles",
    state: "CA",
    rating: "4.9",
    reviewCount: 67,
    verified: true,
    featured: false,
    confidenceScore: 96,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 100,
    recommendationRate: 99,
    description: "Experienced legal counsel for businesses, civil rights matters, real estate, and estate planning. Trusted advocates for our community for over 20 years.",
    latitude: "34.0625000",
    longitude: "-118.3396000",
    tags: ["Legal", "Business", "Civil Rights", "Real Estate"],
    reviews: [
      { id: "r1", author: "Reginald B.", initials: "RB", color: "#2D7A4F", rating: 5, text: "Attorney Carter fought for us when no one else would. Exceptional representation.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(310) 555-0638",
    website: "carterandassociates.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$$",
  },
  {
    id: "7",
    name: "Kingdom Cuts Barbershop",
    category: "Beauty",
    subcategory: "Barbershop",
    address: "1807 Peachtree Rd NE",
    city: "Atlanta",
    state: "GA",
    rating: "4.7",
    reviewCount: 445,
    verified: false,
    featured: false,
    confidenceScore: 71,
    blackOwned: true,
    safetyRating: "4.6",
    wouldReturnAlone: 89,
    recommendationRate: 91,
    description: "The neighborhood barbershop where cuts and conversations flow freely. Master barbers specializing in fades, lineups, and beard grooming.",
    latitude: "33.7982000",
    longitude: "-84.3749000",
    tags: ["Barbershop", "Fades", "Beard", "Walk-In"],
    reviews: [
      { id: "r1", author: "Malik J.", initials: "MJ", color: "#C4622D", rating: 5, text: "Best fades in Atlanta, period. The barbers here know their craft.", timeAgo: "2 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Andre P.", initials: "AP", color: "#D4873A", rating: 4, text: "Great cuts, sometimes a wait but worth it every time.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-0714",
    priceRange: "$",
  },
  {
    id: "8",
    name: "Melanin Money Financial",
    category: "Finance",
    subcategory: "Financial Planning",
    address: "3200 Main St",
    city: "Houston",
    state: "TX",
    rating: "4.8",
    reviewCount: 103,
    verified: true,
    featured: false,
    confidenceScore: 85,
    blackOwned: false,
    safetyRating: "4.8",
    wouldReturnAlone: 93,
    recommendationRate: 95,
    description: "Financial planning, investment advisory, and wealth-building services designed to close the racial wealth gap one family at a time.",
    latitude: "29.7449000",
    longitude: "-95.3698000",
    tags: ["Finance", "Investing", "Wealth", "Planning"],
    reviews: [
      { id: "r1", author: "Denise H.", initials: "DH", color: "#2D7A4F", rating: 5, text: "They helped me build my first investment portfolio. Truly life-changing advice.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(713) 555-0826",
    website: "melaninmoney.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$",
  },
];

async function seed() {
  console.log("Seeding businesses...");

  for (const biz of businesses) {
    await db
      .insert(businessesTable)
      .values(biz)
      .onConflictDoUpdate({
        target: businessesTable.id,
        set: {
          name: biz.name,
          rating: biz.rating,
          reviewCount: biz.reviewCount,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`Seeded ${businesses.length} businesses.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
