import { db, businessesTable } from "@workspace/db";

const businesses = [
  {
    id: "1",
    name: "Sweet Auburn BBQ",
    category: "Food",
    subcategory: "Barbecue",
    address: "656 N Highland Ave NE",
    city: "Atlanta",
    state: "GA",
    rating: "4.8",
    reviewCount: 312,
    verified: true,
    featured: true,
    confidenceScore: 94,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 98,
    description: "Award-winning BBQ rooted in Atlanta's historic Sweet Auburn district. We honor the traditions of Southern BBQ with bold flavors and community warmth.",
    latitude: "33.7641000",
    longitude: "-84.3605000",
    tags: ["BBQ", "Southern", "Takeout", "Dine-In"],
    reviews: [
      { id: "r1", author: "Simone W.", initials: "SW", color: "#3B1F0E", rating: 5, text: "Absolutely amazing! The quality and service exceeded all expectations. Will definitely be back.", timeAgo: "3 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Marcus T.", initials: "MT", color: "#C9922B", rating: 4, text: "Great experience overall. The staff was incredibly welcoming and knowledgeable.", timeAgo: "1 week ago", wouldReturnAlone: true },
      { id: "r3", author: "Aisha B.", initials: "AB", color: "#2D7A4F", rating: 5, text: "This place is a gem. So proud to support Black-owned businesses like this one.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-0191",
    website: "sweetauburnbbq.com",
    hours: "Mon–Sun 11am–9pm",
    priceRange: "$$",
  },
  {
    id: "2",
    name: "Essence Beauty Lounge",
    category: "Beauty",
    subcategory: "Salon & Spa",
    address: "3412 Westheimer Rd",
    city: "Houston",
    state: "TX",
    rating: "4.9",
    reviewCount: 218,
    verified: true,
    featured: true,
    confidenceScore: 91,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 99,
    recommendationRate: 100,
    description: "A full-service beauty experience specializing in natural hair care, braids, locs, and luxury skin treatments designed for melanin-rich skin.",
    latitude: "29.7384000",
    longitude: "-95.4620000",
    tags: ["Hair", "Natural", "Spa", "Locs", "Braids"],
    reviews: [
      { id: "r1", author: "Keisha J.", initials: "KJ", color: "#3B1F0E", rating: 5, text: "Best salon experience I've ever had. They truly understand natural hair and it shows!", timeAgo: "5 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Tamara L.", initials: "TL", color: "#2D7A4F", rating: 5, text: "My locs look absolutely stunning. The staff made me feel like royalty.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(713) 555-0247",
    website: "essencebeautylounge.com",
    hours: "Tue–Sat 9am–7pm",
    priceRange: "$$$",
  },
  {
    id: "3",
    name: "Harambee Tech Hub",
    category: "Tech",
    subcategory: "Coworking & Education",
    address: "1401 S Wabash Ave",
    city: "Chicago",
    state: "IL",
    rating: "4.7",
    reviewCount: 94,
    verified: true,
    featured: false,
    confidenceScore: 87,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 95,
    recommendationRate: 96,
    description: "A community-centered tech hub offering coworking space, coding bootcamps, and mentorship programs focused on underrepresented founders.",
    latitude: "41.8655000",
    longitude: "-87.6252000",
    tags: ["Tech", "Coworking", "Education", "Startup"],
    reviews: [
      { id: "r1", author: "Darius P.", initials: "DP", color: "#3B1F0E", rating: 5, text: "This space changed my career trajectory. The mentorship and community here are unmatched.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(312) 555-0382",
    website: "harambeetehhub.com",
    hours: "Mon–Fri 8am–8pm",
    priceRange: "$",
  },
  {
    id: "4",
    name: "Roots & Culture Bookstore",
    category: "Retail",
    subcategory: "Books & Media",
    address: "2124 Georgia Ave NW",
    city: "Washington",
    state: "DC",
    rating: "4.8",
    reviewCount: 156,
    verified: true,
    featured: false,
    confidenceScore: 89,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 98,
    recommendationRate: 97,
    description: "A beloved independent bookstore celebrating Black authors, African literature, cultural history, and community storytelling since 2009.",
    latitude: "38.9186000",
    longitude: "-77.0178000",
    tags: ["Books", "Culture", "Community", "Independent"],
    reviews: [
      { id: "r1", author: "Nadia C.", initials: "NC", color: "#C9922B", rating: 5, text: "Every visit feels like coming home. The selection of Black literature here is incredible.", timeAgo: "4 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Jerome F.", initials: "JF", color: "#2D7A4F", rating: 5, text: "A DC institution. I've been coming here for years and it only gets better.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(202) 555-0419",
    website: "rootsandculturebooks.com",
    hours: "Mon–Sat 10am–7pm, Sun 12–5pm",
    priceRange: "$",
  },
  {
    id: "5",
    name: "Ujima Wellness Center",
    category: "Health",
    subcategory: "Holistic Health",
    address: "789 Malcolm X Blvd",
    city: "New York",
    state: "NY",
    rating: "4.6",
    reviewCount: 189,
    verified: true,
    featured: true,
    confidenceScore: 82,
    blackOwned: true,
    safetyRating: "4.7",
    wouldReturnAlone: 94,
    recommendationRate: 92,
    description: "Holistic healthcare and wellness services including acupuncture, therapy, nutrition counseling, and fitness programming rooted in African healing traditions.",
    latitude: "40.8030000",
    longitude: "-73.9500000",
    tags: ["Wellness", "Therapy", "Holistic", "Fitness"],
    reviews: [
      { id: "r1", author: "Brianna M.", initials: "BM", color: "#3B1F0E", rating: 5, text: "Finally a wellness center that understands my body and my culture. The practitioners are exceptional.", timeAgo: "6 days ago", wouldReturnAlone: true },
    ],
    phone: "(212) 555-0572",
    website: "ujimawellness.com",
    hours: "Mon–Fri 9am–7pm, Sat 10am–4pm",
    priceRange: "$$",
  },
  {
    id: "6",
    name: "Carter & Associates Law",
    category: "Legal",
    subcategory: "Business & Civil Rights",
    address: "5050 Wilshire Blvd",
    city: "Los Angeles",
    state: "CA",
    rating: "4.9",
    reviewCount: 67,
    verified: true,
    featured: false,
    confidenceScore: 96,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 100,
    recommendationRate: 99,
    description: "Experienced legal counsel for businesses, civil rights matters, real estate, and estate planning. Trusted advocates for our community for over 20 years.",
    latitude: "34.0625000",
    longitude: "-118.3396000",
    tags: ["Legal", "Business", "Civil Rights", "Real Estate"],
    reviews: [
      { id: "r1", author: "Reginald B.", initials: "RB", color: "#2D7A4F", rating: 5, text: "Attorney Carter fought for us when no one else would. Exceptional representation.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(310) 555-0638",
    website: "carterandassociates.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$$",
  },
  {
    id: "7",
    name: "Kingdom Cuts Barbershop",
    category: "Beauty",
    subcategory: "Barbershop",
    address: "1807 Peachtree Rd NE",
    city: "Atlanta",
    state: "GA",
    rating: "4.7",
    reviewCount: 445,
    verified: false,
    featured: false,
    confidenceScore: 71,
    blackOwned: true,
    safetyRating: "4.6",
    wouldReturnAlone: 89,
    recommendationRate: 91,
    description: "The neighborhood barbershop where cuts and conversations flow freely. Master barbers specializing in fades, lineups, and beard grooming.",
    latitude: "33.7982000",
    longitude: "-84.3749000",
    tags: ["Barbershop", "Fades", "Beard", "Walk-In"],
    reviews: [
      { id: "r1", author: "Malik J.", initials: "MJ", color: "#3B1F0E", rating: 5, text: "Best fades in Atlanta, period. The barbers here know their craft.", timeAgo: "2 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Andre P.", initials: "AP", color: "#C9922B", rating: 4, text: "Great cuts, sometimes a wait but worth it every time.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-0714",
    priceRange: "$",
  },
  {
    id: "8",
    name: "Melanin Money Financial",
    category: "Finance",
    subcategory: "Financial Planning",
    address: "3200 Main St",
    city: "Houston",
    state: "TX",
    rating: "4.8",
    reviewCount: 103,
    verified: true,
    featured: false,
    confidenceScore: 85,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 93,
    recommendationRate: 95,
    description: "Financial planning, investment advisory, and wealth-building services designed to close the racial wealth gap one family at a time.",
    latitude: "29.7449000",
    longitude: "-95.3698000",
    tags: ["Finance", "Investing", "Wealth", "Planning"],
    reviews: [
      { id: "r1", author: "Denise H.", initials: "DH", color: "#2D7A4F", rating: 5, text: "They helped me build my first investment portfolio. Truly life-changing advice.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(713) 555-0826",
    website: "melaninmoney.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$",
  },
  {
    id: "9",
    name: "Treme Soul Kitchen",
    category: "Food",
    subcategory: "Soul Food",
    address: "1500 St Philip St",
    city: "New Orleans",
    state: "LA",
    rating: "4.9",
    reviewCount: 524,
    verified: true,
    featured: true,
    confidenceScore: 97,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 96,
    recommendationRate: 99,
    description: "Authentic New Orleans soul food from the heart of Tremé — the oldest African-American neighborhood in the country. Red beans, gumbo, and love on every plate.",
    latitude: "29.9641000",
    longitude: "-90.0680000",
    tags: ["Soul Food", "Gumbo", "Creole", "Dine-In"],
    reviews: [
      { id: "r1", author: "Celeste R.", initials: "CR", color: "#3B1F0E", rating: 5, text: "The gumbo here will change your life. Authentic, soulful, and made with love.", timeAgo: "1 day ago", wouldReturnAlone: true },
      { id: "r2", author: "Victor J.", initials: "VJ", color: "#2D7A4F", rating: 5, text: "Tremé is home and this kitchen captures everything I love about it.", timeAgo: "5 days ago", wouldReturnAlone: true },
    ],
    phone: "(504) 555-0193",
    website: "tremesoulkitchen.com",
    hours: "Wed–Mon 11am–9pm",
    priceRange: "$$",
  },
  {
    id: "10",
    name: "Sankofa Natural Apothecary",
    category: "Retail",
    subcategory: "Health & Beauty Products",
    address: "4321 Flatbush Ave",
    city: "Brooklyn",
    state: "NY",
    rating: "4.8",
    reviewCount: 271,
    verified: true,
    featured: true,
    confidenceScore: 90,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 98,
    description: "Curated natural skincare, haircare, and wellness products made for and by the Black community. Herbs, oils, and ancestral remedies reimagined.",
    latitude: "40.6501000",
    longitude: "-73.9496000",
    tags: ["Natural", "Skincare", "Haircare", "Wellness", "Apothecary"],
    reviews: [
      { id: "r1", author: "Yasmine O.", initials: "YO", color: "#C9922B", rating: 5, text: "Finally products that actually work on my skin. I won't buy from anywhere else now.", timeAgo: "3 days ago", wouldReturnAlone: true },
    ],
    phone: "(718) 555-0295",
    website: "sankofaapothecary.com",
    hours: "Mon–Sat 10am–8pm, Sun 11am–6pm",
    priceRange: "$$",
  },
  {
    id: "11",
    name: "Kulture Kitchen",
    category: "Food",
    subcategory: "Pan-African Cuisine",
    address: "2200 Martin Luther King Jr Dr SW",
    city: "Atlanta",
    state: "GA",
    rating: "4.7",
    reviewCount: 188,
    verified: true,
    featured: false,
    confidenceScore: 88,
    blackOwned: true,
    safetyRating: "4.7",
    wouldReturnAlone: 92,
    recommendationRate: 94,
    description: "A celebration of the African diaspora on every plate. From jerk chicken to jollof rice, egusi to oxtail — this is Pan-African cooking done with reverence.",
    latitude: "33.7417000",
    longitude: "-84.4137000",
    tags: ["Pan-African", "Caribbean", "West African", "Dine-In", "Takeout"],
    reviews: [
      { id: "r1", author: "Amara N.", initials: "AN", color: "#3B1F0E", rating: 5, text: "The jollof rice tastes like my grandmother's. Incredible flavors, warm staff.", timeAgo: "2 days ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-0312",
    hours: "Tue–Sun 12pm–9pm",
    priceRange: "$$",
  },
  {
    id: "12",
    name: "Iron & Thread Boutique",
    category: "Retail",
    subcategory: "Clothing & Fashion",
    address: "1142 U St NW",
    city: "Washington",
    state: "DC",
    rating: "4.6",
    reviewCount: 132,
    verified: true,
    featured: false,
    confidenceScore: 83,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 94,
    recommendationRate: 93,
    description: "Contemporary fashion celebrating Black designers, Afrocentric prints, and culturally inspired streetwear. Supporting independent Black fashion from across the diaspora.",
    latitude: "38.9167000",
    longitude: "-77.0326000",
    tags: ["Fashion", "Afrocentric", "Streetwear", "Designers"],
    reviews: [
      { id: "r1", author: "Zoe P.", initials: "ZP", color: "#2D7A4F", rating: 5, text: "Every piece here tells a story. The curation is impeccable and so intentional.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(202) 555-0441",
    website: "ironandthread.com",
    hours: "Mon–Sat 11am–7pm",
    priceRange: "$$",
  },
  {
    id: "13",
    name: "Griot's Coffee & Study Hall",
    category: "Food",
    subcategory: "Coffee & Café",
    address: "5620 Crenshaw Blvd",
    city: "Los Angeles",
    state: "CA",
    rating: "4.8",
    reviewCount: 347,
    verified: true,
    featured: true,
    confidenceScore: 92,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 98,
    recommendationRate: 97,
    description: "A community coffee house and study space in the heart of Crenshaw. Specialty coffee, African teas, and a safe space for creators, students, and thinkers.",
    latitude: "33.9929000",
    longitude: "-118.3324000",
    tags: ["Coffee", "Study", "Community", "Cowork"],
    reviews: [
      { id: "r1", author: "Jordan T.", initials: "JT", color: "#C9922B", rating: 5, text: "The best third space in LA. Great coffee, even better energy.", timeAgo: "4 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Monique S.", initials: "MS", color: "#3B1F0E", rating: 5, text: "I come here every weekend to write. The atmosphere is unmatched.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(323) 555-0587",
    website: "griotscoffee.com",
    hours: "Mon–Sun 7am–9pm",
    priceRange: "$",
  },
  {
    id: "14",
    name: "Heritage Physical Therapy",
    category: "Health",
    subcategory: "Physical Therapy",
    address: "3800 W Florist Ave",
    city: "Milwaukee",
    state: "WI",
    rating: "4.7",
    reviewCount: 88,
    verified: true,
    featured: false,
    confidenceScore: 84,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 96,
    recommendationRate: 95,
    description: "Patient-centered physical therapy and sports rehabilitation. Dr. Heritage and her team specialize in musculoskeletal care with a culturally sensitive approach.",
    latitude: "43.0877000",
    longitude: "-87.9771000",
    tags: ["Physical Therapy", "Sports", "Rehab", "Health"],
    reviews: [
      { id: "r1", author: "Raymond G.", initials: "RG", color: "#2D7A4F", rating: 5, text: "Dr. Heritage is brilliant. She had me back on my feet in half the time I expected.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(414) 555-0629",
    website: "heritagept.com",
    hours: "Mon–Fri 8am–6pm",
    priceRange: "$$",
  },
  {
    id: "15",
    name: "Afro-Fusion Braiding Studio",
    category: "Beauty",
    subcategory: "Hair Braiding",
    address: "742 Sweet Auburn Ave NE",
    city: "Atlanta",
    state: "GA",
    rating: "4.9",
    reviewCount: 631,
    verified: true,
    featured: true,
    confidenceScore: 95,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 99,
    recommendationRate: 100,
    description: "Expert braiding artists specializing in knotless braids, Senegalese twists, cornrows, and protective styles. Appointments and walk-ins welcome.",
    latitude: "33.7538000",
    longitude: "-84.3773000",
    tags: ["Braiding", "Knotless", "Protective Styles", "Natural Hair"],
    reviews: [
      { id: "r1", author: "Fatima B.", initials: "FB", color: "#3B1F0E", rating: 5, text: "Best braids I've ever had. The technique is flawless and the styles last for weeks.", timeAgo: "2 days ago", wouldReturnAlone: true },
      { id: "r2", author: "Nia W.", initials: "NW", color: "#C9922B", rating: 5, text: "Came from out of town just for this studio. Worth every mile.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-0751",
    hours: "Tue–Sun 9am–7pm",
    priceRange: "$$",
  },
  {
    id: "16",
    name: "Black Pearl Investment Group",
    category: "Finance",
    subcategory: "Investment & Wealth",
    address: "1 Biscayne Tower, Suite 2400",
    city: "Miami",
    state: "FL",
    rating: "4.9",
    reviewCount: 54,
    verified: true,
    featured: false,
    confidenceScore: 93,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 100,
    recommendationRate: 100,
    description: "Boutique investment firm focused on building generational wealth in Black communities through real estate, equities, and business lending.",
    latitude: "25.7745000",
    longitude: "-80.1880000",
    tags: ["Investing", "Real Estate", "Wealth", "Finance"],
    reviews: [
      { id: "r1", author: "Harold E.", initials: "HE", color: "#2D7A4F", rating: 5, text: "They genuinely understand our community's needs. My portfolio has never been stronger.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(305) 555-0814",
    website: "blackpearlinvestments.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$$",
  },
  {
    id: "17",
    name: "Soledad Yoga & Movement",
    category: "Health",
    subcategory: "Yoga & Fitness",
    address: "2701 N Broad St",
    city: "Philadelphia",
    state: "PA",
    rating: "4.8",
    reviewCount: 142,
    verified: true,
    featured: false,
    confidenceScore: 86,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 96,
    description: "A yoga and movement studio that centers the experiences of Black, Indigenous, and People of Color. Trauma-informed instruction in a safe, affirming space.",
    latitude: "39.9888000",
    longitude: "-75.1560000",
    tags: ["Yoga", "Fitness", "Wellness", "BIPOC", "Mindfulness"],
    reviews: [
      { id: "r1", author: "Camille F.", initials: "CF", color: "#3B1F0E", rating: 5, text: "This studio healed me in ways I didn't know I needed. The instructors are phenomenal.", timeAgo: "3 days ago", wouldReturnAlone: true },
    ],
    phone: "(215) 555-0922",
    website: "soledadyoga.com",
    hours: "Mon–Sun 6am–9pm",
    priceRange: "$$",
  },
  {
    id: "18",
    name: "Uhuru Tech Solutions",
    category: "Tech",
    subcategory: "IT & Software",
    address: "8700 McKinney Ave",
    city: "Dallas",
    state: "TX",
    rating: "4.7",
    reviewCount: 76,
    verified: true,
    featured: false,
    confidenceScore: 88,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 95,
    recommendationRate: 93,
    description: "Minority-owned IT consulting and software development firm serving small businesses and nonprofits. Cloud migration, app development, and cybersecurity.",
    latitude: "32.8182000",
    longitude: "-96.7948000",
    tags: ["IT", "Software", "Consulting", "Cybersecurity", "Cloud"],
    reviews: [
      { id: "r1", author: "Terrence O.", initials: "TO", color: "#C9922B", rating: 5, text: "Migrated our entire operation to the cloud seamlessly. Professional, affordable, community-minded.", timeAgo: "1 month ago", wouldReturnAlone: true },
    ],
    phone: "(214) 555-1038",
    website: "uhurtech.com",
    hours: "Mon–Fri 9am–6pm",
    priceRange: "$$",
  },
  {
    id: "19",
    name: "Jazz & Java Lounge",
    category: "Food",
    subcategory: "Coffee & Jazz",
    address: "3201 Frenchmen St",
    city: "New Orleans",
    state: "LA",
    rating: "4.9",
    reviewCount: 489,
    verified: true,
    featured: true,
    confidenceScore: 96,
    blackOwned: true,
    safetyRating: "4.7",
    wouldReturnAlone: 93,
    recommendationRate: 98,
    description: "Live jazz every night on the Frenchmen Street art corridor. Specialty coffee, local craft beers, and small plates in an intimate setting celebrating Black musical heritage.",
    latitude: "29.9618000",
    longitude: "-90.0570000",
    tags: ["Jazz", "Coffee", "Live Music", "Nightlife"],
    reviews: [
      { id: "r1", author: "Simone L.", initials: "SL", color: "#2D7A4F", rating: 5, text: "Stepped in for one drink and stayed for three hours. The music is transcendent.", timeAgo: "2 days ago", wouldReturnAlone: true },
    ],
    phone: "(504) 555-1124",
    hours: "Mon–Sun 4pm–2am",
    priceRange: "$$",
  },
  {
    id: "20",
    name: "Legacy Legal Group",
    category: "Legal",
    subcategory: "Family & Estate Law",
    address: "1400 Coleman Ave",
    city: "Macon",
    state: "GA",
    rating: "4.8",
    reviewCount: 48,
    verified: true,
    featured: false,
    confidenceScore: 87,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 98,
    recommendationRate: 97,
    description: "Family-focused law firm specializing in estate planning, wills, trusts, and generational wealth protection. Ensuring Black families keep and grow what they build.",
    latitude: "32.8407000",
    longitude: "-83.6324000",
    tags: ["Estate", "Family Law", "Wills", "Trusts"],
    reviews: [
      { id: "r1", author: "Barbara K.", initials: "BK", color: "#3B1F0E", rating: 5, text: "They helped us set up our family trust. Patient, thorough, and genuinely caring.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(478) 555-1219",
    website: "legacylegalgroup.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$",
  },
  {
    id: "21",
    name: "Cultivate Organic Market",
    category: "Retail",
    subcategory: "Grocery & Health Foods",
    address: "5000 Woodward Ave",
    city: "Detroit",
    state: "MI",
    rating: "4.6",
    reviewCount: 203,
    verified: true,
    featured: false,
    confidenceScore: 81,
    blackOwned: true,
    safetyRating: "4.6",
    wouldReturnAlone: 88,
    recommendationRate: 90,
    description: "Community-focused organic grocery and fresh produce market bringing healthy, affordable food options to underserved Detroit neighborhoods.",
    latitude: "42.3707000",
    longitude: "-83.0662000",
    tags: ["Organic", "Grocery", "Produce", "Community", "Health"],
    reviews: [
      { id: "r1", author: "Phyllis M.", initials: "PM", color: "#C9922B", rating: 5, text: "This market is a lifeline for our neighborhood. Fresh produce, fair prices, community love.", timeAgo: "5 days ago", wouldReturnAlone: true },
    ],
    phone: "(313) 555-1347",
    hours: "Mon–Sun 8am–8pm",
    priceRange: "$",
  },
  {
    id: "22",
    name: "Crown & Glory Wig Studio",
    category: "Beauty",
    subcategory: "Wigs & Extensions",
    address: "7720 S Shore Dr",
    city: "Chicago",
    state: "IL",
    rating: "4.8",
    reviewCount: 387,
    verified: true,
    featured: false,
    confidenceScore: 90,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 96,
    recommendationRate: 97,
    description: "Premium wig studio offering custom units, wig installations, and hair topper consultations. Specializing in lace fronts, full lace, and medical wigs for alopecia clients.",
    latitude: "41.7522000",
    longitude: "-87.5896000",
    tags: ["Wigs", "Extensions", "Lace Front", "Medical Wigs"],
    reviews: [
      { id: "r1", author: "Latoya C.", initials: "LC", color: "#3B1F0E", rating: 5, text: "They custom-made my unit and it looks completely natural. I've never felt more confident.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(773) 555-1458",
    website: "crownandglorywigs.com",
    hours: "Tue–Sat 9am–6pm",
    priceRange: "$$",
  },
  {
    id: "23",
    name: "Nexus Coworking",
    category: "Tech",
    subcategory: "Coworking Space",
    address: "300 NE 2nd Ave",
    city: "Miami",
    state: "FL",
    rating: "4.7",
    reviewCount: 121,
    verified: true,
    featured: false,
    confidenceScore: 85,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 95,
    description: "Miami's premier Black-owned coworking space for entrepreneurs, creatives, and remote professionals. Private offices, hot desks, event space, and pitch mentorship.",
    latitude: "25.7839000",
    longitude: "-80.1926000",
    tags: ["Cowork", "Startup", "Entrepreneurship", "Networking"],
    reviews: [
      { id: "r1", author: "Roberto A.", initials: "RA", color: "#2D7A4F", rating: 5, text: "The community here is electric. Met two of my best collaborators in this building.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(305) 555-1563",
    website: "nexuscoworkingmia.com",
    hours: "Mon–Fri 8am–8pm, Sat 10am–4pm",
    priceRange: "$$",
  },
  {
    id: "24",
    name: "Nana's Southern Table",
    category: "Food",
    subcategory: "Soul Food",
    address: "2340 Adam Clayton Powell Jr Blvd",
    city: "New York",
    state: "NY",
    rating: "4.8",
    reviewCount: 562,
    verified: true,
    featured: true,
    confidenceScore: 93,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 95,
    recommendationRate: 97,
    description: "Harlem's most-loved soul food destination. Fried chicken, collard greens, mac & cheese, and sweet potato pie made from recipes passed down through generations.",
    latitude: "40.8139000",
    longitude: "-73.9498000",
    tags: ["Soul Food", "Southern", "Harlem", "Comfort Food"],
    reviews: [
      { id: "r1", author: "Gladys T.", initials: "GT", color: "#C9922B", rating: 5, text: "Tastes exactly like my grandmother's kitchen. I cry every time I eat the greens.", timeAgo: "1 day ago", wouldReturnAlone: true },
    ],
    phone: "(212) 555-1672",
    hours: "Mon–Sun 10am–10pm",
    priceRange: "$",
  },
  {
    id: "25",
    name: "Sanara Healing Arts",
    category: "Health",
    subcategory: "Mental Health & Therapy",
    address: "4101 Laclede Ave",
    city: "St. Louis",
    state: "MO",
    rating: "4.9",
    reviewCount: 93,
    verified: true,
    featured: false,
    confidenceScore: 91,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 99,
    recommendationRate: 100,
    description: "A culturally affirming mental health practice with Black therapists who specialize in racial trauma, anxiety, family systems, and LGBTQ+ affirming care.",
    latitude: "38.6436000",
    longitude: "-90.2597000",
    tags: ["Mental Health", "Therapy", "Trauma", "Affirming Care"],
    reviews: [
      { id: "r1", author: "Jada W.", initials: "JW", color: "#3B1F0E", rating: 5, text: "My therapist here understood my experience in a way no one else ever has. Transformative.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(314) 555-1789",
    website: "sanarahealingarts.com",
    hours: "Mon–Fri 9am–7pm",
    priceRange: "$$",
  },
  {
    id: "26",
    name: "The Trap Kitchen ATL",
    category: "Food",
    subcategory: "Caribbean Fusion",
    address: "916 Cascade Rd SW",
    city: "Atlanta",
    state: "GA",
    rating: "4.7",
    reviewCount: 728,
    verified: false,
    featured: false,
    confidenceScore: 76,
    blackOwned: true,
    safetyRating: "4.5",
    wouldReturnAlone: 85,
    recommendationRate: 89,
    description: "Viral Caribbean-fusion street food turned brick-and-mortar. Famous for the lobster mac, oxtail nachos, and energy that hits different after midnight.",
    latitude: "33.7196000",
    longitude: "-84.4260000",
    tags: ["Caribbean", "Fusion", "Street Food", "Viral"],
    reviews: [
      { id: "r1", author: "DeShawn K.", initials: "DK", color: "#C9922B", rating: 5, text: "The lobster mac changed my life. Worth every dollar and every minute of wait time.", timeAgo: "3 days ago", wouldReturnAlone: false },
    ],
    phone: "(404) 555-1893",
    hours: "Wed–Sun 5pm–2am",
    priceRange: "$$",
  },
  {
    id: "27",
    name: "Verdant Landscape & Design",
    category: "Retail",
    subcategory: "Home & Garden",
    address: "2500 S Tryon St",
    city: "Charlotte",
    state: "NC",
    rating: "4.6",
    reviewCount: 77,
    verified: true,
    featured: false,
    confidenceScore: 80,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 93,
    recommendationRate: 91,
    description: "Full-service landscape design, installation, and garden maintenance. Specializing in native plants and sustainable design for residential and commercial clients.",
    latitude: "35.1899000",
    longitude: "-80.8692000",
    tags: ["Landscaping", "Garden", "Sustainable", "Design"],
    reviews: [
      { id: "r1", author: "Michelle R.", initials: "MR", color: "#2D7A4F", rating: 5, text: "They transformed our backyard into an oasis. Reliable, creative, and professional.", timeAgo: "1 month ago", wouldReturnAlone: true },
    ],
    phone: "(704) 555-1974",
    website: "verdantdesignco.com",
    hours: "Mon–Fri 8am–5pm",
    priceRange: "$$",
  },
  {
    id: "28",
    name: "Freeborn Roasters",
    category: "Food",
    subcategory: "Coffee & Café",
    address: "1834 Pennsylvania Ave SE",
    city: "Washington",
    state: "DC",
    rating: "4.9",
    reviewCount: 408,
    verified: true,
    featured: true,
    confidenceScore: 95,
    blackOwned: true,
    safetyRating: "5.0",
    wouldReturnAlone: 99,
    recommendationRate: 100,
    description: "Specialty coffee roastery and café sourcing single-origin beans directly from Black and African farmers. Every cup funds education scholarships.",
    latitude: "38.8824000",
    longitude: "-76.9859000",
    tags: ["Coffee", "Specialty", "Roastery", "Community"],
    reviews: [
      { id: "r1", author: "Alexis J.", initials: "AJ", color: "#3B1F0E", rating: 5, text: "The best coffee in DC, full stop. And the mission behind it makes it taste even better.", timeAgo: "1 day ago", wouldReturnAlone: true },
      { id: "r2", author: "Curtis M.", initials: "CM", color: "#C9922B", rating: 5, text: "Came for the coffee, stayed for the community. This place is something special.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(202) 555-2081",
    website: "freebornroasters.com",
    hours: "Mon–Sun 7am–7pm",
    priceRange: "$",
  },
  {
    id: "29",
    name: "Wright Financial Literacy Center",
    category: "Finance",
    subcategory: "Financial Education",
    address: "6100 W Florissant Ave",
    city: "St. Louis",
    state: "MO",
    rating: "4.8",
    reviewCount: 61,
    verified: true,
    featured: false,
    confidenceScore: 86,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 96,
    description: "Free and low-cost financial literacy classes, credit coaching, and homebuyer education programs for Black families working toward economic independence.",
    latitude: "38.7068000",
    longitude: "-90.2714000",
    tags: ["Financial Literacy", "Credit", "Homebuyer", "Education", "Free"],
    reviews: [
      { id: "r1", author: "Sandra H.", initials: "SH", color: "#2D7A4F", rating: 5, text: "This center helped me go from 540 to 720 credit in one year. I'm now a homeowner.", timeAgo: "2 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(314) 555-2196",
    hours: "Mon, Wed, Fri 10am–6pm, Sat 9am–1pm",
    priceRange: "$",
  },
  {
    id: "30",
    name: "Inkwell Tattoo & Art Gallery",
    category: "Retail",
    subcategory: "Art & Tattoo",
    address: "2100 NW 2nd Ave",
    city: "Miami",
    state: "FL",
    rating: "4.9",
    reviewCount: 234,
    verified: true,
    featured: true,
    confidenceScore: 94,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 98,
    recommendationRate: 99,
    description: "Award-winning tattoo studio and rotating art gallery in Wynwood showcasing Black artists. Fine line, realism, and Afrocentric tattoo artistry at the highest level.",
    latitude: "25.8008000",
    longitude: "-80.1983000",
    tags: ["Tattoo", "Art", "Gallery", "Afrocentric", "Fine Line"],
    reviews: [
      { id: "r1", author: "Tasha N.", initials: "TN", color: "#3B1F0E", rating: 5, text: "My sleeve is a masterpiece. Every artist here is world-class.", timeAgo: "4 days ago", wouldReturnAlone: true },
    ],
    phone: "(786) 555-2307",
    website: "inkwellmia.com",
    hours: "Tue–Sun 12pm–9pm",
    priceRange: "$$$",
  },
  {
    id: "31",
    name: "Rebuild Nation Construction",
    category: "Tech",
    subcategory: "Construction & Design",
    address: "4444 W Chicago Ave",
    city: "Chicago",
    state: "IL",
    rating: "4.7",
    reviewCount: 58,
    verified: true,
    featured: false,
    confidenceScore: 83,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 94,
    recommendationRate: 93,
    description: "Community-focused general contracting firm specializing in residential rehab, commercial build-outs, and affordable housing development on Chicago's West Side.",
    latitude: "41.8953000",
    longitude: "-87.7385000",
    tags: ["Construction", "Rehab", "Affordable Housing", "Commercial"],
    reviews: [
      { id: "r1", author: "Patrick S.", initials: "PS", color: "#C9922B", rating: 5, text: "On time, on budget, beautiful work. Rare to find contractors this professional and community-minded.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(773) 555-2419",
    hours: "Mon–Fri 7am–5pm",
    priceRange: "$$$",
  },
  {
    id: "32",
    name: "Nile Valley Juice Bar",
    category: "Food",
    subcategory: "Juice & Health Food",
    address: "750 Joseph E Lowery Blvd SW",
    city: "Atlanta",
    state: "GA",
    rating: "4.8",
    reviewCount: 293,
    verified: true,
    featured: false,
    confidenceScore: 89,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 97,
    recommendationRate: 98,
    description: "Cold-pressed juices, smoothies, and plant-based meals rooted in African and Caribbean nutritional traditions. No preservatives, no shortcuts — just real food.",
    latitude: "33.7424000",
    longitude: "-84.4053000",
    tags: ["Juice", "Vegan", "Plant-Based", "Health", "Smoothies"],
    reviews: [
      { id: "r1", author: "Serena B.", initials: "SB", color: "#2D7A4F", rating: 5, text: "The green detox blend cured my entire soul. I come here every morning before work.", timeAgo: "2 days ago", wouldReturnAlone: true },
    ],
    phone: "(404) 555-2534",
    hours: "Mon–Sun 7am–6pm",
    priceRange: "$",
  },
  {
    id: "33",
    name: "Baldwin & Brown Advertising",
    category: "Tech",
    subcategory: "Marketing & Advertising",
    address: "400 Renaissance Center",
    city: "Detroit",
    state: "MI",
    rating: "4.7",
    reviewCount: 42,
    verified: true,
    featured: false,
    confidenceScore: 82,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 95,
    recommendationRate: 93,
    description: "Full-service digital marketing and brand strategy agency with deep expertise in reaching multicultural audiences. Brand storytelling with cultural authenticity.",
    latitude: "42.3293000",
    longitude: "-83.0398000",
    tags: ["Marketing", "Branding", "Digital", "Strategy"],
    reviews: [
      { id: "r1", author: "Lisa T.", initials: "LT", color: "#3B1F0E", rating: 5, text: "They understood our brand's soul instantly. Our campaign reach tripled in two months.", timeAgo: "1 month ago", wouldReturnAlone: true },
    ],
    phone: "(313) 555-2648",
    website: "baldwinbrownadv.com",
    hours: "Mon–Fri 9am–5pm",
    priceRange: "$$$",
  },
  {
    id: "34",
    name: "Queen City Fitness",
    category: "Health",
    subcategory: "Gym & Fitness",
    address: "3900 Freedom Dr",
    city: "Charlotte",
    state: "NC",
    rating: "4.6",
    reviewCount: 167,
    verified: true,
    featured: false,
    confidenceScore: 80,
    blackOwned: true,
    safetyRating: "4.8",
    wouldReturnAlone: 93,
    recommendationRate: 91,
    description: "A body-positive gym and fitness community designed to make wellness accessible for everyone. Group classes, personal training, and nutrition coaching.",
    latitude: "35.2131000",
    longitude: "-80.9148000",
    tags: ["Gym", "Fitness", "Personal Training", "Group Classes"],
    reviews: [
      { id: "r1", author: "Marcus D.", initials: "MD", color: "#C9922B", rating: 5, text: "Finally a gym where I feel like I belong. The trainers are encouraging and the community is everything.", timeAgo: "1 week ago", wouldReturnAlone: true },
    ],
    phone: "(704) 555-2753",
    website: "queencityfitness.com",
    hours: "Mon–Fri 5am–10pm, Sat–Sun 7am–7pm",
    priceRange: "$",
  },
  {
    id: "35",
    name: "House of Praise Event Space",
    category: "Retail",
    subcategory: "Event Venue",
    address: "1900 E MLK Blvd",
    city: "Austin",
    state: "TX",
    rating: "4.8",
    reviewCount: 119,
    verified: true,
    featured: false,
    confidenceScore: 87,
    blackOwned: true,
    safetyRating: "4.9",
    wouldReturnAlone: 96,
    recommendationRate: 97,
    description: "A beautiful multipurpose event venue serving the Austin community for weddings, celebrations, corporate events, and community gatherings. Catering partnerships available.",
    latitude: "30.2817000",
    longitude: "-97.7161000",
    tags: ["Events", "Venue", "Wedding", "Corporate", "Community"],
    reviews: [
      { id: "r1", author: "Denise R.", initials: "DR", color: "#2D7A4F", rating: 5, text: "Had our wedding here and it was beyond perfect. The staff treated us like royalty.", timeAgo: "3 weeks ago", wouldReturnAlone: true },
    ],
    phone: "(512) 555-2864",
    website: "houseofpraiseatx.com",
    hours: "By appointment",
    priceRange: "$$$",
  },
];

async function seed() {
  console.log("Seeding businesses...");

  for (const biz of businesses) {
    await db
      .insert(businessesTable)
      .values(biz)
      .onConflictDoUpdate({
        target: businessesTable.id,
        set: {
          name: biz.name,
          rating: biz.rating,
          reviewCount: biz.reviewCount,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`Seeded ${businesses.length} businesses.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
