/**
 * MWM Specialties Vocabulary v1.0
 *
 * Controlled vocabulary of Specialties per subcategory.
 * Specialties are a first-class searchable field — 5–8 per business.
 * Custom suggestions from businesses go to the admin specialty_suggestions queue.
 *
 * RULES:
 * - Always key by the exact subcategory name used in the platform
 * - 15–30 terms per subcategory; aim for cultural specificity
 * - Never duplicate a term across subcategories
 * - Any new term must be added here AND mirrored to lib/constants/src/specialties.ts
 */

export const SPECIALTIES_BY_SUBCATEGORY: Record<string, string[]> = {
  // ─── FOOD & DRINK ──────────────────────────────────────────────────────────
  "Restaurants": [
    "Soul Food",
    "Southern Comfort Cooking",
    "Caribbean Cuisine",
    "Ethiopian / East African",
    "West African",
    "Nigerian",
    "Jamaican",
    "Haitian",
    "Senegalese",
    "Creole & Cajun",
    "Vegan Soul Food",
    "Plant-Based",
    "Brunch & Breakfast",
    "Seafood",
    "BBQ & Smoked Meats",
    "Homestyle Cooking",
    "Jazz Dining Experience",
    "Pan-African Cuisine",
    "Latin-Soul Fusion",
    "Small Plates & Tapas",
    "Family-Style Dining",
    "Chef's Tasting Menu",
  ],
  "Cafés & Coffee Shops": [
    "Specialty Coffee",
    "Black-Owned Roasted Beans",
    "Matcha & Tea Service",
    "Vegan Pastries",
    "Community Gathering Space",
    "Remote Work Friendly",
    "Study-Friendly Atmosphere",
    "Open Mic Venue",
    "Art Gallery Café",
    "Fresh Juice Bar",
    "Smoothie Bar",
    "Herbal & Wellness Teas",
  ],
  "Bakeries & Dessert Shops": [
    "Custom Cakes",
    "Wedding Cakes",
    "Pound Cake",
    "Sweet Potato Pie",
    "Banana Pudding",
    "Cheesecakes",
    "Vegan Desserts",
    "Gluten-Free Options",
    "Cookies & Brownies",
    "Cupcakes",
    "Caribbean Sweets",
    "African-Inspired Desserts",
    "Pastries & Croissants",
  ],
  "Food Trucks & Pop-Ups": [
    "Soul Food",
    "Caribbean",
    "African Cuisine",
    "Vegan / Plant-Based",
    "BBQ & Grills",
    "Seafood",
    "Tacos & Fusion",
    "Desserts & Sweets",
    "Catering Available",
    "Festival & Event Vendor",
  ],
  "Catering Services": [
    "Wedding Catering",
    "Corporate Catering",
    "Family Reunions",
    "Repast & Homegoing Catering",
    "Drop-Off Catering",
    "Full-Service Catering with Staff",
    "Soul Food Buffet",
    "Caribbean Spreads",
    "African Cuisine",
    "Vegan & Vegetarian Menus",
    "Dietary Accommodations",
  ],
  "Bars & Lounges": [
    "Craft Cocktails",
    "Mocktail Menu",
    "Wine Bar",
    "Caribbean Spirits",
    "African Wines & Spirits",
    "Live Music",
    "DJ Nights",
    "Happy Hour",
    "Hookah Lounge",
    "Rooftop Experience",
    "Upscale Casual",
    "Sports Lounge",
  ],

  // ─── BEAUTY & PERSONAL CARE ────────────────────────────────────────────────
  "Hair Salons & Natural Hair": [
    "Knotless Braids",
    "Box Braids",
    "Feed-In Braids",
    "Goddess Braids",
    "Sisterlocks",
    "Traditional Locs",
    "Starter Locs",
    "Loc Retwist & Maintenance",
    "Natural Styling",
    "TWA Styling",
    "Silk Press",
    "Protective Styles",
    "Weave Installation",
    "Quick Weave",
    "Sew-In Extensions",
    "Natural Color",
    "Color Correction",
    "Keratin Treatment",
    "Big Chop Consultations",
    "Wig Customization",
  ],
  "Barbershops": [
    "Fades",
    "Skin Fades",
    "Bald Fades",
    "Taper Cuts",
    "Shape-Ups",
    "Line-Ups & Edge Work",
    "Beard Trims",
    "Full Beard Design & Sculpting",
    "Hot Towel Shaves",
    "Kids Cuts",
    "Hair Designs & Engravings",
    "Loc Grooming",
    "Afro Shaping",
    "Waves & Texture Work",
  ],
  "Nail Salons & Nail Artists": [
    "Acrylic Full Set",
    "Acrylic Fill",
    "Gel Nails",
    "Hard Gel Extensions",
    "Dip Powder",
    "Press-On Nail Sets",
    "Nail Art",
    "3D Nail Art",
    "Chrome & Mirror Nails",
    "Ombre Nails",
    "French Tip",
    "Nude & Minimalist Nails",
    "Pedicures",
    "Spa Pedicures",
    "Nail Repair",
    "Natural Nail Care",
    "Polygel",
  ],
  "Spas & Wellness Retreats": [
    "Therapeutic Massage",
    "Deep Tissue Massage",
    "Swedish Massage",
    "Hot Stone Massage",
    "Prenatal Massage",
    "Couples Massage",
    "Facials",
    "Body Wraps & Scrubs",
    "Waxing",
    "Lash Extensions",
    "Brow Shaping & Tinting",
    "Aromatherapy",
    "Infrared Sauna",
  ],
  "Beauty Supply": [
    "Human Hair Extensions",
    "Synthetic Hair",
    "Braiding Hair",
    "Lace Front Wigs",
    "Full Lace Wigs",
    "Crochet Hair",
    "Loc Extensions",
    "Natural Hair Products",
    "Loc Maintenance Products",
    "Skincare",
    "Weave & Weft Hair",
    "Tools & Appliances",
    "Protective Accessories",
    "Men's Grooming",
    "Makeup",
  ],
  "Skincare & Esthetics": [
    "Facials",
    "Chemical Peels",
    "Dermaplaning",
    "Microneedling",
    "Hyperpigmentation Treatment",
    "Dark Spot Correction",
    "Melanin-Safe Skincare",
    "Acne Treatment",
    "Anti-Aging Treatments",
    "Body Treatments",
    "Waxing",
    "Sugaring",
    "Eyebrow & Lash Services",
    "Holistic Skincare",
  ],

  // ─── HEALTH & WELLNESS ─────────────────────────────────────────────────────
  "Fitness & Training": [
    "Personal Training",
    "Group Fitness Classes",
    "Boxing & Combat Sports",
    "Dance Fitness",
    "Yoga Instruction",
    "Pilates",
    "Weight Loss Programs",
    "Athletic Performance Training",
    "Senior Fitness",
    "Youth Sports Training",
    "Online Coaching",
    "Nutrition Planning",
  ],
  "Mental Health & Therapy": [
    "Individual Therapy",
    "Couples Counseling",
    "Family Therapy",
    "Trauma-Informed Care",
    "BIPOC-Affirming Therapy",
    "LGBTQ+ Affirming Therapy",
    "Grief & Loss Counseling",
    "Anxiety & Depression",
    "EMDR",
    "Cognitive Behavioral Therapy (CBT)",
    "Life Coaching",
    "Substance Use Counseling",
    "Teletherapy",
  ],
  "Holistic & Alternative Health": [
    "Acupuncture",
    "Reiki & Energy Healing",
    "Sound Healing",
    "Herbalism",
    "Naturopathy",
    "Chiropractic Care",
    "Nutritional Counseling",
    "Ayurveda",
    "Reflexology",
    "Cupping Therapy",
    "Ancestral Healing Practices",
    "Breathwork & Meditation",
  ],

  // ─── PROFESSIONAL SERVICES ─────────────────────────────────────────────────
  "Financial Services": [
    "Personal Tax Preparation",
    "Small Business Tax Filing",
    "Business Formation (LLC/Corp)",
    "Business Credit Building",
    "Bookkeeping",
    "Payroll Services",
    "Financial Planning",
    "Retirement Planning",
    "Wealth Management",
    "Real Estate Investment Consulting",
    "Grant Writing",
    "Business Plan Development",
    "Credit Repair",
  ],
  "Insurance": [
    "Life Insurance",
    "Term Life Insurance",
    "Whole Life Insurance",
    "Final Expense Coverage",
    "Auto Insurance",
    "Home & Renters Insurance",
    "Business Insurance",
    "Health Insurance",
    "Medicare & Medicaid",
    "Medicare Supplement Plans",
    "Group Employee Benefits",
    "Commercial Insurance",
    "Disability Insurance",
  ],
  "Legal Services": [
    "Immigration Law",
    "Family Law & Divorce",
    "Criminal Defense",
    "Expungements",
    "Civil Rights Law",
    "Estate Planning & Wills",
    "Trusts & Probate",
    "Business Law",
    "Contracts & Agreements",
    "Real Estate Law",
    "Personal Injury",
    "Tenant Rights",
    "Employment Law",
  ],
  "Staffing & Recruiting": [
    "Healthcare Staffing",
    "IT & Technology Recruiting",
    "Administrative Staffing",
    "Executive Search",
    "Diversity & Inclusion Recruiting",
    "Skilled Trades Placement",
    "Remote Work Placement",
    "Temp-to-Perm Placement",
    "Entry-Level Placement",
    "HR Consulting",
    "Resume & Interview Coaching",
    "Career Transitions",
  ],
  "Translation & Interpretation": [
    "Legal Translation",
    "Medical Interpretation",
    "Business Document Translation",
    "Immigration Document Translation",
    "Court Interpretation",
    "Conference Interpretation",
    "Community Interpretation",
    "Spanish",
    "French",
    "Haitian Creole",
    "Portuguese",
    "Amharic & East African Languages",
    "Arabic",
    "ASL Interpretation",
  ],

  // ─── TRAVEL & HOSPITALITY ──────────────────────────────────────────────────
  "Travel Agencies": [
    "Group Travel",
    "Honeymoon & Romance Travel",
    "Destination Weddings",
    "Africa Travel",
    "Caribbean Travel",
    "Europe Travel",
    "Cruise Packages",
    "Adventure Travel",
    "Luxury Travel",
    "Family Travel",
    "Solo Female Travel",
    "Cultural Heritage Tours",
    "LGBTQ+ Affirming Travel",
    "All-Inclusive Packages",
    "Visa & Documentation Assistance",
    "Corporate Travel",
  ],
  "Tour Guides & Experiences": [
    "Black History Tours",
    "Cultural Walking Tours",
    "Food Tours",
    "Neighborhood History",
    "Architecture & Heritage",
    "African Diaspora Tours",
    "Civil Rights History",
    "Underground Railroad History",
    "Art & Murals Tours",
    "Ghost Tours",
    "Nightlife Tours",
    "Eco & Nature Tours",
    "Private Group Tours",
  ],
  "Hotels & Lodging": [
    "Black-Owned Boutique Hotel",
    "Bed & Breakfast",
    "Short-Term Rental",
    "Extended Stay",
    "Pet-Friendly",
    "Family Suites",
    "Historic Property",
    "Cultural Experience Stay",
    "Accessible Accommodations",
  ],

  // ─── EVENTS & CELEBRATIONS ─────────────────────────────────────────────────
  "Event Planning": [
    "Wedding Planning",
    "Day-Of Coordination",
    "Full-Service Planning",
    "Birthday Celebrations",
    "Quinceañeras & Debutante Balls",
    "Baby Showers",
    "Graduation Celebrations",
    "Sweet 16 Parties",
    "Milestone Anniversaries",
    "Corporate Events",
    "Community Fundraisers",
    "Virtual Events",
    "Venue Sourcing",
  ],
  "Florists & Décor": [
    "Wedding Florals",
    "Event Décor & Styling",
    "Custom Bouquets",
    "Centerpiece Design",
    "Arch & Backdrop Design",
    "Balloon Installations",
    "African & Tropical Flowers",
    "Sympathy & Memorial Arrangements",
    "Corporate Décor",
    "Holiday Décor",
    "Rental Inventory",
    "Full Setup & Breakdown",
  ],

  // ─── MEDIA & CREATIVE SERVICES ─────────────────────────────────────────────
  "Photography & Videography": [
    "Portrait Photography",
    "Family Photography",
    "Newborn & Maternity Photography",
    "Wedding Photography",
    "Event Photography",
    "Business Headshots",
    "Product Photography",
    "Real Estate Photography",
    "Music Video Production",
    "Documentary Filmmaking",
    "Social Media Content Creation",
    "Brand Photography",
    "Commercial Photography",
    "Drone Photography & Videography",
  ],
  "Graphic Design & Branding": [
    "Logo Design",
    "Brand Identity Systems",
    "Business Cards & Stationery",
    "Social Media Graphics",
    "Marketing Materials",
    "Menu Design",
    "Book & Album Cover Art",
    "Murals & Wall Art",
    "Signage & Wayfinding",
    "Packaging Design",
    "Motion Graphics",
    "Illustration",
    "Custom Merchandise Design",
  ],
  "Music & Audio Production": [
    "Beat Production",
    "Full Song Production",
    "Mixing & Mastering",
    "Recording Studio Sessions",
    "Podcast Production",
    "Voiceover Services",
    "Jingle & Commercial Audio",
    "Film Score & Soundtracks",
    "Live Sound Engineering",
    "Music Lessons",
    "DJ Services",
    "Audio Restoration",
  ],

  // ─── RETAIL ────────────────────────────────────────────────────────────────
  "Retail & Boutiques": [
    "African Print & Ankara Fashion",
    "Urban Streetwear",
    "Athleisure",
    "Plus Size Fashion",
    "Custom Tailoring & Alterations",
    "Vintage & Resale",
    "Children's Clothing",
    "Business & Professional Attire",
    "African Jewelry & Accessories",
    "Natural Hair Accessories",
    "Shoes & Sneakers",
    "Home & Lifestyle Goods",
    "Afrocentric Gifts & Novelties",
    "Books & Media",
  ],
  "Bookstores & Libraries": [
    "Black Literature",
    "African Diaspora History",
    "Children's Books by Black Authors",
    "Self-Help & Empowerment",
    "Spiritual & Religious Texts",
    "Business & Finance",
    "Fiction & Poetry",
    "Rare & Collectible Books",
    "Community Events & Author Talks",
    "Used & Rare Books",
    "Educational Resources",
  ],

  // ─── ARTS & CULTURE ────────────────────────────────────────────────────────
  "Visual Arts & Galleries": [
    "African Diaspora Art",
    "Contemporary Black Art",
    "Photography Exhibitions",
    "Mixed Media",
    "Sculpture",
    "Printmaking",
    "Community Art Programs",
    "Youth Arts Education",
    "Art Classes & Workshops",
    "Commissioned Work",
    "Pop-Up Exhibitions",
    "Artist Residencies",
  ],
  "Performing Arts": [
    "Live Jazz",
    "R&B & Soul",
    "Hip-Hop Performances",
    "Gospel Music",
    "African Drum & Dance",
    "Spoken Word & Poetry",
    "Stand-Up Comedy",
    "Theater & Stage Productions",
    "Dance Performances",
    "Open Mic Nights",
    "Cultural Festivals",
    "Youth Performing Arts",
  ],

  // ─── EDUCATION & LEARNING ──────────────────────────────────────────────────
  "Tutoring & Academic Support": [
    "K-12 Tutoring",
    "SAT / ACT Prep",
    "College Admissions Counseling",
    "STEM Tutoring",
    "Reading & Literacy",
    "Writing & Essay Coaching",
    "HBCU Guidance & Applications",
    "Financial Aid Navigation",
    "Adult Education",
    "ESL / English Language Learning",
    "Online Tutoring",
  ],
  "Professional Development": [
    "Resume Writing",
    "Interview Coaching",
    "Career Coaching",
    "LinkedIn Profile Optimization",
    "Public Speaking",
    "Leadership Development",
    "Entrepreneurship Training",
    "Certifications & Licensing Prep",
    "Networking Events",
    "Mentorship Programs",
  ],

  // ─── HOME & PROPERTY ───────────────────────────────────────────────────────
  "Home Services": [
    "General Contracting",
    "Painting (Interior & Exterior)",
    "Flooring Installation",
    "Plumbing",
    "Electrical",
    "HVAC",
    "Landscaping & Lawn Care",
    "Pressure Washing",
    "Roofing",
    "Fence Installation",
    "Deck & Patio Construction",
    "Kitchen & Bath Remodeling",
    "Handyman Services",
  ],
  "Cleaning Services": [
    "Residential Cleaning",
    "Commercial Cleaning",
    "Deep Cleaning",
    "Move-In / Move-Out Cleaning",
    "Post-Construction Cleaning",
    "Airbnb & Short-Term Rental Cleaning",
    "Recurring Maintenance Cleaning",
    "Eco-Friendly Cleaning Products",
    "Organizational Services",
  ],
  "Moving & Relocation": [
    "Local Moving",
    "Long-Distance Moving",
    "Apartment Moving",
    "Commercial Moving",
    "Senior Relocation",
    "Packing & Unpacking Services",
    "Furniture Assembly",
    "Piano & Specialty Item Moving",
    "Storage Solutions",
  ],
  "Real Estate": [
    "Buyer Representation",
    "Seller Representation",
    "First-Time Homebuyers",
    "Investment Properties",
    "Rental Property Management",
    "Commercial Real Estate",
    "Luxury Properties",
    "Community Land Trust",
    "Affordable Housing Programs",
    "Relocation Specialist",
  ],
};

/** Flat deduplicated list of all approved specialty terms across all subcategories */
export const ALL_SPECIALTIES: string[] = [
  ...new Set(Object.values(SPECIALTIES_BY_SUBCATEGORY).flat()),
];

/** Returns the approved specialties list for a given subcategory name */
export function getSpecialtiesForSubcategory(subcategory: string): string[] {
  return SPECIALTIES_BY_SUBCATEGORY[subcategory] ?? [];
}

/** Returns true if a given specialty is approved for a subcategory */
export function isApprovedSpecialty(subcategory: string, specialty: string): boolean {
  return getSpecialtiesForSubcategory(subcategory).includes(specialty);
}
