/**
 * THE REAL — Professional Trust Signal Layer
 *
 * Mapping With Melanin™ permanent source-of-truth.
 * THE REAL applies to professional/service categories where community
 * members report on being believed, advocated for, treated with dignity,
 * and receiving culturally competent service. These are NOT atmosphere
 * signals (The Vibe) — they are professional trust signals.
 *
 * 151 tags across 9 categories.
 * Source: Mapping_With_Melanin_MASTER_Business_Directory_v2_THE_REAL.xlsx
 * "THE REAL Reference" sheet — NEVER MODIFY without founder approval.
 */

export type TheRealTagType = "real-specific" | "real-adaptive";

export interface TheRealTag {
  tag_key: string;
  label: string;
  category: string;
  type: TheRealTagType;
  /** null for real-specific tags */
  adaptive_family: string | null;
  /** semicolon-separated subcategory scope, or "all" */
  subcategory_scope: string;
  helper_text: string;
}

/**
 * THE REAL tag definitions — all 151 tags.
 * Display threshold: 5 community taps (lower than endorsement tags because
 * professional trust signals are harder to earn and carry more weight).
 */
export const THE_REAL_DISPLAY_THRESHOLD = 5;

export const THE_REAL_TAGS: TheRealTag[] = [
  // ── Health & Wellness ────────────────────────────────────────────────────
  {
    tag_key: "this_doctor_listens",
    label: "This Doctor Listens",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, PT, chiropractic, holistic",
    helper_text: "They asked, then waited for the whole answer",
  },
  {
    tag_key: "believed_my_pain",
    label: "Believed My Pain",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, PT, chiropractic, doula",
    helper_text: "No minimizing, no doubting, no \"are you sure?\"",
  },
  {
    tag_key: "believed_me",
    label: "Believed Me",
    category: "Health & Wellness",
    type: "real-adaptive",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "They took your account of your own body as true",
  },
  {
    tag_key: "culturally_competent_care",
    label: "Culturally Competent Care",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "They understand where you come from",
  },
  {
    tag_key: "understands_my_skin",
    label: "Understands My Skin",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care (dermatology) , wellness centers",
    helper_text: "Trained on melanated skin, not just textbook photos",
  },
  {
    tag_key: "understands_my_hair",
    label: "Understands My Hair",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care (dermatology) , wellness centers",
    helper_text: "Knows textured hair and scalp conditions",
  },
  {
    tag_key: "fought_for_my_coverage",
    label: "Fought For My Coverage",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "They pushed insurance so you didn't have to",
  },
  {
    tag_key: "knew_my_condition_hits_us_different",
    label: "Knew My Condition Hits Us Different",
    category: "Health & Wellness",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "primary care, dental, PT, chiropractic, holistic, doula",
    helper_text: "They knew the numbers for our community without being told",
  },
  {
    tag_key: "didn_t_dismiss_my_symptoms",
    label: "Didn't Dismiss My Symptoms",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "What you reported was investigated, not filed away",
  },
  {
    tag_key: "explained_options_not_just_orders",
    label: "Explained Options, Not Just Orders",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "You chose your care, you weren't handed a decision",
  },
  {
    tag_key: "waited_for_my_questions",
    label: "Waited For My Questions",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Nobody had a hand on the doorknob",
  },
  {
    tag_key: "remembered_my_history",
    label: "Remembered My History",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, mental wellness, PT, chiropractic, home health",
    helper_text: "You didn't have to start over every visit",
  },
  {
    tag_key: "respected_my_birth_plan",
    label: "Respected My Birth Plan",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "doula & birth services, primary care",
    helper_text: "What you wrote down was honored in the room",
  },
  {
    tag_key: "advocated_when_i_couldn_t",
    label: "Advocated When I Couldn't",
    category: "Health & Wellness",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "doula & birth services, primary care, home health, mental wellness",
    helper_text: "They spoke up for you when you had no voice left",
  },
  {
    tag_key: "doula_held_me_down",
    label: "Doula Held Me Down",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "doula & birth services",
    helper_text: "Advocated for you when it counted most",
  },
  {
    tag_key: "therapist_gets_the_culture",
    label: "Therapist Gets The Culture",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "mental wellness & therapy",
    helper_text: "No spending session one explaining your whole life",
  },
  {
    tag_key: "gentle_with_my_child",
    label: "Gentle With My Child",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, PT, home health",
    helper_text: "Your baby wasn't frightened or handled roughly",
  },
  {
    tag_key: "explained_every_option",
    label: "Explained Every Option",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Maternal-Fetal Medicine; Fertility & Reproductive Health",
    helper_text: "I understood the choices, risks, benefits, and what happened next",
  },
  {
    tag_key: "didn_t_blame_everything_on_my_weight",
    label: "Didn't Blame Everything On My Weight",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Primary Care & Medical Practices; Specialist Physicians",
    helper_text: "My symptoms were investigated instead of being reduced to my size",
  },
  {
    tag_key: "took_my_reproductive_choices_seriously",
    label: "Took My Reproductive Choices Seriously",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Fertility & Reproductive Health",
    helper_text: "My goals and decisions were treated as mine to make",
  },
  {
    tag_key: "didn_t_assume_i_wanted_children",
    label: "Didn't Assume I Wanted Children",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Fertility & Reproductive Health",
    helper_text: "They asked what I wanted instead of deciding for me",
  },
  {
    tag_key: "took_my_child_s_symptoms_seriously",
    label: "Took My Child's Symptoms Seriously",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Pediatrics; Primary Care & Medical Practices; Urgent Care",
    helper_text: "They listened to the parent and investigated what was happening",
  },
  {
    tag_key: "understood_melanated_skin",
    label: "Understood Melanated Skin",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Dermatology; Specialist Physicians",
    helper_text: "Diagnosis considered how symptoms present on darker skin",
  },

  // ── Legal & Government Services ────────────────────────────────────────────────────
  {
    tag_key: "staff_looked_like_me",
    label: "Staff Looked Like Me",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Representatio n from the front desk back",
  },
  {
    tag_key: "no_surprise_bills",
    label: "No Surprise Bills",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "The bill matched what you were told",
  },
  {
    tag_key: "fought_for_me",
    label: "Fought For Me",
    category: "Legal & Government Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "attorneys, mediation, immigration, public services",
    helper_text: "Genuine advocacy, not a filing service",
  },
  {
    tag_key: "explained_my_rights",
    label: "Explained My Rights",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You learned what you were actually entitled to",
  },
  {
    tag_key: "didn_t_take_my_money_and_ghost",
    label: "Didn't Take My Money And Ghost",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, legal document services",
    helper_text: "Communicati on stayed consistent after the retainer cleared",
  },
  {
    tag_key: "handled_my_immigration_case_with_care",
    label: "Handled My Immigration Case With Care",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "immigration services, attorneys",
    helper_text: "Trust with the highest stakes there are",
  },
  {
    tag_key: "kept_my_family_together",
    label: "Kept My Family Together",
    category: "Legal & Government Services",
    type: "real-adaptive",
    adaptive_family: "protected_my_privacy",
    subcategory_scope: "attorneys, immigration, mediation",
    helper_text: "The outcome that mattered more than anything",
  },
  {
    tag_key: "treated_me_with_dignity",
    label: "Treated Me With Dignity",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "government offices, public services, all",
    helper_text: "No dismissivenes s at the counter",
  },
  {
    tag_key: "showed_up_to_court_prepared",
    label: "Showed Up To Court Prepared",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, mediation, immigration",
    helper_text: "They knew your file cold when it counted",
  },
  {
    tag_key: "didn_t_make_me_feel_criminal",
    label: "Didn't Make Me Feel Criminal",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, government offices, public services",
    helper_text: "You were a client, not a suspect",
  },
  {
    tag_key: "understood_the_system_works_against_us",
    label: "Understood The System Works Against Us",
    category: "Legal & Government Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "all",
    helper_text: "They named it out loud and planned around it",
  },
  {
    tag_key: "called_me_back_same_day",
    label: "Called Me Back Same Day",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, mediation, legal document services",
    helper_text: "You were never left waiting in the dark",
  },
  {
    tag_key: "pro_bono_when_i_needed_it",
    label: "Pro Bono When I Needed It",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, mediation, immigration, legal",
    helper_text: "They worked when you couldn't pay",
  },
  {
    tag_key: "explained_every_step_before_we_took_it",
    label: "Explained Every Step Before We Took It",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Attorneys & Law Firms; Immigration Attorneys; Family Law; Criminal Defense; Housing & Tenant Law",
    helper_text: "I knew what was happening, why, and what came next",
  },
  {
    tag_key: "didn_t_promise_me_a_guaranteed_outcome",
    label: "Didn't Promise Me A Guaranteed Outcome",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Attorneys & Law Firms; Immigration Attorneys; Family Law; Criminal Defense; Personal Injury",
    helper_text: "They were hopeful without selling me certainty",
  },
  {
    tag_key: "understood_my_immigration_status_without_judgment",
    label: "Understood My Immigration Status Without Judgment",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Immigration Attorneys; Immigration Services",
    helper_text: "I could tell the whole story without being shamed or treated as suspicious",
  },
  {
    tag_key: "protected_my_privacy",
    label: "Protected My Privacy",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Immigration Attorneys; Immigration Services; Attorneys & Law Firms",
    helper_text: "Sensitive information was handled carefully",
  },
  {
    tag_key: "made_sure_i_understood_before_i_signed",
    label: "Made Sure I Understood Before I Signed",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Attorneys & Law Firms; Immigration Attorneys; Legal Document Services; Notary Services",
    helper_text: "Nothing was rushed past me because the paperwork was complicated",
  },

  // ── Financial & Business Services ────────────────────────────────────────────────────
  {
    tag_key: "knew_the_judge_and_the_room",
    label: "Knew The Judge And The Room",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, mediation",
    helper_text: "Local knowledge that changed the outcome",
  },
  {
    tag_key: "paperwork_was_done_right",
    label: "Paperwork Was Done Right",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "immigration, legal document services, notary, attorneys",
    helper_text: "Nothing bounced back, nothing was refiled",
  },
  {
    tag_key: "didn_t_rush_my_case",
    label: "Didn't Rush My Case",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, mediation",
    helper_text: "They took the time your case actually needed",
  },
  {
    tag_key: "translated_everything",
    label: "Translated Everything",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Every document, every hearing, in your language",
  },
  {
    tag_key: "made_me_feel_like_i_mattered",
    label: "Made Me Feel Like I Mattered",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You were a person, not a case number in a stack",
  },
  {
    tag_key: "no_predatory_fees",
    label: "No Predatory Fees",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "attorneys, immigration, legal document services, notary",
    helper_text: "The fee structure was honest from the first meeting",
  },
  {
    tag_key: "said_yes_when_others_said_no",
    label: "Said Yes When Others Said No",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "lending, mortgage, credit services, business funding",
    helper_text: "They looked past the algorithm at the actual person",
  },
  {
    tag_key: "no_predatory_terms",
    label: "No Predatory Terms",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "lending, credit services, business funding, mortgage",
    helper_text: "Fair rates, no traps buried on page nine",
  },
  {
    tag_key: "got_me_funded",
    label: "Got Me Funded",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "business funding, lending, mortgage",
    helper_text: "The capital actually came through",
  },
  {
    tag_key: "taught_me_to_build_wealth",
    label: "Taught Me To Build Wealth",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "financial advisors, investment services, banks & credit unions",
    helper_text: "Education, not just transactions",
  },
  {
    tag_key: "explained_my_credit_plain",
    label: "Explained My Credit Plain",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "credit services, lending, mortgage,",
    helper_text: "You finally understood your own report",
  },
  {
    tag_key: "didn_t_judge_my_starting_point",
    label: "Didn't Judge My Starting Point",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Wherever you started, that's where they met you",
  },
  {
    tag_key: "showed_me_the_path",
    label: "Showed Me The Path",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You left with a plan, not just a product",
  },
  {
    tag_key: "celebrated_my_first_investment",
    label: "Celebrated My First Investment",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "financial advisors, investment services, banks & credit unions",
    helper_text: "Small beginnings treated like they mattered",
  },
  {
    tag_key: "understood_generational_wealth_gaps",
    label: "Understood Generational Wealth Gaps",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "all",
    helper_text: "They knew you were building without inheritance",
  },
  {
    tag_key: "no_minimum_to_be_respected",
    label: "No Minimum To Be Respected",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Your balance didn't determine your treatment",
  },
  {
    tag_key: "helped_my_family_not_just_me",
    label: "Helped My Family, Not Just Me",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "protected_my_privacy",
    subcategory_scope: "financial advisors, tax preparation, investment services, banks",
    helper_text: "They planned for everybody you carry",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Real information, delivered with respect",
  },
  {
    tag_key: "didn_t_push_products_i_didn_t_need",
    label: "Didn't Push Products I Didn't Need",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "financial advisors, investment services, banks, credit services",
    helper_text: "No commission- driven recommendat ions",
  },
  {
    tag_key: "showed_me_the_total_cost_not_just_the_monthly_payment",
    label: "Showed Me The Total Cost, Not Just The Monthly Payment",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Lending & Financing; Mortgage Services; Banks & Credit Unions; Business Funding",
    helper_text: "I could see the full price of the money before agreeing",
  },
  {
    tag_key: "didn_t_treat_cash_income_like_it_wasn_t_real",
    label: "Didn't Treat Cash Income Like It Wasn't Real",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Mortgage Services; Lending & Financing; Banks & Credit Unions",
    helper_text: "They explained what documentation could support my application",
  },

  // ── Professional Services ────────────────────────────────────────────────────
  {
    tag_key: "fought_the_denial",
    label: "Fought The Denial",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "lending, mortgage, credit services, business funding",
    helper_text: "They appealed it instead of accepting it",
  },
  {
    tag_key: "believed_my_numbers",
    label: "Believed My Numbers",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "business funding, lending, bookkeeping, tax preparation",
    helper_text: "Your books were trusted, not interrogated",
  },
  {
    tag_key: "fought_for_me",
    label: "Fought For Me",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "legal, insurance, staffing, accounting & tax",
    helper_text: "Went to bat on your behalf",
  },
  {
    tag_key: "took_my_small_business_seriously",
    label: "Took My Small Business Seriously",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "No revenue minimum to be respected",
  },
  {
    tag_key: "taught_me_while_they_worked",
    label: "Taught Me While They Worked",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "consulting, marketing, design, web & app, IT",
    helper_text: "You learned, you weren't just billed",
  },
  {
    tag_key: "didn_t_talk_down_to_me",
    label: "Didn't Talk Down To Me",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Respect regardless of what you knew coming in",
  },
  {
    tag_key: "made_my_business_feel_big",
    label: "Made My Business Feel Big",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You got the treatment a major client gets",
  },
  {
    tag_key: "understood_my_community",
    label: "Understood My Community",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "marketing, PR, design, consulting, staffing, translation",
    helper_text: "They knew who you serve without a lecture",
  },
  {
    tag_key: "didn_t_nickel_and_dime_me",
    label: "Didn't Nickel And Dime Me",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Every question didn't turn into a line item",
  },
  {
    tag_key: "available_when_i_panicked",
    label: "Available When I Panicked",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "accounting & tax, legal, insurance, IT, consulting, VA",
    helper_text: "The emergency call got answered",
  },
  {
    tag_key: "grew_with_me",
    label: "Grew With Me",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Still your person three years in",
  },
  {
    tag_key: "referred_me_to_their_people",
    label: "Referred Me To Their People",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "They opened their network to you",
  },
  {
    tag_key: "kept_my_books_clean",
    label: "Kept My Books Clean",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "accounting & tax, financial services, bookkeeping- adjacent",
    helper_text: "Audit-ready, no scrambling in April",
  },
  {
    tag_key: "tax_refund_was_right",
    label: "Tax Refund Was Right",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "accounting & tax",
    helper_text: "Correct the first time, no amended return",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Substance, delivered with respect",
  },
  {
    tag_key: "contract_had_no_traps",
    label: "Contract Had No Traps",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "all",
    helper_text: "You could sign it without a second lawyer",
  },
  {
    tag_key: "explained_everything_clearly",
    label: "Explained Everything Clearly",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "I understood what they were doing, what they needed from me, and what came next",
  },
  {
    tag_key: "didn_t_make_me_prove_i_belonged_in_the_room",
    label: "Didn't Make Me Prove I Belonged In The Room",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Business Consulting; Marketing & Advertising; Public Relations; Staffing & Recruiting; Executive Coaching",
    helper_text: "My experience and ambition were taken seriously from the start",
  },

  // ── Technology & Digital Services ────────────────────────────────────────────────────
  {
    tag_key: "believed_my_vision",
    label: "Believed My Vision",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "consulting, marketing, PR, design, web & app",
    helper_text: "They took your idea seriously from day one",
  },
  {
    tag_key: "explained_it_without_the_jargon",
    label: "Explained It Without The Jargon",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Plain language from start to finish",
  },
  {
    tag_key: "handed_over_the_passwords",
    label: "Handed Over The Passwords",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, IT support, SaaS",
    helper_text: "You own your domain, hosting, and accounts",
  },
  {
    tag_key: "built_for_our_community",
    label: "Built For Our Community",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Designed with us in mind, not retrofitted",
  },
  {
    tag_key: "didn_t_talk_down_to_me",
    label: "Didn't Talk Down To Me",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Respect regardless of your tech level",
  },
  {
    tag_key: "didn_t_make_me_feel_dumb",
    label: "Didn't Make Me Feel Dumb",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "No sighing, no eye- rolling, no \"obviously\"",
  },
  {
    tag_key: "actually_tested_it",
    label: "Actually Tested It",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, software,",
    helper_text: "It worked on delivery, not",
  },
  {
    tag_key: "answered_at_11pm",
    label: "Answered At 11pm",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "IT support, cybersecurity, web dev, app dev, SaaS",
    helper_text: "The site went down and somebody picked up",
  },
  {
    tag_key: "taught_my_team_to_fish",
    label: "Taught My Team To Fish",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "consulting, IT support, SaaS, AI & automation, web dev",
    helper_text: "You aren't dependent on them forever",
  },
  {
    tag_key: "didn_t_hold_my_site_hostage",
    label: "Didn't Hold My Site Hostage",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, IT support, SaaS",
    helper_text: "Full access, no ransom, clean handoff",
  },
  {
    tag_key: "understood_my_audience",
    label: "Understood My Audience",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "web dev, app dev, digital products, consulting",
    helper_text: "They built for the people you actually serve",
  },
  {
    tag_key: "made_it_accessible",
    label: "Made It Accessible",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, digital products, SaaS",
    helper_text: "Screen readers, contrast, older phones, slow data",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Technical truth, no condescensio n",
  },
  {
    tag_key: "contract_had_no_traps",
    label: "Contract Had No Traps",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "all",
    helper_text: "No auto- renew ambush, no ownership grab",
  },
  {
    tag_key: "believed_my_bug_report",
    label: "Believed My Bug Report",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "software, SaaS, app dev, web dev, IT support",
    helper_text: "\"It's not doing that\" was never the answer",
  },

  // ── Home & Property Services ────────────────────────────────────────────────────
  {
    tag_key: "fixed_it_right_the_first_time",
    label: "Fixed It Right The First Time",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, roofing, handyman, pest control",
    helper_text: "No second call, no callback fee",
  },
  {
    tag_key: "respected_my_home",
    label: "Respected My Home",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Shoes off, drop cloths, care taken",
  },
  {
    tag_key: "honest_about_what_i_didn_t_need",
    label: "Honest About What I Didn't Need",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, roofing, inspection, pest control",
    helper_text: "They talked you out of spending money",
  },
  {
    tag_key: "didn_t_talk_down_to_me",
    label: "Didn't Talk Down To Me",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Explained without condescensio n",
  },
  {
    tag_key: "didn_t_overcharge_for_my_zip_code",
    label: "Didn't Overcharge For My Zip Code",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Same price they'd quote across town",
  },
  {
    tag_key: "showed_up_in_my_neighborhood",
    label: "Showed Up In My Neighborhood",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Community- reported: no excuses",
  },
  {
    tag_key: "treated_my_apartment_like_a_house",
    label: "Treated My Apartment Like A House",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, cleaning, handyman, pest control, property management",
    helper_text: "Renters got the same care as owners",
  },
  {
    tag_key: "didn_t_scare_me_into_more_work",
    label: "Didn't Scare Me Into More Work",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, roofing, inspection, pest control",
    helper_text: "No manufactured emergencies",
  },
  {
    tag_key: "left_my_floors_clean",
    label: "Left My Floors Clean",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You didn't clean up behind them",
  },
  {
    tag_key: "good_with_my_grandmother",
    label: "Good With My Grandmother",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Safe and patient in an elder's home, alone",
  },
  {
    tag_key: "quote_had_no_traps",
    label: "Quote Had No Traps",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "contractors, construction, roofing, HVAC, moving, property management",
    helper_text: "The final number matched the signed number",
  },
  {
    tag_key: "knows_what_we_face_with_housing",
    label: "Knows What We Face With Housing",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "real estate agents & brokers, property management, home inspection",
    helper_text: "They understood appraisal gaps and steering",
  },
  {
    tag_key: "believed_me_about_the_problem",
    label: "Believed Me About The Problem",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "plumbing, electricians, HVAC, property",
    helper_text: "They came out and looked",
  },
  {
    tag_key: "didn_t_steer_me_away_from_a_neighborhood",
    label: "Didn't Steer Me Away From A Neighborhood",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Real Estate Agents & Brokers; Housing Counselors",
    helper_text: "They gave information without deciding where someone like me should live",
  },
  {
    tag_key: "explained_first_time_buyer_programs",
    label: "Explained First-Time Buyer Programs",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Real Estate Agents & Brokers; Housing Counselors; Mortgage & Homebuyer Counseling",
    helper_text: "They showed me assistance and programs I might qualify for",
  },

  // ── Automotive & Transportation ────────────────────────────────────────────────────
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Showed you the work and the why",
  },
  {
    tag_key: "didn_t_upsell_me",
    label: "Didn't Upsell Me",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision",
    helper_text: "Only what the car actually needed",
  },
  {
    tag_key: "showed_me_the_old_part",
    label: "Showed Me The Old Part",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, body & collision",
    helper_text: "Proof the work was really done",
  },
  {
    tag_key: "safe_for_women_coming_alone",
    label: "Safe For Women Coming Alone",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Community- reported: respectful, no pressure, no creeping",
  },
  {
    tag_key: "didn_t",
    label: "Didn't",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision",
    helper_text: "They talked to you like you'd been under a hood",
  },
  {
    tag_key: "gave_me_the_real_price_first",
    label: "Gave Me The Real Price First",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "The first number was the honest number",
  },
  {
    tag_key: "didn_t_talk_past_me_to_my_husband",
    label: "Didn't Talk Past Me To My Husband",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision, towing",
    helper_text: "They addressed you, the actual customer",
  },
  {
    tag_key: "remembered_my_car_s_history",
    label: "Remembered My Car's History",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, body & collision, detailing",
    helper_text: "They knew the vehicle before you explained it",
  },
  {
    tag_key: "honest_about_what_could_wait",
    label: "Honest About What Could Wait",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision",
    helper_text: "They told you what could hold until next month",
  },
  {
    tag_key: "financing_had_no_traps",
    label: "Financing Had No Traps",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "auto dealers, transportation companies",
    helper_text: "No rate markup, no packed payments",
  },
  {
    tag_key: "believed_me_about_the_sound",
    label: "Believed Me About The Sound",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "auto repair, tire, body & collision",
    helper_text: "They drove it and listened instead of dismissing you",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "auto repair, tire, dealers, body & collision, towing",
    helper_text: "Showed you the diagnostic and walked it through",
  },
  {
    tag_key: "fought_my_insurance_for_me",
    label: "Fought My Insurance For Me",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "auto body & collision, auto repair, towing",
    helper_text: "They handled the adjuster so you didn't have to",
  },
  {
    tag_key: "didn_t_leave_me_stranded",
    label: "Didn't Leave Me Stranded",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "towing & roadside, auto repair, car rental, transportation companies",
    helper_text: "They got you home before they got paid",
  },

  // ── Pets & Animal Services ────────────────────────────────────────────────────
  {
    tag_key: "knows_what_we_face_on_the_road",
    label: "Knows What We Face On The Road",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "chauffeur & private driver, transportation companies, towing & roadside",
    helper_text: "Community- reported understandin g of roadside risk for us",
  },
  {
    tag_key: "my_dog_wasn_t_scared",
    label: "My Dog Wasn't Scared",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "vets, grooming, boarding, daycare, training",
    helper_text: "Calm afterward, not traumatized",
  },
  {
    tag_key: "honest_about_treatment_cost",
    label: "Honest About Treatment Cost",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, training",
    helper_text: "No fear-based upselling on a sick animal",
  },
  {
    tag_key: "no_breed_judgment",
    label: "No Breed Judgment",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Pit bulls and big dogs treated fairly",
  },
  {
    tag_key: "didn_t_judge_what_i_could_afford",
    label: "Didn't Judge What I Could Afford",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, grooming, training, boarding",
    helper_text: "They found a way within your budget",
  },
  {
    tag_key: "gave_me_real_options",
    label: "Gave Me Real Options",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, training",
    helper_text: "Every path explained, including the affordable one",
  },
  {
    tag_key: "didn_t_assume_i_neglected_them",
    label: "Didn't Assume I Neglected Them",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, grooming, training",
    helper_text: "No lecture, no accusation, just care",
  },
  {
    tag_key: "stayed_after_hours_for_us",
    label: "Stayed After Hours For Us",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, boarding, pet sitting",
    helper_text: "The door didn't close on an emergency",
  },
  {
    tag_key: "handled_our_loss_with_grace",
    label: "Handled Our Loss With Grace",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians",
    helper_text: "Dignity when you had to say goodbye",
  },
  {
    tag_key: "payment_plan_was_real",
    label: "Payment Plan Was Real",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "veterinarians, training, boarding",
    helper_text: "No interest trap on a sick animal",
  },
  {
    tag_key: "believed_something_was_wrong",
    label: "Believed Something Was Wrong",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "veterinarians, training",
    helper_text: "You know your animal, and they trusted that",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "veterinarians, training, grooming",
    helper_text: "Real medical information, respectfully given",
  },
  {
    tag_key: "fought_for_my_animal",
    label: "Fought For My Animal",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "veterinarians",
    helper_text: "They exhausted every option before giving up",
  },
  {
    tag_key: "good_with_my_kids_watching",
    label: "Good With My Kids Watching",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, grooming, training, pet stores",
    helper_text: "Patient with children in the room",
  },

  // ── Other Services ────────────────────────────────────────────────────
  {
    tag_key: "handled_our_loss_with_grace",
    label: "Handled Our Loss With Grace",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services",
    helper_text: "Dignity for your family in grief",
  },
  {
    tag_key: "honored_our_traditions",
    label: "Honored Our Traditions",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services",
    helper_text: "The homegoing was done our way",
  },
  {
    tag_key: "didn_t_upsell_us_in_grief",
    label: "Didn't Upsell Us In Grief",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services",
    helper_text: "No pressure at the worst moment of your life",
  },
  {
    tag_key: "gave_us_the_price_list_up_front",
    label: "Gave Us The Price List Up Front",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "funeral & memorial services, storage, shipping & mailing, personal concierge",
    helper_text: "Every cost in writing before any decision",
  },
  {
    tag_key: "worked_with_what_we_had",
    label: "Worked With What We Had",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services, tailoring, shoe repair, storage, laundry",
    helper_text: "They made it beautiful within your means",
  },
  {
    tag_key: "didn_t_judge_what_i_brought_in",
    label: "Didn't Judge What I Brought In",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "laundry & dry cleaning, tailoring & alterations, shoe repair",
    helper_text: "Old and worn was treated like new and expensive",
  },
  {
    tag_key: "came_when_i_was_stuck",
    label: "Came When I Was Stuck",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "locksmiths, personal concierge, storage",
    helper_text: "Late, alone, locked out, and they showed up",
  },
  {
    tag_key: "didn_t_gouge_me_in_an_emergency",
    label: "Didn't Gouge Me In An Emergency",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "locksmiths, personal concierge, shipping & mailing",
    helper_text: "The 2am price was a fair price",
  },
  {
    tag_key: "believed_me_about_the_damage",
    label: "Believed Me About The Damage",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "laundry & dry cleaning, shipping & mailing, storage, tailoring",
    helper_text: "They made it right without a fight",
  },
  {
    tag_key: "protected_my_family",
    label: "Protected My Family",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "protected_my_privacy",
    subcategory_scope: "funeral & memorial services, personal concierge, locksmiths",
    helper_text: "They carried your family through it",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Straight answers, no runaround",
  },
  {
    tag_key: "knows_what_our_traditions_require",
    label: "Knows What Our Traditions Require",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "funeral & memorial services, tailoring & alterations, personal concierge",
    helper_text: "No explaining your customs from scratch",
  },
  {
    tag_key: "fought_for_my_claim",
    label: "Fought For My Claim",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "shipping & mailing, storage, laundry & dry cleaning",
    helper_text: "They pursued the carrier or insurer on your behalf",
  },

];

/** Category → THE REAL tags lookup */
export const THE_REAL_CATEGORY_MAP: Record<string, TheRealTag[]> = {
  "Health & Wellness": THE_REAL_TAGS.filter(t => t.category === "Health & Wellness"),
  "Legal & Government Services": THE_REAL_TAGS.filter(t => t.category === "Legal & Government Services"),
  "Financial & Business Services": THE_REAL_TAGS.filter(t => t.category === "Financial & Business Services"),
  "Professional Services": THE_REAL_TAGS.filter(t => t.category === "Professional Services"),
  "Technology & Digital Services": THE_REAL_TAGS.filter(t => t.category === "Technology & Digital Services"),
  "Home & Property Services": THE_REAL_TAGS.filter(t => t.category === "Home & Property Services"),
  "Automotive & Transportation": THE_REAL_TAGS.filter(t => t.category === "Automotive & Transportation"),
  "Pets & Animal Services": THE_REAL_TAGS.filter(t => t.category === "Pets & Animal Services"),
  "Other Services": THE_REAL_TAGS.filter(t => t.category === "Other Services"),
};

/**
 * Categories that display THE REAL professional trust layer.
 * All other categories use The Vibe (atmosphere) layer.
 * Source: "Layer Routing" sheet.
 *
 * Special case: Health & Wellness fitness subcategories
 * (Fitness & Gyms, Personal Trainers, Yoga & Pilates) use The Vibe.
 */
export const THE_REAL_CATEGORIES: string[] = [
  "Health & Wellness",
  "Legal & Government Services",
  "Financial & Business Services",
  "Professional Services",
  "Technology & Digital Services",
  "Home & Property Services",
  "Automotive & Transportation",
  "Pets & Animal Services",
  "Other Services",
];

/**
 * Health & Wellness subcategories that use The VIBE (not THE REAL).
 * Movement/wellness experience exception per Layer Routing sheet.
 */
export const HEALTH_VIBE_SUBCATEGORIES: string[] = [
  "Fitness & Gyms",
  "Personal Trainers",
  "Yoga & Pilates",
];

/** Returns true if a business's category uses THE REAL layer */
export function usesTheReal(category: string, subcategory?: string): boolean {
  if (!THE_REAL_CATEGORIES.includes(category)) return false;
  if (category === "Health & Wellness" && subcategory &&
      HEALTH_VIBE_SUBCATEGORIES.includes(subcategory)) return false;
  return true;
}

/** Returns THE REAL tags for a given category */
export function getTheRealTagsForCategory(category: string): TheRealTag[] {
  return THE_REAL_CATEGORY_MAP[category] ?? [];
}
