/**
 * THE REAL — Professional Trust Signal Layer
 *
 * Mapping With Melanin™ permanent source-of-truth.
 * THE REAL applies to professional/service categories where community
 * members report on being believed, advocated for, treated with dignity,
 * and receiving culturally competent service. These are NOT atmosphere
 * signals (The Vibe) — they are professional trust signals.
 *
 * 151 tags across 9 categories.
 * Source: Mapping_With_Melanin_MASTER_Business_Directory_v2_THE_REAL.xlsx
 * "THE REAL Reference" sheet — NEVER MODIFY without founder approval.
 */

export type TheRealTagType = "real-specific" | "real-adaptive";

export interface TheRealTag {
  tag_key: string;
  label: string;
  category: string;
  type: TheRealTagType;
  /** null for real-specific tags */
  adaptive_family: string | null;
  /** semicolon-separated subcategory scope, or "all" */
  subcategory_scope: string;
  helper_text: string;
}

/**
 * THE REAL tag definitions — all 151 tags.
 * Display threshold: 5 community taps (lower than endorsement tags because
 * professional trust signals are harder to earn and carry more weight).
 */
export const THE_REAL_DISPLAY_THRESHOLD = 5;

export const THE_REAL_TAGS: TheRealTag[] = [
  // ── Health & Wellness ────────────────────────────────────────────────────
  {
    tag_key: "this_doctor_listens",
    label: "This Doctor Listens",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, PT, chiropractic, holistic",
    helper_text: "They asked, then waited for the whole answer",
  },
  {
    tag_key: "believed_my_pain",
    label: "Believed My Pain",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, PT, chiropractic, doula",
    helper_text: "No minimizing, no doubting, no \"are you sure?\"",
  },
  {
    tag_key: "believed_me",
    label: "Believed Me",
    category: "Health & Wellness",
    type: "real-adaptive",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "They took your account of your own body as true",
  },
  {
    tag_key: "culturally_competent_care",
    label: "Culturally Competent Care",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "They understand where you come from",
  },
  {
    tag_key: "understands_my_skin",
    label: "Understands My Skin",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care (dermatology) , wellness centers",
    helper_text: "Trained on melanated skin, not just textbook photos",
  },
  {
    tag_key: "understands_my_hair",
    label: "Understands My Hair",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care (dermatology) , wellness centers",
    helper_text: "Knows textured hair and scalp conditions",
  },
  {
    tag_key: "fought_for_my_coverage",
    label: "Fought For My Coverage",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "They pushed insurance so you didn't have to",
  },
  {
    tag_key: "knew_my_condition_hits_us_different",
    label: "Knew My Condition Hits Us Different",
    category: "Health & Wellness",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "primary care, dental, PT, chiropractic, holistic, doula",
    helper_text: "They knew the numbers for our community without being told",
  },
  {
    tag_key: "didn_t_dismiss_my_symptoms",
    label: "Didn't Dismiss My Symptoms",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "What you reported was investigated, not filed away",
  },
  {
    tag_key: "explained_options_not_just_orders",
    label: "Explained Options, Not Just Orders",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "You chose your care, you weren't handed a decision",
  },
  {
    tag_key: "waited_for_my_questions",
    label: "Waited For My Questions",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Nobody had a hand on the doorknob",
  },
  {
    tag_key: "remembered_my_history",
    label: "Remembered My History",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, mental wellness, PT, chiropractic, home health",
    helper_text: "You didn't have to start over every visit",
  },
  {
    tag_key: "respected_my_birth_plan",
    label: "Respected My Birth Plan",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "doula & birth services, primary care",
    helper_text: "What you wrote down was honored in the room",
  },
  {
    tag_key: "advocated_when_i_couldn_t",
    label: "Advocated When I Couldn't",
    category: "Health & Wellness",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "doula & birth services, primary care, home health, mental wellness",
    helper_text: "They spoke up for you when you had no voice left",
  },
  {
    tag_key: "doula_held_me_down",
    label: "Doula Held Me Down",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "doula & birth services",
    helper_text: "Advocated for you when it counted most",
  },
  {
    tag_key: "therapist_gets_the_culture",
    label: "Therapist Gets The Culture",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "mental wellness & therapy",
    helper_text: "No spending session one explaining your whole life",
  },
  {
    tag_key: "gentle_with_my_child",
    label: "Gentle With My Child",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "primary care, dental, PT, home health",
    helper_text: "Your baby wasn't frightened or handled roughly",
  },
  {
    tag_key: "explained_every_option",
    label: "Explained Every Option",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Maternal-Fetal Medicine; Fertility & Reproductive Health",
    helper_text: "I understood the choices, risks, benefits, and what happened next",
  },
  {
    tag_key: "didn_t_blame_everything_on_my_weight",
    label: "Didn't Blame Everything On My Weight",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Primary Care & Medical Practices; Specialist Physicians",
    helper_text: "My symptoms were investigated instead of being reduced to my size",
  },
  {
    tag_key: "took_my_reproductive_choices_seriously",
    label: "Took My Reproductive Choices Seriously",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Fertility & Reproductive Health",
    helper_text: "My goals and decisions were treated as mine to make",
  },
  {
    tag_key: "didn_t_assume_i_wanted_children",
    label: "Didn't Assume I Wanted Children",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Fertility & Reproductive Health",
    helper_text: "They asked what I wanted instead of deciding for me",
  },
  {
    tag_key: "took_my_child_s_symptoms_seriously",
    label: "Took My Child's Symptoms Seriously",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Pediatrics; Primary Care & Medical Practices; Urgent Care",
    helper_text: "They listened to the parent and investigated what was happening",
  },
  {
    tag_key: "understood_melanated_skin",
    label: "Understood Melanated Skin",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Dermatology; Specialist Physicians",
    helper_text: "Diagnosis considered how symptoms present on darker skin",
  },
  {
    tag_key: "lgbtq_affirming",
    label: "LGBTQIA+ Affirming",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Identity was respected and affirmed — no assumptions, no judgment",
  },
  {
    tag_key: "trauma_informed_care",
    label: "Trauma-Informed Care",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "mental wellness & therapy; primary care; doula & birth services",
    helper_text: "They understood that what happened to you affects how you experience care",
  },
  {
    tag_key: "trans_inclusive_care",
    label: "Trans-Inclusive Care",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Trans and non-binary patients were seen and cared for with full dignity",
  },
  {
    tag_key: "sickle_cell_knowledgeable",
    label: "Sickle Cell Knowledgeable",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Primary Care & Medical Practices; Specialist Physicians; Hematology; Pediatrics",
    helper_text: "They knew the disease — how it presents, how it's managed, what we face",
  },
  {
    tag_key: "hiv_knowledgeable",
    label: "HIV Knowledgeable",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Primary Care & Medical Practices; Infectious Disease; Sexual Health",
    helper_text: "Up to date on treatment, PrEP, and care — no stigma, just facts",
  },
  {
    tag_key: "fibroid_knowledgeable",
    label: "Fibroid Knowledgeable",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Maternal-Fetal Medicine; Specialist Physicians",
    helper_text: "They knew how fibroids affect Black women specifically — and took it seriously",
  },
  {
    tag_key: "endometriosis_knowledgeable",
    label: "Endometriosis Knowledgeable",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "OB-GYN & Women's Health; Specialist Physicians",
    helper_text: "They didn't dismiss the pain — and they knew what they were looking for",
  },
  {
    tag_key: "disability_accessible",
    label: "Disability Accessible",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Physical, communication, and scheduling access for patients with disabilities",
  },
  {
    tag_key: "telehealth_available",
    label: "Telehealth Available",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "You can be seen without having to get there",
  },
  {
    tag_key: "accepting_new_patients",
    label: "Accepting New Patients",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "You can actually get in the door",
  },
  {
    tag_key: "evening_weekend_hours",
    label: "Evening/Weekend Appointments",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "You don't have to choose between work and care",
  },
  {
    tag_key: "self_pay_friendly",
    label: "Self-Pay Friendly",
    category: "Health & Wellness",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Sliding scale, cash pay, or transparent pricing without insurance",
  },

  // ── Legal & Government Services ────────────────────────────────────────────────────
  {
    tag_key: "staff_looked_like_me",
    label: "Staff Looked Like Me",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "Representatio n from the front desk back",
  },
  {
    tag_key: "no_surprise_bills",
    label: "No Surprise Bills",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all real subcats",
    helper_text: "The bill matched what you were told",
  },
  {
    tag_key: "fought_for_me",
    label: "Fought For Me",
    category: "Legal & Government Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "attorneys, mediation, immigration, public services",
    helper_text: "Genuine advocacy, not a filing service",
  },
  {
    tag_key: "explained_my_rights",
    label: "Explained My Rights",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You learned what you were actually entitled to",
  },
  {
    tag_key: "didn_t_take_my_money_and_ghost",
    label: "Didn't Take My Money And Ghost",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, legal document services",
    helper_text: "Communicati on stayed consistent after the retainer cleared",
  },
  {
    tag_key: "handled_my_immigration_case_with_care",
    label: "Handled My Immigration Case With Care",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "immigration services, attorneys",
    helper_text: "Trust with the highest stakes there are",
  },
  {
    tag_key: "kept_my_family_together",
    label: "Kept My Family Together",
    category: "Legal & Government Services",
    type: "real-adaptive",
    adaptive_family: "protected_my_privacy",
    subcategory_scope: "attorneys, immigration, mediation",
    helper_text: "The outcome that mattered more than anything",
  },
  {
    tag_key: "treated_me_with_dignity",
    label: "Treated Me With Dignity",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "government offices, public services, all",
    helper_text: "No dismissivenes s at the counter",
  },
  {
    tag_key: "showed_up_to_court_prepared",
    label: "Showed Up To Court Prepared",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, mediation, immigration",
    helper_text: "They knew your file cold when it counted",
  },
  {
    tag_key: "didn_t_make_me_feel_criminal",
    label: "Didn't Make Me Feel Criminal",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, government offices, public services",
    helper_text: "You were a client, not a suspect",
  },
  {
    tag_key: "understood_the_system_works_against_us",
    label: "Understood The System Works Against Us",
    category: "Legal & Government Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "all",
    helper_text: "They named it out loud and planned around it",
  },
  {
    tag_key: "called_me_back_same_day",
    label: "Called Me Back Same Day",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, mediation, legal document services",
    helper_text: "You were never left waiting in the dark",
  },
  {
    tag_key: "pro_bono_when_i_needed_it",
    label: "Pro Bono When I Needed It",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, mediation, immigration, legal",
    helper_text: "They worked when you couldn't pay",
  },
  {
    tag_key: "explained_every_step_before_we_took_it",
    label: "Explained Every Step Before We Took It",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Attorneys & Law Firms; Immigration Attorneys; Family Law; Criminal Defense; Housing & Tenant Law",
    helper_text: "I knew what was happening, why, and what came next",
  },
  {
    tag_key: "didn_t_promise_me_a_guaranteed_outcome",
    label: "Didn't Promise Me A Guaranteed Outcome",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Attorneys & Law Firms; Immigration Attorneys; Family Law; Criminal Defense; Personal Injury",
    helper_text: "They were hopeful without selling me certainty",
  },
  {
    tag_key: "understood_my_immigration_status_without_judgment",
    label: "Understood My Immigration Status Without Judgment",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Immigration Attorneys; Immigration Services",
    helper_text: "I could tell the whole story without being shamed or treated as suspicious",
  },
  {
    tag_key: "protected_my_privacy",
    label: "Protected My Privacy",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Immigration Attorneys; Immigration Services; Attorneys & Law Firms",
    helper_text: "Sensitive information was handled carefully",
  },
  {
    tag_key: "made_sure_i_understood_before_i_signed",
    label: "Made Sure I Understood Before I Signed",
    category: "Legal & Government Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Attorneys & Law Firms; Immigration Attorneys; Legal Document Services; Notary Services",
    helper_text: "Nothing was rushed past me because the paperwork was complicated",
  },

  // ── Financial & Business Services ────────────────────────────────────────────────────
  {
    tag_key: "knew_the_judge_and_the_room",
    label: "Knew The Judge And The Room",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, mediation",
    helper_text: "Local knowledge that changed the outcome",
  },
  {
    tag_key: "paperwork_was_done_right",
    label: "Paperwork Was Done Right",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "immigration, legal document services, notary, attorneys",
    helper_text: "Nothing bounced back, nothing was refiled",
  },
  {
    tag_key: "didn_t_rush_my_case",
    label: "Didn't Rush My Case",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "attorneys, immigration, mediation",
    helper_text: "They took the time your case actually needed",
  },
  {
    tag_key: "translated_everything",
    label: "Translated Everything",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Every document, every hearing, in your language",
  },
  {
    tag_key: "made_me_feel_like_i_mattered",
    label: "Made Me Feel Like I Mattered",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You were a person, not a case number in a stack",
  },
  {
    tag_key: "no_predatory_fees",
    label: "No Predatory Fees",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "attorneys, immigration, legal document services, notary",
    helper_text: "The fee structure was honest from the first meeting",
  },
  {
    tag_key: "said_yes_when_others_said_no",
    label: "Said Yes When Others Said No",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "lending, mortgage, credit services, business funding",
    helper_text: "They looked past the algorithm at the actual person",
  },
  {
    tag_key: "no_predatory_terms",
    label: "No Predatory Terms",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "lending, credit services, business funding, mortgage",
    helper_text: "Fair rates, no traps buried on page nine",
  },
  {
    tag_key: "got_me_funded",
    label: "Got Me Funded",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "business funding, lending, mortgage",
    helper_text: "The capital actually came through",
  },
  {
    tag_key: "taught_me_to_build_wealth",
    label: "Taught Me To Build Wealth",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "financial advisors, investment services, banks & credit unions",
    helper_text: "Education, not just transactions",
  },
  {
    tag_key: "explained_my_credit_plain",
    label: "Explained My Credit Plain",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "credit services, lending, mortgage,",
    helper_text: "You finally understood your own report",
  },
  {
    tag_key: "didn_t_judge_my_starting_point",
    label: "Didn't Judge My Starting Point",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Wherever you started, that's where they met you",
  },
  {
    tag_key: "showed_me_the_path",
    label: "Showed Me The Path",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You left with a plan, not just a product",
  },
  {
    tag_key: "celebrated_my_first_investment",
    label: "Celebrated My First Investment",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "financial advisors, investment services, banks & credit unions",
    helper_text: "Small beginnings treated like they mattered",
  },
  {
    tag_key: "understood_generational_wealth_gaps",
    label: "Understood Generational Wealth Gaps",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "all",
    helper_text: "They knew you were building without inheritance",
  },
  {
    tag_key: "no_minimum_to_be_respected",
    label: "No Minimum To Be Respected",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Your balance didn't determine your treatment",
  },
  {
    tag_key: "helped_my_family_not_just_me",
    label: "Helped My Family, Not Just Me",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "protected_my_privacy",
    subcategory_scope: "financial advisors, tax preparation, investment services, banks",
    helper_text: "They planned for everybody you carry",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Financial & Business Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Real information, delivered with respect",
  },
  {
    tag_key: "didn_t_push_products_i_didn_t_need",
    label: "Didn't Push Products I Didn't Need",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "financial advisors, investment services, banks, credit services",
    helper_text: "No commission- driven recommendat ions",
  },
  {
    tag_key: "showed_me_the_total_cost_not_just_the_monthly_payment",
    label: "Showed Me The Total Cost, Not Just The Monthly Payment",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Lending & Financing; Mortgage Services; Banks & Credit Unions; Business Funding",
    helper_text: "I could see the full price of the money before agreeing",
  },
  {
    tag_key: "didn_t_treat_cash_income_like_it_wasn_t_real",
    label: "Didn't Treat Cash Income Like It Wasn't Real",
    category: "Financial & Business Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Mortgage Services; Lending & Financing; Banks & Credit Unions",
    helper_text: "They explained what documentation could support my application",
  },

  // ── Professional Services ────────────────────────────────────────────────────
  {
    tag_key: "fought_the_denial",
    label: "Fought The Denial",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "lending, mortgage, credit services, business funding",
    helper_text: "They appealed it instead of accepting it",
  },
  {
    tag_key: "believed_my_numbers",
    label: "Believed My Numbers",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "business funding, lending, bookkeeping, tax preparation",
    helper_text: "Your books were trusted, not interrogated",
  },
  {
    tag_key: "fought_for_me",
    label: "Fought For Me",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "legal, insurance, staffing, accounting & tax",
    helper_text: "Went to bat on your behalf",
  },
  {
    tag_key: "took_my_small_business_seriously",
    label: "Took My Small Business Seriously",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "No revenue minimum to be respected",
  },
  {
    tag_key: "taught_me_while_they_worked",
    label: "Taught Me While They Worked",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "consulting, marketing, design, web & app, IT",
    helper_text: "You learned, you weren't just billed",
  },
  {
    tag_key: "didn_t_talk_down_to_me",
    label: "Didn't Talk Down To Me",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Respect regardless of what you knew coming in",
  },
  {
    tag_key: "made_my_business_feel_big",
    label: "Made My Business Feel Big",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You got the treatment a major client gets",
  },
  {
    tag_key: "understood_my_community",
    label: "Understood My Community",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "marketing, PR, design, consulting, staffing, translation",
    helper_text: "They knew who you serve without a lecture",
  },
  {
    tag_key: "didn_t_nickel_and_dime_me",
    label: "Didn't Nickel And Dime Me",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Every question didn't turn into a line item",
  },
  {
    tag_key: "available_when_i_panicked",
    label: "Available When I Panicked",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "accounting & tax, legal, insurance, IT, consulting, VA",
    helper_text: "The emergency call got answered",
  },
  {
    tag_key: "grew_with_me",
    label: "Grew With Me",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Still your person three years in",
  },
  {
    tag_key: "referred_me_to_their_people",
    label: "Referred Me To Their People",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "They opened their network to you",
  },
  {
    tag_key: "kept_my_books_clean",
    label: "Kept My Books Clean",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "accounting & tax, financial services, bookkeeping- adjacent",
    helper_text: "Audit-ready, no scrambling in April",
  },
  {
    tag_key: "tax_refund_was_right",
    label: "Tax Refund Was Right",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "accounting & tax",
    helper_text: "Correct the first time, no amended return",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Substance, delivered with respect",
  },
  {
    tag_key: "contract_had_no_traps",
    label: "Contract Had No Traps",
    category: "Professional Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "all",
    helper_text: "You could sign it without a second lawyer",
  },
  {
    tag_key: "explained_everything_clearly",
    label: "Explained Everything Clearly",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "I understood what they were doing, what they needed from me, and what came next",
  },
  {
    tag_key: "didn_t_make_me_prove_i_belonged_in_the_room",
    label: "Didn't Make Me Prove I Belonged In The Room",
    category: "Professional Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Business Consulting; Marketing & Advertising; Public Relations; Staffing & Recruiting; Executive Coaching",
    helper_text: "My experience and ambition were taken seriously from the start",
  },

  // ── Technology & Digital Services ────────────────────────────────────────────────────
  {
    tag_key: "believed_my_vision",
    label: "Believed My Vision",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "consulting, marketing, PR, design, web & app",
    helper_text: "They took your idea seriously from day one",
  },
  {
    tag_key: "explained_it_without_the_jargon",
    label: "Explained It Without The Jargon",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Plain language from start to finish",
  },
  {
    tag_key: "handed_over_the_passwords",
    label: "Handed Over The Passwords",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, IT support, SaaS",
    helper_text: "You own your domain, hosting, and accounts",
  },
  {
    tag_key: "built_for_our_community",
    label: "Built For Our Community",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Designed with us in mind, not retrofitted",
  },
  {
    tag_key: "didn_t_talk_down_to_me",
    label: "Didn't Talk Down To Me",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Respect regardless of your tech level",
  },
  {
    tag_key: "didn_t_make_me_feel_dumb",
    label: "Didn't Make Me Feel Dumb",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "No sighing, no eye- rolling, no \"obviously\"",
  },
  {
    tag_key: "actually_tested_it",
    label: "Actually Tested It",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, software,",
    helper_text: "It worked on delivery, not",
  },
  {
    tag_key: "answered_at_11pm",
    label: "Answered At 11pm",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "IT support, cybersecurity, web dev, app dev, SaaS",
    helper_text: "The site went down and somebody picked up",
  },
  {
    tag_key: "taught_my_team_to_fish",
    label: "Taught My Team To Fish",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "consulting, IT support, SaaS, AI & automation, web dev",
    helper_text: "You aren't dependent on them forever",
  },
  {
    tag_key: "didn_t_hold_my_site_hostage",
    label: "Didn't Hold My Site Hostage",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, IT support, SaaS",
    helper_text: "Full access, no ransom, clean handoff",
  },
  {
    tag_key: "understood_my_audience",
    label: "Understood My Audience",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "web dev, app dev, digital products, consulting",
    helper_text: "They built for the people you actually serve",
  },
  {
    tag_key: "made_it_accessible",
    label: "Made It Accessible",
    category: "Technology & Digital Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "web dev, app dev, digital products, SaaS",
    helper_text: "Screen readers, contrast, older phones, slow data",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Technical truth, no condescensio n",
  },
  {
    tag_key: "contract_had_no_traps",
    label: "Contract Had No Traps",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "all",
    helper_text: "No auto- renew ambush, no ownership grab",
  },
  {
    tag_key: "believed_my_bug_report",
    label: "Believed My Bug Report",
    category: "Technology & Digital Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "software, SaaS, app dev, web dev, IT support",
    helper_text: "\"It's not doing that\" was never the answer",
  },

  // ── Home & Property Services ────────────────────────────────────────────────────
  {
    tag_key: "fixed_it_right_the_first_time",
    label: "Fixed It Right The First Time",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, roofing, handyman, pest control",
    helper_text: "No second call, no callback fee",
  },
  {
    tag_key: "respected_my_home",
    label: "Respected My Home",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Shoes off, drop cloths, care taken",
  },
  {
    tag_key: "honest_about_what_i_didn_t_need",
    label: "Honest About What I Didn't Need",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, roofing, inspection, pest control",
    helper_text: "They talked you out of spending money",
  },
  {
    tag_key: "didn_t_talk_down_to_me",
    label: "Didn't Talk Down To Me",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Explained without condescensio n",
  },
  {
    tag_key: "didn_t_overcharge_for_my_zip_code",
    label: "Didn't Overcharge For My Zip Code",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Same price they'd quote across town",
  },
  {
    tag_key: "showed_up_in_my_neighborhood",
    label: "Showed Up In My Neighborhood",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Community- reported: no excuses",
  },
  {
    tag_key: "treated_my_apartment_like_a_house",
    label: "Treated My Apartment Like A House",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, cleaning, handyman, pest control, property management",
    helper_text: "Renters got the same care as owners",
  },
  {
    tag_key: "didn_t_scare_me_into_more_work",
    label: "Didn't Scare Me Into More Work",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "contractors, electricians, plumbing, HVAC, roofing, inspection, pest control",
    helper_text: "No manufactured emergencies",
  },
  {
    tag_key: "left_my_floors_clean",
    label: "Left My Floors Clean",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "You didn't clean up behind them",
  },
  {
    tag_key: "good_with_my_grandmother",
    label: "Good With My Grandmother",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Safe and patient in an elder's home, alone",
  },
  {
    tag_key: "quote_had_no_traps",
    label: "Quote Had No Traps",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "contractors, construction, roofing, HVAC, moving, property management",
    helper_text: "The final number matched the signed number",
  },
  {
    tag_key: "knows_what_we_face_with_housing",
    label: "Knows What We Face With Housing",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "real estate agents & brokers, property management, home inspection",
    helper_text: "They understood appraisal gaps and steering",
  },
  {
    tag_key: "believed_me_about_the_problem",
    label: "Believed Me About The Problem",
    category: "Home & Property Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "plumbing, electricians, HVAC, property",
    helper_text: "They came out and looked",
  },
  {
    tag_key: "didn_t_steer_me_away_from_a_neighborhood",
    label: "Didn't Steer Me Away From A Neighborhood",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Real Estate Agents & Brokers; Housing Counselors",
    helper_text: "They gave information without deciding where someone like me should live",
  },
  {
    tag_key: "explained_first_time_buyer_programs",
    label: "Explained First-Time Buyer Programs",
    category: "Home & Property Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "Real Estate Agents & Brokers; Housing Counselors; Mortgage & Homebuyer Counseling",
    helper_text: "They showed me assistance and programs I might qualify for",
  },

  // ── Automotive & Transportation ────────────────────────────────────────────────────
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Showed you the work and the why",
  },
  {
    tag_key: "didn_t_upsell_me",
    label: "Didn't Upsell Me",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision",
    helper_text: "Only what the car actually needed",
  },
  {
    tag_key: "showed_me_the_old_part",
    label: "Showed Me The Old Part",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, body & collision",
    helper_text: "Proof the work was really done",
  },
  {
    tag_key: "safe_for_women_coming_alone",
    label: "Safe For Women Coming Alone",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Community- reported: respectful, no pressure, no creeping",
  },
  {
    tag_key: "didn_t",
    label: "Didn't",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision",
    helper_text: "They talked to you like you'd been under a hood",
  },
  {
    tag_key: "gave_me_the_real_price_first",
    label: "Gave Me The Real Price First",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "The first number was the honest number",
  },
  {
    tag_key: "didn_t_talk_past_me_to_my_husband",
    label: "Didn't Talk Past Me To My Husband",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision, towing",
    helper_text: "They addressed you, the actual customer",
  },
  {
    tag_key: "remembered_my_car_s_history",
    label: "Remembered My Car's History",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, body & collision, detailing",
    helper_text: "They knew the vehicle before you explained it",
  },
  {
    tag_key: "honest_about_what_could_wait",
    label: "Honest About What Could Wait",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "auto repair, tire, dealers, body & collision",
    helper_text: "They told you what could hold until next month",
  },
  {
    tag_key: "financing_had_no_traps",
    label: "Financing Had No Traps",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "auto dealers, transportation companies",
    helper_text: "No rate markup, no packed payments",
  },
  {
    tag_key: "believed_me_about_the_sound",
    label: "Believed Me About The Sound",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "auto repair, tire, body & collision",
    helper_text: "They drove it and listened instead of dismissing you",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "auto repair, tire, dealers, body & collision, towing",
    helper_text: "Showed you the diagnostic and walked it through",
  },
  {
    tag_key: "fought_my_insurance_for_me",
    label: "Fought My Insurance For Me",
    category: "Automotive & Transportation",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "auto body & collision, auto repair, towing",
    helper_text: "They handled the adjuster so you didn't have to",
  },
  {
    tag_key: "didn_t_leave_me_stranded",
    label: "Didn't Leave Me Stranded",
    category: "Automotive & Transportation",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "towing & roadside, auto repair, car rental, transportation companies",
    helper_text: "They got you home before they got paid",
  },

  // ── Pets & Animal Services ────────────────────────────────────────────────────
  {
    tag_key: "knows_what_we_face_on_the_road",
    label: "Knows What We Face On The Road",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "chauffeur & private driver, transportation companies, towing & roadside",
    helper_text: "Community- reported understandin g of roadside risk for us",
  },
  {
    tag_key: "my_dog_wasn_t_scared",
    label: "My Dog Wasn't Scared",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "vets, grooming, boarding, daycare, training",
    helper_text: "Calm afterward, not traumatized",
  },
  {
    tag_key: "honest_about_treatment_cost",
    label: "Honest About Treatment Cost",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, training",
    helper_text: "No fear-based upselling on a sick animal",
  },
  {
    tag_key: "no_breed_judgment",
    label: "No Breed Judgment",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "all",
    helper_text: "Pit bulls and big dogs treated fairly",
  },
  {
    tag_key: "didn_t_judge_what_i_could_afford",
    label: "Didn't Judge What I Could Afford",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, grooming, training, boarding",
    helper_text: "They found a way within your budget",
  },
  {
    tag_key: "gave_me_real_options",
    label: "Gave Me Real Options",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, training",
    helper_text: "Every path explained, including the affordable one",
  },
  {
    tag_key: "didn_t_assume_i_neglected_them",
    label: "Didn't Assume I Neglected Them",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, grooming, training",
    helper_text: "No lecture, no accusation, just care",
  },
  {
    tag_key: "stayed_after_hours_for_us",
    label: "Stayed After Hours For Us",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, boarding, pet sitting",
    helper_text: "The door didn't close on an emergency",
  },
  {
    tag_key: "handled_our_loss_with_grace",
    label: "Handled Our Loss With Grace",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians",
    helper_text: "Dignity when you had to say goodbye",
  },
  {
    tag_key: "payment_plan_was_real",
    label: "Payment Plan Was Real",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "veterinarians, training, boarding",
    helper_text: "No interest trap on a sick animal",
  },
  {
    tag_key: "believed_something_was_wrong",
    label: "Believed Something Was Wrong",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "veterinarians, training",
    helper_text: "You know your animal, and they trusted that",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "veterinarians, training, grooming",
    helper_text: "Real medical information, respectfully given",
  },
  {
    tag_key: "fought_for_my_animal",
    label: "Fought For My Animal",
    category: "Pets & Animal Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "veterinarians",
    helper_text: "They exhausted every option before giving up",
  },
  {
    tag_key: "good_with_my_kids_watching",
    label: "Good With My Kids Watching",
    category: "Pets & Animal Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "veterinarians, grooming, training, pet stores",
    helper_text: "Patient with children in the room",
  },

  // ── Other Services ────────────────────────────────────────────────────
  {
    tag_key: "handled_our_loss_with_grace",
    label: "Handled Our Loss With Grace",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services",
    helper_text: "Dignity for your family in grief",
  },
  {
    tag_key: "honored_our_traditions",
    label: "Honored Our Traditions",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services",
    helper_text: "The homegoing was done our way",
  },
  {
    tag_key: "didn_t_upsell_us_in_grief",
    label: "Didn't Upsell Us In Grief",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services",
    helper_text: "No pressure at the worst moment of your life",
  },
  {
    tag_key: "gave_us_the_price_list_up_front",
    label: "Gave Us The Price List Up Front",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "no_predatory_terms",
    subcategory_scope: "funeral & memorial services, storage, shipping & mailing, personal concierge",
    helper_text: "Every cost in writing before any decision",
  },
  {
    tag_key: "worked_with_what_we_had",
    label: "Worked With What We Had",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "funeral & memorial services, tailoring, shoe repair, storage, laundry",
    helper_text: "They made it beautiful within your means",
  },
  {
    tag_key: "didn_t_judge_what_i_brought_in",
    label: "Didn't Judge What I Brought In",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "laundry & dry cleaning, tailoring & alterations, shoe repair",
    helper_text: "Old and worn was treated like new and expensive",
  },
  {
    tag_key: "came_when_i_was_stuck",
    label: "Came When I Was Stuck",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "locksmiths, personal concierge, storage",
    helper_text: "Late, alone, locked out, and they showed up",
  },
  {
    tag_key: "didn_t_gouge_me_in_an_emergency",
    label: "Didn't Gouge Me In An Emergency",
    category: "Other Services",
    type: "real-specific",
    adaptive_family: null,
    subcategory_scope: "locksmiths, personal concierge, shipping & mailing",
    helper_text: "The 2am price was a fair price",
  },
  {
    tag_key: "believed_me_about_the_damage",
    label: "Believed Me About The Damage",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "believed_me",
    subcategory_scope: "laundry & dry cleaning, shipping & mailing, storage, tailoring",
    helper_text: "They made it right without a fight",
  },
  {
    tag_key: "protected_my_family",
    label: "Protected My Family",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "protected_my_privacy",
    subcategory_scope: "funeral & memorial services, personal concierge, locksmiths",
    helper_text: "They carried your family through it",
  },
  {
    tag_key: "explained_it_like_i_was_smart",
    label: "Explained It Like I Was Smart",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "explained_like_i_was_smart",
    subcategory_scope: "all",
    helper_text: "Straight answers, no runaround",
  },
  {
    tag_key: "knows_what_our_traditions_require",
    label: "Knows What Our Traditions Require",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "knows_what_we_face",
    subcategory_scope: "funeral & memorial services, tailoring & alterations, personal concierge",
    helper_text: "No explaining your customs from scratch",
  },
  {
    tag_key: "fought_for_my_claim",
    label: "Fought For My Claim",
    category: "Other Services",
    type: "real-adaptive",
    adaptive_family: "fought_for_me",
    subcategory_scope: "shipping & mailing, storage, laundry & dry cleaning",
    helper_text: "They pursued the carrier or insurer on your behalf",
  },

  // ── Financial & Business Services — Accountants & Tax ─────────────────
  { tag_key: "tax_explained_clearly", label: "Explained Everything Clearly", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Bookkeeping", helper_text: "No jargon, no confusion" },
  { tag_key: "tax_didnt_feel_dumb", label: "Didn't Make Me Feel Dumb", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "Every question was a fair question" },
  { tag_key: "tax_found_what_missing", label: "Found What I Was Missing", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "Caught deductions and credits you didn't know existed" },
  { tag_key: "tax_saved_me_money", label: "Saved Me Money", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Tax Resolution", helper_text: "The bill was lower than expected" },
  { tag_key: "tax_real_deductions", label: "Told Me What I Could Actually Deduct", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "No guessing — they knew the rules" },
  { tag_key: "tax_small_biz_serious", label: "Took My Small Business Seriously", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Bookkeeping; Payroll", helper_text: "A solo business wasn't treated like a hobby" },
  { tag_key: "tax_self_employment", label: "Understood Self-Employment Income", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "Knew the complexity of 1099 income without being told" },
  { tag_key: "tax_multiple_streams", label: "Understood Multiple Income Streams", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "W2 + side hustle + investments — they handled all of it" },
  { tag_key: "tax_cleaned_books", label: "Helped Me Clean Up My Books", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Bookkeeping", helper_text: "They organized the mess without judgment" },
  { tag_key: "tax_fixed_past_mistakes", label: "Helped Me Fix Past Mistakes", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Tax Resolution; IRS Audits", helper_text: "Prior years were handled, not avoided" },
  { tag_key: "tax_explained_what_owed", label: "Explained What I Owed And Why", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Tax Resolution", helper_text: "The number wasn't just handed to you" },
  { tag_key: "tax_no_fake_refund", label: "Didn't Promise Me A Fake Refund", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "Honest about what you'd actually get back" },
  { tag_key: "tax_kept_out_trouble", label: "Kept Me Out Of Trouble", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Tax Resolution; IRS Audits", helper_text: "Compliance without drama" },
  { tag_key: "tax_plan_next_year", label: "Helped Me Plan For Next Year", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "They thought past this tax season" },
  { tag_key: "tax_no_judgment", label: "Answered My Questions Without Judgment", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Bookkeeping", helper_text: "Nothing was too basic to ask" },
  { tag_key: "tax_no_shame_behind", label: "Didn't Shame Me For Being Behind", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Tax Resolution", helper_text: "They started from where you were" },
  { tag_key: "tax_gave_a_plan", label: "Gave Me A Plan", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Bookkeeping", helper_text: "You left knowing the next step" },
  { tag_key: "tax_stayed_available", label: "Stayed Available After Filing", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals", helper_text: "Questions after April didn't go to voicemail" },
  { tag_key: "tax_trust_with_business", label: "I'd Trust Them With My Business", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Accountants & Tax Professionals; Bookkeeping; Payroll", helper_text: "Long-term trust earned" },
  // ── Financial & Business Services — Insurance ──────────────────────────
  { tag_key: "ins_explained_buying", label: "Explained What I Was Actually Buying", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "No buying blind — every line was explained" },
  { tag_key: "ins_explained_gaps", label: "Explained What Wasn't Covered", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "The fine print was made plain before you signed" },
  { tag_key: "ins_no_oversell", label: "Didn't Oversell Me", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "Coverage matched your actual needs" },
  { tag_key: "ins_within_budget", label: "Found Coverage Within My Budget", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "Real options at your actual price point" },
  { tag_key: "ins_compared_options", label: "Compared My Options", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "You saw more than one choice" },
  { tag_key: "ins_deductible_clear", label: "Helped Me Understand The Deductible", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals", helper_text: "The number that actually matters in a claim was explained" },
  { tag_key: "ins_told_the_gaps", label: "Told Me Where The Gaps Were", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "Proactively identified what your policy didn't cover" },
  { tag_key: "ins_answered_claim", label: "Answered When I Had A Claim", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals", helper_text: "The person who sold you the policy was still there when you needed them" },
  { tag_key: "ins_stayed_involved", label: "Stayed Involved When Something Went Wrong", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals", helper_text: "They didn't hand you a phone number and disappear" },
  { tag_key: "ins_fought_denial", label: "Helped Me Fight The Denial", category: "Financial & Business Services", type: "real-adaptive", adaptive_family: "fought_for_me", subcategory_scope: "Insurance Professionals", helper_text: "They pushed back on the claim denial on your behalf" },
  { tag_key: "ins_didnt_disappear", label: "Didn't Disappear After The Sale", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "Commission wasn't the last time you heard from them" },
  { tag_key: "ins_reviewed_coverage", label: "Reviewed My Coverage With Me", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals", helper_text: "Annual check-in wasn't just a upsell call" },
  { tag_key: "ins_family_protected", label: "Made Sure My Family Was Protected", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals", helper_text: "Thought through what matters most to you" },
  { tag_key: "ins_small_biz_serious", label: "Took My Small Business Seriously", category: "Financial & Business Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Insurance Professionals; Insurance Brokers", helper_text: "Commercial coverage wasn't only for corporations" },
  // ── Professional Services — Staffing / Recruiting / Career Services ────
  { tag_key: "staff_saw_more_than_resume", label: "Saw More Than My Resume", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching; Career Services", helper_text: "The whole person was considered" },
  { tag_key: "staff_experience_seriously", label: "Took My Experience Seriously", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Services", helper_text: "Non-traditional paths weren't penalized" },
  { tag_key: "staff_no_prove_belonged", label: "Didn't Make Me Prove I Belonged", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching", helper_text: "No invisible credential test" },
  { tag_key: "staff_explained_salary", label: "Explained The Salary Range", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting", helper_text: "Transparent about what the role actually pays" },
  { tag_key: "staff_honest_employer", label: "Was Honest About The Employer", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting", helper_text: "Flagged culture issues before you accepted" },
  { tag_key: "staff_prepared_interview", label: "Prepared Me For The Interview", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching", helper_text: "You walked in ready, not cold" },
  { tag_key: "staff_no_waste_time", label: "Didn't Waste My Time", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting", helper_text: "Every role presented was actually a real possibility" },
  { tag_key: "staff_kept_updated", label: "Kept Me Updated", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Services", helper_text: "No waiting in the dark wondering what happened" },
  { tag_key: "staff_advocated_pay", label: "Advocated For My Pay", category: "Professional Services", type: "real-adaptive", adaptive_family: "fought_for_me", subcategory_scope: "Staffing & Recruiting", helper_text: "They pushed for what you were worth" },
  { tag_key: "staff_opened_rooms", label: "Put Me In Rooms I Couldn't Reach Alone", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching", helper_text: "Genuine access, not just a job board" },
  { tag_key: "staff_career_changes", label: "Understood Career Changes", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching", helper_text: "Industry transitions were treated as experience, not gaps" },
  { tag_key: "staff_nontraditional_path", label: "Understood Nontraditional Experience", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching", helper_text: "Gig work, community leadership, and side hustles counted" },
  { tag_key: "staff_translated_skills", label: "Helped Me Translate My Skills", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching", helper_text: "Made what you do make sense to employers" },
  { tag_key: "staff_no_first_job_push", label: "Didn't Push Me Into The First Job Available", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting", helper_text: "They cared about the right fit, not the fastest fill" },
  { tag_key: "staff_actually_fit", label: "Found Something That Actually Fit", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Services", helper_text: "Role and culture matched who you are" },
  { tag_key: "staff_called_back", label: "Called Me Back", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Services", helper_text: "Basic follow-through that means a lot" },
  { tag_key: "staff_followed_through", label: "Followed Through", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Staffing & Recruiting; Career Coaching; Career Services", helper_text: "They did what they said they would do" },
  // ── Professional Services — Translation & Language Services ───────────
  { tag_key: "trans_speaks_my_language", label: "They Speak My Language", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "Not just words — your language, fully" },
  { tag_key: "trans_meaning_not_words", label: "Explained The Meaning, Not Just The Words", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "Cultural context wasn't lost in translation" },
  { tag_key: "trans_didnt_rush", label: "Didn't Rush Me", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "The pace was yours" },
  { tag_key: "trans_protected_privacy", label: "Protected My Privacy", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services", helper_text: "Sensitive information stayed private" },
  { tag_key: "trans_made_sure_understood", label: "Made Sure I Understood", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "They checked, not assumed" },
  { tag_key: "trans_respected_dialect", label: "Respected My Dialect", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "Your way of speaking was honored, not corrected" },
  { tag_key: "trans_cultural_context", label: "Understood Cultural Context", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "What couldn't be directly translated was explained" },
  { tag_key: "trans_no_embarrassment", label: "Didn't Make Me Feel Embarrassed", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "Patience, not condescension" },
  { tag_key: "trans_helped_family", label: "Helped My Family Understand", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "Everyone in the room left knowing what was said" },
  { tag_key: "trans_accurate_documents", label: "Was Accurate With Important Documents", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services", helper_text: "Legal, medical, and official docs were handled with precision" },
  { tag_key: "trans_explained_not_literal", label: "Explained What Could Not Be Translated Literally", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "Cultural nuance was preserved" },
  { tag_key: "trans_stayed_patient", label: "Stayed Patient Through Questions", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Translation & Language Services; Interpretation", helper_text: "No sighing, no rushing" },
  // ── Professional Services — Travel Advisors / Travel Agencies ─────────
  { tag_key: "ta_helped_when_wrong", label: "Helped Me When Something Went Wrong", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "The real test of a travel professional" },
  { tag_key: "ta_answered_when_needed", label: "Answered When I Needed Them", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Available before, during, and after the trip" },
  { tag_key: "ta_didnt_disappear_after_paid", label: "Didn't Disappear After I Paid", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Commission didn't close the door" },
  { tag_key: "ta_stayed_through_problem", label: "Stayed With Me Through The Problem", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "They didn't hand you a 1-800 number and disappear" },
  { tag_key: "ta_flight_changed", label: "Helped When My Flight Changed", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Disruption was handled, not just reported" },
  { tag_key: "ta_hotel_wasnt_right", label: "Helped When The Hotel Wasn't Right", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "A bad property was fixed, not defended" },
  { tag_key: "ta_fought_refund", label: "Fought For My Refund / Credit", category: "Professional Services", type: "real-adaptive", adaptive_family: "fought_for_me", subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Pursued the carrier or vendor on your behalf" },
  { tag_key: "ta_explained_fine_print", label: "Explained The Fine Print", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Cancellation, change fees, and restrictions were plain before you committed" },
  { tag_key: "ta_what_is_refundable", label: "Told Me What Was Actually Refundable", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "No surprises when plans changed" },
  { tag_key: "ta_no_false_promises", label: "Didn't Make Promises They Couldn't Keep", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Honest expectations from the start" },
  { tag_key: "ta_honest_destination", label: "Was Honest About The Destination", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Including the parts the tourist board doesn't advertise" },
  { tag_key: "ta_warned_me", label: "Warned Me About What I Needed To Know", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Prepared you, not just booked you" },
  { tag_key: "ta_safety_concerns", label: "Took My Safety Concerns Seriously", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Traveling while Black wasn't an afterthought" },
  { tag_key: "ta_traveling_while_black", label: "Understood Traveling While Black", category: "Professional Services", type: "real-adaptive", adaptive_family: "knows_what_we_face", subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Named the reality and planned for it" },
  { tag_key: "ta_family_needs", label: "Understood My Family's Needs", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Thought about the kids, the elders, the whole crew" },
  { tag_key: "ta_respected_budget", label: "Respected My Budget", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "Real options at your real budget" },
  { tag_key: "ta_no_budget_judgment", label: "Didn't Judge How Much I Could Spend", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "No attitude about the number" },
  { tag_key: "ta_travel_insurance_clear", label: "Explained Travel Insurance Clearly", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "You actually understood what you were buying" },
  { tag_key: "ta_understood_before_paid", label: "Made Sure I Understood Before I Paid", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "No signatures before comprehension" },
  { tag_key: "ta_checked_during_trip", label: "Checked On Me During The Trip", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "A message mid-trip to make sure everything was right" },
  { tag_key: "ta_had_backup_plan", label: "Had A Backup Plan", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "When things changed, there was already an answer" },
  { tag_key: "ta_helped_get_home", label: "Helped Me Get Home", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "When nothing was going right, they got you back" },
  { tag_key: "ta_not_on_my_own", label: "Made Me Feel Like I Wasn't On My Own", category: "Professional Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Travel Advisors; Travel Agencies", helper_text: "A real advocate, not just a booking engine" },
  // ── Home & Property Services — Movers ─────────────────────────────────
  { tag_key: "mover_showed_up_time", label: "Showed Up On Time", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Moving day doesn't have room for late" },
  { tag_key: "mover_quote_matched_bill", label: "Quote Matched The Bill", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "The number they gave was the number you paid" },
  { tag_key: "mover_no_hostage", label: "Didn't Hold My Stuff Hostage", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Everything arrived without last-minute demands" },
  { tag_key: "mover_handled_with_care", label: "Handled My Things With Care", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Treated your belongings like their own" },
  { tag_key: "mover_nothing_missing", label: "Nothing Went Missing", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Full trust in the crew" },
  { tag_key: "mover_nothing_broken", label: "Nothing Was Broken", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "The fragile stuff made it" },
  { tag_key: "mover_protected_furniture", label: "Protected My Furniture", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Wrapped, padded, and moved right" },
  { tag_key: "mover_quick_not_careless", label: "Worked Quickly Without Being Careless", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Efficient and careful at the same time" },
  { tag_key: "mover_no_surprise_fees", label: "Didn't Add Surprise Fees", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "No extra charges that weren't discussed" },
  { tag_key: "mover_explained_extra", label: "Explained Extra Charges Before Doing The Work", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Any additions were approved first" },
  { tag_key: "mover_respected_home", label: "Respected My Home", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Floors, walls, and doorframes came through fine" },
  { tag_key: "mover_less_stressful", label: "Made Moving Day Less Stressful", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "One of the hardest days was easier" },
  { tag_key: "mover_good_with_elders", label: "Good With My Elders", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "Patient and respectful with the older family members" },
  { tag_key: "mover_call_again", label: "I'd Call Them Again", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Movers & Moving Services", helper_text: "The strongest endorsement a mover can earn" },
  // ── Home & Property Services — Cleaning Services ──────────────────────
  { tag_key: "clean_actually_clean", label: "My House Was Actually Clean", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Not just tidied — actually cleaned" },
  { tag_key: "clean_no_corners_cut", label: "Didn't Cut Corners", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "The behind-the-toilet and under-the-couch spots were done" },
  { tag_key: "clean_paid_attention_details", label: "Paid Attention To The Details", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "The things you notice when you look close were handled" },
  { tag_key: "clean_respected_home", label: "Respected My Home", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Personal items were left exactly as found" },
  { tag_key: "clean_used_right_products", label: "Used What I Asked Them To Use", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Product preferences were honored" },
  { tag_key: "clean_around_family", label: "Worked Around My Family", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Kids, pets, and home schedules were accommodated" },
  { tag_key: "clean_showed_up_time", label: "Showed Up On Time", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "The window they gave was the window they kept" },
  { tag_key: "clean_quote_matched", label: "Quote Matched The Bill", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "No surprise charges at the end" },
  { tag_key: "clean_no_judgment", label: "Didn't Judge My Home", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Life happens — they came to help, not critique" },
  { tag_key: "clean_comfortable_in_space", label: "Made Me Feel Comfortable Having Them In My Space", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Trust in your home is a high bar — they cleared it" },
  { tag_key: "clean_careful_belongings", label: "Took Care Around My Belongings", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "Nothing was moved or damaged without consent" },
  { tag_key: "clean_trust_again", label: "I'd Trust Them In My Home Again", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Cleaning Services; Housekeeping", helper_text: "The ultimate endorsement for an in-home service" },
  // ── Home & Property Services — Property Management / Renter Experience ─
  { tag_key: "pm_answered_maintenance", label: "Answered The Maintenance Request", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "The request went somewhere and someone came" },
  { tag_key: "pm_no_ignore", label: "Didn't Ignore The Problem", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "The issue wasn't filed away and forgotten" },
  { tag_key: "pm_fixed_first_time", label: "Fixed It The First Time", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "One visit actually resolved it" },
  { tag_key: "pm_no_blame_tenant", label: "Didn't Blame The Tenant", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "The problem was investigated, not deflected" },
  { tag_key: "pm_explained_lease", label: "Explained The Lease", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords; Real Estate Agents & Brokers", helper_text: "Every clause was made plain before signing" },
  { tag_key: "pm_no_hidden_fees", label: "Didn't Hide Fees", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "All costs were disclosed upfront" },
  { tag_key: "pm_deposit_fairly", label: "Returned My Deposit Fairly", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "Normal wear was treated as normal — not charged" },
  { tag_key: "pm_respect_renters", label: "Treated Renters With Respect", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "A tenant was a person, not a problem" },
  { tag_key: "pm_no_condescend", label: "Didn't Talk To Me Like I Should Be Grateful For Basic Service", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "Basic maintenance is the agreement, not a favor" },
  { tag_key: "pm_building_cared_for", label: "Made The Building Feel Cared For", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "Common areas and building systems were maintained" },
  { tag_key: "pm_urgent_response", label: "Responded When It Was Urgent", category: "Home & Property Services", type: "real-specific", adaptive_family: null, subcategory_scope: "Property Management; Landlords", helper_text: "No heat in winter, flooding, no power — they came" },

  // ── Childcare & Early Education ───────────────────────────────────────────
  // Task #179: Trust signals for families choosing daycare, preschool, and
  // early education providers. Community-verified signals about dignity,
  // cultural competence, safety, and communication.
  { tag_key: "child_came_home_happy", label: "My Child Came Home Happy", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care", helper_text: "The most important signal — a child who wanted to go back" },
  { tag_key: "child_asked_to_go_back", label: "My Child Asked To Go Back", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "No coaxing, no tears — they were ready before you were" },
  { tag_key: "spoke_to_child_not_around", label: "Spoke To My Child, Not Around Them", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care; Tutoring", helper_text: "Got down to their level and talked to them like a person" },
  { tag_key: "called_me_right_away", label: "Called Me Right Away", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "When something happened, I heard about it immediately" },
  { tag_key: "same_teachers_stayed", label: "Same Teachers, Same Faces", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education", helper_text: "Low staff turnover — consistency matters more than most things" },
  { tag_key: "our_culture_not_a_problem", label: "Our Culture Was Never A Problem", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care", helper_text: "Our food, traditions, language — welcomed, not tolerated" },
  { tag_key: "childs_hair_respected", label: "My Child's Hair Was Respected", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education", helper_text: "No touching without permission. No comments. No 'fixing' what wasn't broken" },
  { tag_key: "dietary_needs_no_drama", label: "Handled Dietary Needs Without Drama", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "Allergies, halal, vegan — accommodated like it was no big deal" },
  { tag_key: "transition_was_gentle", label: "The Transition Was Gentle", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education", helper_text: "They helped your child feel safe before you left the room" },
  { tag_key: "real_updates_not_just_forms", label: "Real Updates, Not Just Forms", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care", helper_text: "You knew what your child actually did today, not just 'they did well'" },
  { tag_key: "knew_child_as_individual", label: "Knew My Child As An Individual", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; Tutoring", helper_text: "Not lumped in, not sorted — actually seen" },
  { tag_key: "strict_pickup_protocols", label: "Strict About Pickup — No Exceptions", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "Verified every person. Non-negotiable. Exactly as it should be" },
  { tag_key: "classroom_reflected_us", label: "The Classroom Reflected Who We Are", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education", helper_text: "Books, art, dolls — your child saw themselves on the walls" },
  { tag_key: "home_language_welcomed", label: "My Child's Home Language Was Welcomed", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education", helper_text: "Bilingual, multilingual, code-switching — never shamed" },
  { tag_key: "told_me_honestly", label: "Told Me About Incidents Honestly", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "When something went wrong, they told you the truth — not a softened version" },
  { tag_key: "iep_actually_followed", label: "My Child's IEP Was Actually Followed", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Early Childhood Education; After-School Care; Tutoring", helper_text: "The plan existed — and they actually followed it" },
  { tag_key: "welcomed_parent_questions", label: "Welcomed My Questions", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care; Tutoring", helper_text: "No defensiveness. No rushing you out. You were part of the team" },
  { tag_key: "child_made_friends_here", label: "My Child Made Friends Here", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care", helper_text: "Social belonging is part of care — they made it happen" },
  { tag_key: "health_emergency_handled_well", label: "Handled A Health Emergency Well", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "When it mattered most, they knew exactly what to do" },
  { tag_key: "discipline_not_humiliating", label: "Discipline That Taught, Not Humiliated", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care", helper_text: "Redirected, explained, talked to — never shamed or isolated" },
  { tag_key: "noticed_when_struggling", label: "Recognized When My Child Was Struggling", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care; Tutoring", helper_text: "They noticed before you had to say anything" },
  { tag_key: "environment_safe_and_clean", label: "The Environment Was Safe And Clean", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "Basic — but it has to be said because it's not always given" },
  { tag_key: "medication_administered_correctly", label: "Administered Medication Correctly", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; After-School Care", helper_text: "Required medication was given correctly, on time, every time" },
  { tag_key: "celebrated_childs_wins", label: "Celebrated My Child's Wins", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; After-School Care; Tutoring", helper_text: "Small victories counted here — reading a word, tying shoes, making a friend" },
  { tag_key: "no_ability_assumptions", label: "Didn't Assume What My Child Could Do", category: "Childcare & Early Education", type: "real-specific", adaptive_family: null, subcategory_scope: "Daycare & Childcare; Preschool; Early Childhood Education; Tutoring", helper_text: "Let them show what they were capable of — didn't decide before they tried" },

];

/** Category → THE REAL tags lookup */
export const THE_REAL_CATEGORY_MAP: Record<string, TheRealTag[]> = {
  "Health & Wellness": THE_REAL_TAGS.filter(t => t.category === "Health & Wellness"),
  "Legal & Government Services": THE_REAL_TAGS.filter(t => t.category === "Legal & Government Services"),
  "Financial & Business Services": THE_REAL_TAGS.filter(t => t.category === "Financial & Business Services"),
  "Professional Services": THE_REAL_TAGS.filter(t => t.category === "Professional Services"),
  "Technology & Digital Services": THE_REAL_TAGS.filter(t => t.category === "Technology & Digital Services"),
  "Home & Property Services": THE_REAL_TAGS.filter(t => t.category === "Home & Property Services"),
  "Automotive & Transportation": THE_REAL_TAGS.filter(t => t.category === "Automotive & Transportation"),
  "Pets & Animal Services": THE_REAL_TAGS.filter(t => t.category === "Pets & Animal Services"),
  "Other Services": THE_REAL_TAGS.filter(t => t.category === "Other Services"),
  "Childcare & Early Education": THE_REAL_TAGS.filter(t => t.category === "Childcare & Early Education"),
};

/**
 * Categories that display THE REAL professional trust layer.
 * All other categories use The Vibe (atmosphere) layer.
 * Source: "Layer Routing" sheet.
 *
 * Special case: Health & Wellness fitness subcategories
 * (Fitness & Gyms, Personal Trainers, Yoga & Pilates) use The Vibe.
 */
export const THE_REAL_CATEGORIES: string[] = [
  "Health & Wellness",
  "Legal & Government Services",
  "Financial & Business Services",
  "Professional Services",
  "Technology & Digital Services",
  "Home & Property Services",
  "Automotive & Transportation",
  "Pets & Animal Services",
  "Other Services",
  "Childcare & Early Education",
];

/**
 * Health & Wellness subcategories that use The VIBE (not THE REAL).
 * Movement/wellness experience exception per Layer Routing sheet.
 */
export const HEALTH_VIBE_SUBCATEGORIES: string[] = [
  "Fitness & Gyms",
  "Personal Trainers",
  "Yoga & Pilates",
];

/** Returns true if a business's category uses THE REAL layer */
export function usesTheReal(category: string, subcategory?: string): boolean {
  if (!THE_REAL_CATEGORIES.includes(category)) return false;
  if (category === "Health & Wellness" && subcategory &&
      HEALTH_VIBE_SUBCATEGORIES.includes(subcategory)) return false;
  return true;
}

/** Returns THE REAL tags for a given category */
export function getTheRealTagsForCategory(category: string): TheRealTag[] {
  return THE_REAL_CATEGORY_MAP[category] ?? [];
}
