import { Check, Loader2, Scissors } from "lucide-react";
import { useState } from "react";
import { authenticatedFetch } from "@/lib/authenticatedFetch";

const BASE = import.meta.env.BASE_URL;
const OPTIONS = [
  ["loc maintenance", "Loc maintenance"], ["starter locs", "Starter locs"], ["retwists", "Retwists"], ["microlocs", "Microlocs"],
  ["natural hair care", "Natural-hair care"], ["protective styles", "Braids / protective styles"], ["silk presses", "Silk presses"], ["wigs and installs", "Wigs / installs"], ["sew-ins", "Sew-ins"],
] as const;

export function HairServicePreferences() {
  const [selected, setSelected] = useState<string[]>([]); const [shampoo, setShampoo] = useState(false); const [detangling, setDetangling] = useState(false); const [noPrewash, setNoPrewash] = useState(false); const [consent, setConsent] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  function toggle(value: string) { setSelected((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function save() { if (!consent || selected.length === 0) return; setSaving(true); setMessage(null); const parts = [`For hair-service discovery, I prefer ${selected.join(", ")}.`]; if (shampoo) parts.push("I require shampoo to be included."); if (detangling) parts.push("I require detangling to be included."); if (noPrewash) parts.push("I will not book a stylist who requires pre-washed hair."); try { const response = await authenticatedFetch(`${BASE}api/kinfolk/memories`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: parts.join(" "), purpose: "profile_context", consent: true }) }); const body = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(body.error ?? "Could not save your service preferences."); setMessage(body.message ?? "Saved privately. Kinfolk will only use this for relevant hair-service searches."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save your service preferences."); } finally { setSaving(false); } }
  return <section className="rounded-2xl border border-[#3A1F0E]/10 bg-white p-5 sm:p-6"><div className="mb-5 flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#CA922B]/12"><Scissors className="h-5 w-5 text-[#CA922B]" /></div><div><h2 className="font-serif text-xl font-bold text-[#2B1507]">Hair-service preferences</h2><p className="mt-1 text-sm leading-5 text-[#3A1F0E]/65">Optional and private. Kinfolk uses only what you explicitly save to prioritize documented services during a relevant hair-service search. It never creates a public label or infers anything about you.</p></div></div><fieldset className="space-y-3"><legend className="text-sm font-bold text-[#2B1507]">Services you want Kinfolk to prioritize</legend><div className="grid gap-2 sm:grid-cols-2">{OPTIONS.map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-xl border border-[#3A1F0E]/10 px-3 py-2 text-sm"><input type="checkbox" checked={selected.includes(value)} onChange={() => toggle(value)} />{label}</label>)}</div></fieldset><fieldset className="mt-5 space-y-2"><legend className="text-sm font-bold text-[#2B1507]">Only show a verified match when the appointment includes</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={shampoo} onChange={(event) => setShampoo(event.target.checked)} />Shampoo</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={detangling} onChange={(event) => setDetangling(event.target.checked)} />Detangling</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={noPrewash} onChange={(event) => setNoPrewash(event.target.checked)} />Do not show a verified match that requires me to arrive pre-washed</label></fieldset><label className="mt-5 flex items-start gap-2 rounded-xl border border-[#CA922B]/20 bg-[#CA922B]/[0.06] p-3 text-xs leading-5 text-[#3A1F0E]/75"><input className="mt-1" type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} />I consent to Kinfolk saving these private preferences for my account. I can review, pause, edit, or delete them in Kinfolk Memory settings.</label><button type="button" disabled={saving || !consent || selected.length === 0} onClick={() => void save()} className="mt-4 inline-flex min-h-10 items-center justify-center gap-2 rounded-full bg-[#2B1507] px-5 text-sm font-bold text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}{saving ? "Saving…" : "Save private service preferences"}</button>{message && <p role="status" className="mt-3 text-sm font-medium text-[#6A3B1E]">{message}</p>}</section>;
}
