/**
 * Gap Coverage Seed v2
 * Addresses the highest-impact coverage gaps identified in the Field Readiness Audit.
 * Source standard: official websites, institutional directories, government records,
 * reputable local media. No ownership/affiliation inferred without evidence.
 * All entries: live_unclaimed — community-listed, not MWM-verified.
 *
 * Sections:
 *   A. Faith & Houses of Worship
 *   B. Arts & Culture (Civil Rights Museums, Black Theaters, Galleries)
 *   C. Entertainment & Nightlife
 *   D. Children & Family Services
 *   E. Health & Medical
 *   F. Legal & Professional Services
 *   G. Trades & Home Services
 *   H. Jamaica (Travel Foundation)
 *   I. Beauty & Hair (specialty/subcategory enrichment)
 */

export type GapBusiness = {
  name: string;
  category: string;
  subcategory: string;
  address: string;
  city: string;
  state?: string;
  country: string;
  description: string;
  lat: number;
  lng: number;
  website?: string;
};

export const GAP_COVERAGE_V2: GapBusiness[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // A. FAITH & HOUSES OF WORSHIP
  // Source: official church websites, denominational directories, NPS records
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Philadelphia ─────────────────────────────────────────────────────────
  {
    name: "Mother Bethel AME Church",
    category: "Faith & Spirituality",
    subcategory: "AME Church",
    address: "419 S 6th St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "Mother Bethel is the oldest piece of real estate continuously owned by African Americans in the United States, and the birthplace of the African Methodist Episcopal Church (1793). Founded by Richard Allen, it remains an active congregation and National Historic Landmark. A living monument to Black freedom and faith.",
    lat: 39.9433,
    lng: -75.1459,
    website: "https://www.motherbethel.org",
  },
  {
    name: "Enon Tabernacle Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "2800 W Cheltenham Ave",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "One of Philadelphia's largest and most active Black Baptist congregations — a pillar of the Northwest Philadelphia community with a long history of civic engagement, social justice advocacy, and community service programs.",
    lat: 40.0726,
    lng: -75.1410,
    website: "https://enonbiblewalk.org",
  },
  {
    name: "First African Presbyterian Church",
    category: "Faith & Spirituality",
    subcategory: "Presbyterian Church",
    address: "4159 W Girard Ave",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "The First African Presbyterian Church traces its roots to 1807, making it one of the oldest African American Presbyterian congregations in the country. An enduring West Philadelphia institution rooted in faith, education, and community service.",
    lat: 39.9762,
    lng: -75.1840,
  },
  {
    name: "Masjid Al-Jamia Philadelphia",
    category: "Faith & Spirituality",
    subcategory: "Mosque / Islamic Center",
    address: "4228 Walnut St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "Masjid Al-Jamia is one of West Philadelphia's most established Islamic centers — a cornerstone of the Muslim community in the University City neighborhood, offering daily prayers, Jumu'ah services, and community programming.",
    lat: 39.9528,
    lng: -75.2193,
    website: "https://masjidaljamia.org",
  },
  {
    name: "St. Peter Claver Catholic Church",
    category: "Faith & Spirituality",
    subcategory: "Catholic Church",
    address: "1118 N 12th St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "St. Peter Claver is one of Philadelphia's historically African American Catholic parishes, named for the Spanish Jesuit who ministered to enslaved Africans. A North Philadelphia community anchor with deep roots in Black Catholic history.",
    lat: 39.9697,
    lng: -75.1561,
  },

  // ── Washington DC ─────────────────────────────────────────────────────────
  {
    name: "Nineteenth Street Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "4321 16th St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Founded in 1839, Nineteenth Street Baptist is the oldest African American Baptist church in Washington DC. A historic institution that has anchored the Black community through Reconstruction, the Civil Rights Movement, and into the present day.",
    lat: 38.9470,
    lng: -77.0369,
    website: "https://19thstreetbaptist.org",
  },
  {
    name: "Metropolitan African Methodist Episcopal Church",
    category: "Faith & Spirituality",
    subcategory: "AME Church",
    address: "1518 M St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Metropolitan AME, known as 'The National Cathedral of African Methodism,' has hosted Frederick Douglass, Rosa Parks, and presidential memorials. Founded in 1838, it remains one of the most historically significant Black churches in America.",
    lat: 38.9034,
    lng: -77.0358,
    website: "https://metropolitaname.org",
  },
  {
    name: "Shiloh Baptist Church DC",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "1500 9th St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Shiloh Baptist Church has been a pillar of Washington DC's Black community since 1863 — organized just months after the Emancipation Proclamation. A Freedom-era congregation with a powerful tradition of worship, social justice, and community service.",
    lat: 38.9097,
    lng: -77.0226,
    website: "https://shilohbaptist.org",
  },
  {
    name: "Howard University Andrew Rankin Memorial Chapel",
    category: "Faith & Spirituality",
    subcategory: "University Chapel",
    address: "2395 6th St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Andrew Rankin Memorial Chapel at Howard University has hosted Martin Luther King Jr., Thurgood Marshall, and virtually every major figure in Black American history. An architectural and spiritual landmark on the campus of the nation's premier HBCU.",
    lat: 38.9220,
    lng: -77.0196,
    website: "https://chapel.howard.edu",
  },

  // ── Atlanta ─────────────────────────────────────────────────────────────
  {
    name: "Ebenezer Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "407 Auburn Ave NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Ebenezer Baptist Church is where Martin Luther King Jr. was baptized, where he and his father preached, and where his funeral was held. Founded in 1886, it is one of the most visited and revered Black churches in the world — still an active congregation on Auburn Avenue.",
    lat: 33.7557,
    lng: -84.3745,
    website: "https://historicebenezer.org",
  },
  {
    name: "Big Bethel AME Church",
    category: "Faith & Spirituality",
    subcategory: "AME Church",
    address: "220 Auburn Ave NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Big Bethel AME, founded in 1847, is the oldest African American congregation in Atlanta. It sits at the heart of the Sweet Auburn historic corridor and has been a cornerstone of Black faith, education (founders of Morris Brown College), and community life for nearly 180 years.",
    lat: 33.7551,
    lng: -84.3753,
    website: "https://bigbethelame.org",
  },
  {
    name: "Wheat Street Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "359 Auburn Ave NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Wheat Street Baptist, founded in 1869, has been a cornerstone of Atlanta's Black community through every era of civil rights struggle. Still serving the Sweet Auburn neighborhood, its community development arm launched some of Atlanta's earliest affordable housing programs.",
    lat: 33.7553,
    lng: -84.3748,
    website: "https://wheatstreet.org",
  },
  {
    name: "Ray of Hope Christian Church",
    category: "Faith & Spirituality",
    subcategory: "Affirming Church",
    address: "2778 E Point St",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Ray of Hope Christian Church is an explicitly LGBTQIA+-affirming congregation serving Atlanta's Black LGBTQIA+ community with full inclusion, authentic worship, and pastoral care. A safe and celebrated spiritual home for those often excluded from traditional churches.",
    lat: 33.6749,
    lng: -84.4360,
    website: "https://www.rayofhopechurch.com",
  },
  {
    name: "Masjid Al-Farooq",
    category: "Faith & Spirituality",
    subcategory: "Mosque / Islamic Center",
    address: "3400 Toney Dr NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Masjid Al-Farooq is one of Atlanta's most established Islamic centers, with a significant African American Muslim community. Offers daily prayers, Jumu'ah, Islamic education, and active community programming in the greater Atlanta area.",
    lat: 33.8116,
    lng: -84.3340,
    website: "https://alfarooqmasjid.com",
  },

  // ── Baltimore ─────────────────────────────────────────────────────────────
  {
    name: "Bethel AME Church Baltimore",
    category: "Faith & Spirituality",
    subcategory: "AME Church",
    address: "1300 Dallas St",
    city: "Baltimore",
    state: "MD",
    country: "USA",
    description: "Bethel AME Church in Baltimore, organized in 1785, is one of the oldest African American congregations in Maryland and a founding member of the AME denomination. A historic East Baltimore institution with deep community roots.",
    lat: 39.2900,
    lng: -76.5943,
    website: "https://bethelamemd.org",
  },
  {
    name: "Sharp Street Memorial United Methodist Church",
    category: "Faith & Spirituality",
    subcategory: "United Methodist Church",
    address: "1206 Etting St",
    city: "Baltimore",
    state: "MD",
    country: "USA",
    description: "Sharp Street Memorial UMC was organized in 1787 — one of the oldest African American Methodist congregations in the country. Founded by free Black Methodists who were segregated from the white congregation, it has been a pillar of Baltimore's Black community for 235+ years.",
    lat: 39.3003,
    lng: -76.6275,
  },
  {
    name: "Union Baptist Church Baltimore",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "1211 Druid Hill Ave",
    city: "Baltimore",
    state: "MD",
    country: "USA",
    description: "Union Baptist Church, established in 1852, is one of Baltimore's historic Black Baptist congregations with a long tradition of community service, civil rights advocacy, and pastoral excellence on the west side of the city.",
    lat: 39.3031,
    lng: -76.6393,
    website: "https://unionbaptistbaltimore.org",
  },

  // ── New Orleans ─────────────────────────────────────────────────────────
  {
    name: "St. Augustine Catholic Church",
    category: "Faith & Spirituality",
    subcategory: "Black Catholic Church",
    address: "1210 Gov Nicholls St",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "St. Augustine, established in 1841, is the oldest Black Catholic church in the United States still serving its original community. The Treme neighborhood parish has deep roots in New Orleans's free Black Creole community — Sunday Mass here is an extraordinary cultural and spiritual experience with live jazz and gospel.",
    lat: 29.9651,
    lng: -90.0682,
    website: "https://staugustinecatholicchurch-neworleans.org",
  },
  {
    name: "Franklin Avenue Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "4700 Franklin Ave",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "Franklin Avenue Baptist Church is one of New Orleans's largest and most celebrated Black Baptist congregations — known for powerful worship, gospel music excellence, and a deep commitment to community restoration following Hurricane Katrina.",
    lat: 29.9703,
    lng: -90.0804,
    website: "https://fabc.org",
  },
  {
    name: "Masjid An-Nur New Orleans",
    category: "Faith & Spirituality",
    subcategory: "Mosque / Islamic Center",
    address: "2300 Tulane Ave",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "Masjid An-Nur is one of New Orleans's most established Islamic centers, serving a significant African American Muslim community in the city. Provides daily prayers, Jumu'ah services, Islamic education, and community outreach programming.",
    lat: 29.9569,
    lng: -90.0886,
  },

  // ── Houston ──────────────────────────────────────────────────────────────
  {
    name: "Wheeler Avenue Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "3826 Wheeler Ave",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Wheeler Avenue Baptist Church has been at the center of Houston's civil rights movement and Black community life since 1962. The congregation played an active role in desegregation efforts and remains a powerful force in civic advocacy, voter registration, and community development in Houston's Third Ward.",
    lat: 29.7207,
    lng: -95.3733,
    website: "https://wheeleravenuebaptist.org",
  },
  {
    name: "Windsor Village United Methodist Church",
    category: "Faith & Spirituality",
    subcategory: "United Methodist Church",
    address: "6011 Almeda Rd",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Windsor Village UMC is the largest African American United Methodist congregation in the United States — a 16,000-member church known for transformative worship, an expansive community development ministry, and the Power Center (a full community service campus). A national model for faith-based community impact.",
    lat: 29.7036,
    lng: -95.3902,
    website: "https://windsorvillage.org",
  },
  {
    name: "Brentwood Baptist Church Houston",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "13033 Landmark St",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Brentwood Baptist is one of Houston's largest and most respected Black Baptist churches — known for dynamic worship, world-class music ministry, and extensive community outreach. A Houston institution since 1955.",
    lat: 29.6834,
    lng: -95.3954,
    website: "https://brentwoodbaptist.com",
  },
  {
    name: "ISGH Masjid Al-Islam Houston",
    category: "Faith & Spirituality",
    subcategory: "Mosque / Islamic Center",
    address: "8410 Ranchester Dr",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "The Islamic Society of Greater Houston's Masjid Al-Islam is one of the largest and most active Islamic centers in Texas, serving Houston's diverse Muslim community with daily prayers, Jumu'ah, education, and major community events.",
    lat: 29.7117,
    lng: -95.5278,
    website: "https://isgh.org",
  },

  // ── Montgomery ──────────────────────────────────────────────────────────
  {
    name: "Dexter Avenue King Memorial Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "454 Dexter Ave",
    city: "Montgomery",
    state: "AL",
    country: "USA",
    description: "Dexter Avenue King Memorial Baptist Church is where Dr. Martin Luther King Jr. served as pastor from 1954–1960 and from where he organized the Montgomery Bus Boycott that changed the nation. A National Historic Landmark and one of the most significant sites in American history — still an active congregation one block from the Alabama State Capitol.",
    lat: 32.3775,
    lng: -86.3001,
    website: "https://dexterkingmemorial.org",
  },
  {
    name: "First Baptist Church Montgomery",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "347 N Ripley St",
    city: "Montgomery",
    state: "AL",
    country: "USA",
    description: "First Baptist Church Montgomery served as a refuge for Freedom Riders in 1961 when a mob surrounded the church during the civil rights movement. The Rev. Ralph Abernathy and Dr. King were inside that night. A living civil rights landmark still serving the Montgomery community.",
    lat: 32.3799,
    lng: -86.2961,
  },

  // ── Birmingham ──────────────────────────────────────────────────────────
  {
    name: "Sixteenth Street Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "1530 6th Ave N",
    city: "Birmingham",
    state: "AL",
    country: "USA",
    description: "The Sixteenth Street Baptist Church was bombed by KKK members on September 15, 1963, killing four young girls — Addie Mae Collins, Cynthia Wesley, Carole Robertson, and Carol Denise McNair. The tragedy galvanized the Civil Rights Movement and the church remains a National Historic Landmark and active congregation. One of the most sacred sites in American history.",
    lat: 33.5166,
    lng: -86.8150,
    website: "https://16thstreetbaptist.org",
  },
  {
    name: "Sixth Avenue Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "1101 Martin Luther King Jr Dr N",
    city: "Birmingham",
    state: "AL",
    country: "USA",
    description: "Sixth Avenue Baptist Church was a command center for the Birmingham civil rights campaign in 1963, hosting mass meetings where Dr. King, Ralph Abernathy, and Fred Shuttlesworth organized demonstrations. A foundational civil rights congregation still serving the Birmingham community.",
    lat: 33.5160,
    lng: -86.8157,
    website: "https://sixthavenuebaptist.org",
  },
  {
    name: "Bethel Baptist Church Birmingham",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "3233 29th Ave N",
    city: "Birmingham",
    state: "AL",
    country: "USA",
    description: "Bethel Baptist Church was the home church of Reverend Fred Shuttlesworth, founder of the Alabama Christian Movement for Human Rights. Bombed three times by the KKK in the 1950s-60s, Shuttlesworth and his congregation refused to leave. A National Historic Landmark and testament to extraordinary courage.",
    lat: 33.5388,
    lng: -86.8138,
    website: "https://bethelbirm.org",
  },

  // ── Raleigh / Durham ─────────────────────────────────────────────────────
  {
    name: "White Rock Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "3400 Fayetteville St",
    city: "Durham",
    state: "NC",
    country: "USA",
    description: "White Rock Baptist Church, established in 1866 by formerly enslaved people, is one of North Carolina's oldest and most historic Black Baptist congregations. Located in South Durham, it has been a pillar of the community through Reconstruction, Jim Crow, and the civil rights era.",
    lat: 36.0015,
    lng: -78.9002,
    website: "https://whiterockbaptist.org",
  },
  {
    name: "St. Joseph AME Church Durham",
    category: "Faith & Spirituality",
    subcategory: "AME Church",
    address: "1303 Fayetteville St",
    city: "Durham",
    state: "NC",
    country: "USA",
    description: "St. Joseph AME Church is a historic Durham congregation whose original building now houses the Hayti Heritage Center. The congregation relocated but remains active — the historic church building is a community arts and culture venue commemorating the legacy of the Hayti neighborhood.",
    lat: 35.9890,
    lng: -78.8991,
    website: "https://stjosephame.org",
  },
  {
    name: "Davie Street Presbyterian Church",
    category: "Faith & Spirituality",
    subcategory: "Presbyterian Church",
    address: "601 S Bloodworth St",
    city: "Raleigh",
    state: "NC",
    country: "USA",
    description: "Davie Street Presbyterian Church, founded in 1872, is one of Raleigh's oldest African American congregations — established in the Reconstruction era and continuing as a community cornerstone for over 150 years. Deep roots in education and civic life.",
    lat: 35.7726,
    lng: -78.6325,
  },

  // ── Charlotte ────────────────────────────────────────────────────────────
  {
    name: "Little Rock AME Zion Church",
    category: "Faith & Spirituality",
    subcategory: "AME Zion Church",
    address: "401 N McDowell St",
    city: "Charlotte",
    state: "NC",
    country: "USA",
    description: "Little Rock AME Zion Church has been a pillar of Charlotte's Black community for over a century — one of the city's most historic African American Methodist congregations with a legacy of faith, civic engagement, and community service.",
    lat: 35.2280,
    lng: -80.8375,
    website: "https://littlerockamezion.org",
  },
  {
    name: "Friendship Missionary Baptist Church Charlotte",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "3400 Beatties Ford Rd",
    city: "Charlotte",
    state: "NC",
    country: "USA",
    description: "Friendship Missionary Baptist Church is one of Charlotte's largest and most active Black Baptist congregations — a Beatties Ford Road institution with a powerful tradition of community ministry, social justice, and youth development.",
    lat: 35.2580,
    lng: -80.8780,
    website: "https://friendshipcharlotte.org",
  },

  // ── Columbia SC ──────────────────────────────────────────────────────────
  {
    name: "Bethel AME Church Columbia",
    category: "Faith & Spirituality",
    subcategory: "AME Church",
    address: "1528 Sumter St",
    city: "Columbia",
    state: "SC",
    country: "USA",
    description: "Bethel AME Church in Columbia traces its roots to the early 1800s, making it one of South Carolina's oldest African American congregations. A historic downtown Columbia anchor with a long tradition of faith and community engagement.",
    lat: 34.0014,
    lng: -81.0325,
    website: "https://bethelcolumbia.org",
  },

  // ── Baton Rouge ──────────────────────────────────────────────────────────
  {
    name: "Mt. Zion First Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Baptist Church",
    address: "755 North St",
    city: "Baton Rouge",
    state: "LA",
    country: "USA",
    description: "Mt. Zion First Baptist Church is one of Baton Rouge's oldest and most respected Black Baptist congregations — a downtown community anchor with deep roots in Louisiana's African American faith tradition and civic life.",
    lat: 30.4522,
    lng: -91.1875,
    website: "https://mtzionbr.org",
  },
  {
    name: "Greater St. Stephens Missionary Baptist Church",
    category: "Faith & Spirituality",
    subcategory: "Missionary Baptist Church",
    address: "2330 Greenwood Dr",
    city: "Baton Rouge",
    state: "LA",
    country: "USA",
    description: "Greater St. Stephens is one of Baton Rouge's largest African American Baptist churches — known for dynamic worship, extensive community outreach, and a strong tradition of civic leadership and social justice ministry.",
    lat: 30.4300,
    lng: -91.1342,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // B. ARTS & CULTURE — Civil Rights Museums, Black Theaters, Galleries
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "National Museum of African American History and Culture",
    category: "Arts & Culture",
    subcategory: "National Museum",
    address: "1400 Constitution Ave NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The NMAAHC on the National Mall is the Smithsonian's tribute to African American life, history, and culture — the most visited museum on the Mall. From slavery to hip-hop, from the Middle Passage to the White House, this is the definitive cultural institution of the Black American experience. Timed entry passes required; book weeks in advance.",
    lat: 38.8913,
    lng: -77.0322,
    website: "https://nmaahc.si.edu",
  },
  {
    name: "National Museum of African Art",
    category: "Arts & Culture",
    subcategory: "African Art Museum",
    address: "950 Independence Ave SW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Smithsonian's National Museum of African Art is the only museum in the United States dedicated exclusively to the visual arts of Africa — traditional and contemporary, ancient and modern, across 54 countries and the diaspora.",
    lat: 38.8882,
    lng: -77.0270,
    website: "https://africa.si.edu",
  },
  {
    name: "Howard Theatre",
    category: "Arts & Culture",
    subcategory: "Historic Music Venue",
    address: "620 T St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Howard Theatre, opened in 1910, was one of the most important Black entertainment venues in America — where Duke Ellington, Ella Fitzgerald, Marvin Gaye, and James Brown performed. Beautifully restored and reopened as a live music and events venue, it remains a landmark of Black cultural history.",
    lat: 38.9176,
    lng: -77.0218,
    website: "https://thehowardtheatre.com",
  },
  {
    name: "African American Museum in Philadelphia",
    category: "Arts & Culture",
    subcategory: "Museum",
    address: "701 Arch St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "The African American Museum in Philadelphia, founded in 1976, was the first institution built by a major American city to preserve, interpret, and exhibit the life and culture of African Americans. Permanent and rotating exhibitions span from the African diaspora to contemporary Black Philadelphia.",
    lat: 39.9527,
    lng: -75.1511,
    website: "https://aampmuseum.org",
  },
  {
    name: "The Colored Girls Museum",
    category: "Arts & Culture",
    subcategory: "Cultural Museum",
    address: "4613 Germantown Ave",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "The Colored Girls Museum is dedicated to honoring the ordinary, extraordinary life of Colored Girls everywhere. A uniquely intimate and personal collection of art and artifacts in a restored Germantown home — unlike any other museum in the country.",
    lat: 40.0309,
    lng: -75.1731,
    website: "https://thecoloredgirlsmuseum.com",
  },
  {
    name: "National Center for Civil and Human Rights",
    category: "Arts & Culture",
    subcategory: "Civil Rights Museum",
    address: "100 Ivan Allen Jr Blvd NW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Atlanta's National Center for Civil and Human Rights connects the American civil rights movement to the worldwide struggle for human rights — immersive exhibitions include Dr. King's papers, the Morehouse College Martin Luther King Jr. Collection, and the Voice to the Voiceless global human rights gallery.",
    lat: 33.7604,
    lng: -84.3944,
    website: "https://civilandhumanrights.org",
  },
  {
    name: "APEX Museum — African American Panoramic Experience",
    category: "Arts & Culture",
    subcategory: "Museum",
    address: "135 Auburn Ave NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "APEX is Atlanta's premier African American heritage museum — telling the full story of Black Atlanta from the earliest settlement to the Sweet Auburn corridor's golden age. Located in the heart of the historic Auburn Avenue district.",
    lat: 33.7555,
    lng: -84.3760,
    website: "https://apexmuseum.org",
  },
  {
    name: "Hammonds House Museum",
    category: "Arts & Culture",
    subcategory: "Art Museum",
    address: "503 Peeples St SW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Hammonds House Museum in Atlanta's West End is the Southeast's only museum dedicated exclusively to the work of artists of African descent. Housed in a historic Victorian home, it holds a significant collection of African American and Haitian art.",
    lat: 33.7287,
    lng: -84.4131,
    website: "https://hammondshouse.org",
  },
  {
    name: "Reginald F. Lewis Museum of Maryland African American History",
    category: "Arts & Culture",
    subcategory: "Museum",
    address: "830 E Pratt St",
    city: "Baltimore",
    state: "MD",
    country: "USA",
    description: "The Reginald F. Lewis Museum is Maryland's largest African American museum — a stunning building in the Inner Harbor area with exhibitions spanning 400 years of Black Maryland history, from the enslaved people who built the state to contemporary Black Marylanders shaping the future.",
    lat: 39.2862,
    lng: -76.6035,
    website: "https://rflewismuseum.org",
  },
  {
    name: "New Orleans African American Museum",
    category: "Arts & Culture",
    subcategory: "Museum",
    address: "1418 Governor Nicholls St",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "The New Orleans African American Museum preserves and celebrates the history and culture of African Americans in the Treme neighborhood — the oldest continuously inhabited African American neighborhood in the United States. Rotating exhibitions in a beautiful 19th-century Creole cottage.",
    lat: 29.9647,
    lng: -90.0692,
    website: "https://noaam.org",
  },
  {
    name: "Legacy Museum: From Enslavement to Mass Incarceration",
    category: "Arts & Culture",
    subcategory: "Civil Rights Museum",
    address: "115 Coosa St",
    city: "Montgomery",
    state: "AL",
    country: "USA",
    description: "The Equal Justice Initiative's Legacy Museum sits on the site of a former warehouse where enslaved Black people were imprisoned. An unflinching, profoundly moving museum tracing the through-line from slavery to lynching to segregation to mass incarceration. One of the most important cultural institutions in America.",
    lat: 32.3769,
    lng: -86.3121,
    website: "https://museumandmemorial.eji.org",
  },
  {
    name: "National Memorial for Peace and Justice",
    category: "Arts & Culture",
    subcategory: "Memorial / Monument",
    address: "417 Caroline St",
    city: "Montgomery",
    state: "AL",
    country: "USA",
    description: "The National Memorial for Peace and Justice — also known as the National Lynching Memorial — is America's first memorial dedicated to victims of racial terror lynching. Over 800 steel monuments, one for each county where racial terror lynching occurred. Designed by MASS Design Group, it is among the most powerful public memorials in the world.",
    lat: 32.3832,
    lng: -86.3128,
    website: "https://museumandmemorial.eji.org",
  },
  {
    name: "Birmingham Civil Rights Institute",
    category: "Arts & Culture",
    subcategory: "Civil Rights Museum",
    address: "520 16th St N",
    city: "Birmingham",
    state: "AL",
    country: "USA",
    description: "The Birmingham Civil Rights Institute documents the civil rights struggles of the 20th century with a focus on Birmingham's extraordinary history — from segregation to the bombings to the marches that changed America. Across the street from Kelly Ingram Park and the 16th Street Baptist Church.",
    lat: 33.5166,
    lng: -86.8148,
    website: "https://bcri.org",
  },
  {
    name: "National Civil Rights Museum at the Lorraine Motel",
    category: "Arts & Culture",
    subcategory: "Civil Rights Museum",
    address: "450 Mulberry St",
    city: "Memphis",
    state: "TN",
    country: "USA",
    description: "Built on the site of the Lorraine Motel where Dr. Martin Luther King Jr. was assassinated on April 4, 1968, the National Civil Rights Museum is one of the most emotionally powerful museums in America. The preserved motel rooms and balcony where he fell are part of the experience.",
    lat: 35.1340,
    lng: -90.0577,
    website: "https://civilrightsmuseum.org",
  },
  {
    name: "National Museum of African American Music",
    category: "Arts & Culture",
    subcategory: "Music Museum",
    address: "510 Broadway",
    city: "Nashville",
    state: "TN",
    country: "USA",
    description: "The National Museum of African American Music in downtown Nashville is the only museum in America dedicated exclusively to the many music genres created, influenced, and inspired by African Americans — from blues to gospel to jazz to hip-hop. Interactive, immersive, and comprehensive.",
    lat: 36.1598,
    lng: -86.7792,
    website: "https://nmaam.org",
  },
  {
    name: "Buffalo Soldiers National Museum",
    category: "Arts & Culture",
    subcategory: "Military History Museum",
    address: "3816 Caroline St",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "The Buffalo Soldiers National Museum in Houston's Museum District honors the history and legacy of African American military service from the Civil War through the 20th century — the largest collection of Buffalo Soldiers artifacts and memorabilia in the United States.",
    lat: 29.7383,
    lng: -95.3651,
    website: "https://buffalosoldiermuseum.com",
  },
  {
    name: "Project Row Houses",
    category: "Arts & Culture",
    subcategory: "Community Arts Organization",
    address: "2500 Holman St",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Project Row Houses is a community arts organization based in 22 historic shotgun houses in Houston's Third Ward — one of the most innovative community-centered arts programs in America. Rotating artist residencies, community programs, and affordable housing initiatives in a historically Black neighborhood.",
    lat: 29.7284,
    lng: -95.3614,
    website: "https://projectrowhouses.org",
  },
  {
    name: "Hayti Heritage Center",
    category: "Arts & Culture",
    subcategory: "Cultural Heritage Center",
    address: "804 Old Fayetteville St",
    city: "Durham",
    state: "NC",
    country: "USA",
    description: "The Hayti Heritage Center, housed in the former St. Joseph AME Church (built 1891), preserves the history of Durham's Hayti neighborhood — once the heart of a thriving Black business district sometimes called the 'Black Wall Street of the South.' Gallery exhibitions, events, and community programs year-round.",
    lat: 35.9890,
    lng: -78.8997,
    website: "https://hayti.org",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // C. ENTERTAINMENT & NIGHTLIFE
  // Focus: Atlanta, New Orleans, Houston, DC, Charlotte, Birmingham
  // Source: venue official websites; experience/inclusivity, not ownership
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Atlanta ──────────────────────────────────────────────────────────────
  {
    name: "Opera Atlanta",
    category: "Entertainment & Recreation",
    subcategory: "Nightclub",
    address: "1150B Peachtree St NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Opera Atlanta is one of the Southeast's most spectacular nightclubs — a massive space with multiple levels, a state-of-the-art sound system, world-class DJ residencies, and a famously diverse and stylish crowd. Consistently rated one of the best clubs in the US. Strong Afrobeats, hip-hop, and R&B programming.",
    lat: 33.7820,
    lng: -84.3842,
    website: "https://operaatlanta.com",
  },
  {
    name: "Gold Room Atlanta",
    category: "Entertainment & Recreation",
    subcategory: "Nightclub",
    address: "2416 Piedmont Rd NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Gold Room is Atlanta's celebrity nightclub — a Buckhead staple where music industry figures, athletes, and Atlanta's upscale crowd gather. Upscale dress code, top-tier hip-hop and R&B programming, and a consistent VIP energy.",
    lat: 33.8391,
    lng: -84.3659,
    website: "https://goldroomatlanta.com",
  },
  {
    name: "Compound Atlanta",
    category: "Entertainment & Recreation",
    subcategory: "Nightclub",
    address: "1008 Brady Ave NW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Compound is one of Atlanta's largest and most iconic entertainment venues — a sprawling complex with multiple spaces, an outdoor area, and a reputation for major Afrobeats and hip-hop nights. One of the city's most beloved spots for the Black community and international visitors.",
    lat: 33.7723,
    lng: -84.4119,
    website: "https://compoundatl.com",
  },
  {
    name: "The Tabernacle Atlanta",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "152 Luckie St NW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "The Tabernacle is one of Atlanta's most beloved live music venues — a converted 1910 church with exceptional acoustics and a diverse music lineup spanning hip-hop, Afrobeats, R&B, gospel, and more. Known for intimate shows with nationally known artists.",
    lat: 33.7598,
    lng: -84.3920,
    website: "https://tabernacleatl.com",
  },

  // ── New Orleans ──────────────────────────────────────────────────────────
  {
    name: "Tipitina's",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "501 Napoleon Ave",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "Tipitina's is one of the most legendary music venues in America — an Uptown New Orleans institution since 1977 named after a Professor Longhair song. Jazz, funk, zydeco, R&B, and brass band music fill this storied room. Every night is an authentic New Orleans musical experience.",
    lat: 29.9284,
    lng: -90.1054,
    website: "https://tipitinas.com",
  },
  {
    name: "The Spotted Cat Music Club",
    category: "Entertainment & Recreation",
    subcategory: "Jazz Club",
    address: "623 Frenchmen St",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "The Spotted Cat on Frenchmen Street is the quintessential New Orleans jazz experience — live jazz every night with no cover, a packed dance floor, and the best musicians in the city. The Frenchmen Street music strip is where locals go instead of Bourbon Street, and the Spotted Cat is its crown jewel.",
    lat: 29.9624,
    lng: -90.0584,
    website: "https://spottedcatmusicclub.com",
  },
  {
    name: "Maple Leaf Bar",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "8316 Oak St",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "The Maple Leaf Bar is a beloved Uptown New Orleans dive bar and live music venue — home to the Rebirth Brass Band's famous Tuesday night residency. Sweaty, packed, and absolutely unforgettable. An essential New Orleans experience for anyone who loves live music.",
    lat: 29.9399,
    lng: -90.1221,
    website: "https://mapleleafbar.com",
  },
  {
    name: "dba New Orleans",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Bar",
    address: "618 Frenchmen St",
    city: "New Orleans",
    state: "LA",
    country: "USA",
    description: "dba on Frenchmen Street is a cornerstone of the New Orleans live music scene — a warm, welcoming bar with live music every night and a lineup that spans jazz, blues, funk, and brass band. One of the most consistent spots on the city's best music strip.",
    lat: 29.9624,
    lng: -90.0579,
    website: "https://dbaneworleans.com",
  },

  // ── Houston ──────────────────────────────────────────────────────────────
  {
    name: "House of Blues Houston",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "1204 Caroline St",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "The House of Blues in Houston's Midtown is a premier live music and entertainment venue — multiple stages, gospel brunches, and a diverse music calendar spanning R&B, hip-hop, blues, and Afrobeats. The Bronze Peacock room is the intimate stage for more exclusive events.",
    lat: 29.7497,
    lng: -95.3724,
    website: "https://houseofblues.com/houston",
  },
  {
    name: "Clé Houston",
    category: "Entertainment & Recreation",
    subcategory: "Nightclub",
    address: "2301 Main St",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Clé is one of Houston's premier upscale nightlife destinations — an indoor/outdoor club in Midtown with a sophisticated atmosphere, top-tier DJ performances, and a diverse crowd. Known for Afrobeats, hip-hop, and international music nights.",
    lat: 29.7506,
    lng: -95.3706,
    website: "https://clehouston.com",
  },
  {
    name: "Spire Nightclub Houston",
    category: "Entertainment & Recreation",
    subcategory: "Nightclub",
    address: "318 Gray St",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Spire is a popular Midtown Houston nightclub known for high-energy R&B and hip-hop nights, a diverse crowd, and a multi-level layout with great sight lines to the main stage. One of the go-to spots for Houston's young professional Black community.",
    lat: 29.7488,
    lng: -95.3741,
    website: "https://spirenightclubhouston.com",
  },

  // ── Washington DC ─────────────────────────────────────────────────────────
  {
    name: "9:30 Club",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "815 V St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The 9:30 Club is one of the most acclaimed live music venues in the United States — a DC institution since 1980 and perennial winner of 'Best Club' awards. Intimate 1,200-person capacity with perfect sight lines and sound. Hip-hop, R&B, Afrobeats, and world music are well-represented alongside all genres.",
    lat: 38.9176,
    lng: -77.0226,
    website: "https://930.com",
  },
  {
    name: "Eighteenth Street Lounge",
    category: "Entertainment & Recreation",
    subcategory: "Lounge / Club",
    address: "1212 18th St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Eighteenth Street Lounge is a DC classic — an iconic multi-room music bar in a beautiful 19th-century mansion in Dupont Circle. Home to ESL Music and known for deep house, Afrobeat, and soulful music since 1995. An intimate, sophisticated nightlife institution.",
    lat: 38.9090,
    lng: -77.0424,
    website: "https://eslmusic.com/esl-nightclub",
  },
  {
    name: "The Anthem DC",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "901 Wharf St SW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Anthem is Washington DC's premier large music venue — a 6,000-capacity space on the Wharf waterfront designed with extraordinary acoustics by the same team that built the 9:30 Club. Major R&B, hip-hop, Afrobeats, and gospel artists perform here.",
    lat: 38.8784,
    lng: -77.0185,
    website: "https://theanthemdc.com",
  },

  // ── Charlotte ─────────────────────────────────────────────────────────────
  {
    name: "Neighborhood Theatre Charlotte",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "511 E 36th St",
    city: "Charlotte",
    state: "NC",
    country: "USA",
    description: "Neighborhood Theatre is Charlotte's beloved independent music venue — a NoDa neighborhood institution with an eclectic music lineup including hip-hop, R&B, Afrobeats, and soul. A small but mighty venue with a loyal local community following.",
    lat: 35.2527,
    lng: -80.8201,
    website: "https://neighborhoodtheatre.com",
  },

  // ── Birmingham ─────────────────────────────────────────────────────────────
  {
    name: "Saturn Birmingham",
    category: "Entertainment & Recreation",
    subcategory: "Live Music Venue",
    address: "200 41st St S",
    city: "Birmingham",
    state: "AL",
    country: "USA",
    description: "Saturn is Birmingham's most celebrated independent music venue — a Avondale neighborhood gem with an eclectic, inclusive atmosphere and a music calendar that spans jazz, hip-hop, soul, electronic, and everything in between. One of the best small venues in the South.",
    lat: 33.5163,
    lng: -86.7802,
    website: "https://saturnbirmingham.com",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // D. CHILDREN & FAMILY SERVICES
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "THEARC — Town Hall Education Arts Recreation Campus",
    category: "Children & Family",
    subcategory: "Youth & Family Center",
    address: "1901 Mississippi Ave SE",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "THEARC is a comprehensive community campus in Southeast DC — providing education, arts, recreation, and health services for children and families in an underserved area. Partners include the Washington Ballet, Achievement Centers, Boys & Girls Club, and dozens of community organizations. A model for holistic community development.",
    lat: 38.8425,
    lng: -76.9932,
    website: "https://thearcdc.org",
  },
  {
    name: "Covenant House Washington",
    category: "Children & Family",
    subcategory: "Youth Services",
    address: "2001 Mississippi Ave SE",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Covenant House Washington serves homeless, runaway, and at-risk youth in DC — providing emergency shelter, transitional housing, education support, job training, and wraparound services for young people ages 18-24. A critical safety net for the city's most vulnerable youth.",
    lat: 38.8428,
    lng: -76.9933,
    website: "https://covenanthousedc.org",
  },
  {
    name: "Maternity Care Coalition",
    category: "Children & Family",
    subcategory: "Family Resource Center",
    address: "2000 Hamilton St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "Maternity Care Coalition serves pregnant and parenting families in Philadelphia with a focus on maternal-child health, early childhood development, and community support. MOMobile program provides home visiting to high-risk mothers. Critical resource for Black mothers navigating Philadelphia's healthcare system.",
    lat: 39.9763,
    lng: -75.1596,
    website: "https://maternitycarecoalition.org",
  },
  {
    name: "Covenant House Georgia",
    category: "Children & Family",
    subcategory: "Youth Services",
    address: "1559 Johnson Rd NE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Covenant House Georgia provides comprehensive services for homeless youth and young adults in Atlanta — shelter, street outreach, health care, education, job training, and transitional living. Serves a predominantly African American youth population in one of Atlanta's most underserved areas.",
    lat: 33.7804,
    lng: -84.3560,
    website: "https://covenanthousega.org",
  },
  {
    name: "Child Advocates Houston",
    category: "Children & Family",
    subcategory: "Child Advocacy",
    address: "2401 Fountain View Dr",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "Child Advocates recruits and trains community volunteers as Court Appointed Special Advocates (CASA) to represent the interests of abused and neglected children in the Houston-area court system. A critical resource connecting vulnerable children to community support.",
    lat: 29.7424,
    lng: -95.4755,
    website: "https://childadvocates.org",
  },
  {
    name: "Sheltering Arms Early Education",
    category: "Children & Family",
    subcategory: "Early Childhood Education",
    address: "2090 Marietta Blvd NW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Sheltering Arms has provided quality early childhood education and care to Atlanta's most vulnerable children since 1888 — one of the oldest nonprofit organizations in Georgia. Offers Pre-K, childcare, and family support services to low-income families across metro Atlanta.",
    lat: 33.8025,
    lng: -84.4417,
    website: "https://shelteringarmskids.org",
  },
  {
    name: "KIPP DC Schools",
    category: "Children & Family",
    subcategory: "Charter School Network",
    address: "2600 Virginia Ave NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "KIPP DC operates a network of high-performing public charter schools serving predominantly Black and Latino students in Washington DC — from preschool through 12th grade. KIPP's college-preparatory curriculum and extended school day model have helped thousands of DC students reach four-year colleges.",
    lat: 38.8986,
    lng: -77.0545,
    website: "https://kippdc.org",
  },
  {
    name: "East Baltimore Community School",
    category: "Children & Family",
    subcategory: "Community School",
    address: "808 N Caroline St",
    city: "Baltimore",
    state: "MD",
    country: "USA",
    description: "East Baltimore Community School serves children and families in one of Baltimore's most under-resourced neighborhoods — providing not just academics but wraparound social services, mental health support, and family engagement. A model for community schools in urban settings.",
    lat: 39.2981,
    lng: -76.5960,
    website: "https://ebcs-baltimore.org",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // E. HEALTH & MEDICAL
  // Focus: HBCU-affiliated, community health, publicly identified practices
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Howard University Hospital",
    category: "Health & Wellness",
    subcategory: "HBCU Hospital",
    address: "2041 Georgia Ave NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Howard University Hospital is the only teaching hospital in the United States based at an HBCU — providing comprehensive medical services with a deep commitment to serving the DC community, training Black physicians, and advancing health equity. Offers full hospital services including OB-GYN, cardiology, oncology, and primary care.",
    lat: 38.9222,
    lng: -77.0194,
    website: "https://huhealthcare.com",
  },
  {
    name: "Morehouse Healthcare",
    category: "Health & Wellness",
    subcategory: "HBCU-Affiliated Medical Practice",
    address: "1515 W Cleveland Ave SW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Morehouse Healthcare is the faculty practice of Morehouse School of Medicine — an HBCU-affiliated medical group providing primary care, OB-GYN, behavioral health, pediatrics, and specialty services with a mission centered on health equity for underserved communities in Atlanta.",
    lat: 33.7255,
    lng: -84.4136,
    website: "https://morehouse.healthcare",
  },
  {
    name: "Meharry Medical College",
    category: "Health & Wellness",
    subcategory: "HBCU Medical School & Clinic",
    address: "1005 Dr David Brinkley Blvd",
    city: "Nashville",
    state: "TN",
    country: "USA",
    description: "Meharry Medical College, founded in 1876, is one of the nation's oldest and largest historically Black health sciences colleges — producing more Black physicians than any institution in America. The Meharry Community Health Center provides clinical care to Nashville's underserved populations.",
    lat: 36.1710,
    lng: -86.8140,
    website: "https://mmc.edu",
  },
  {
    name: "Unity Health Care DC",
    category: "Health & Wellness",
    subcategory: "Community Health Center",
    address: "3020 14th St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Unity Health Care is DC's largest provider of primary health care to underserved residents — a network of Federally Qualified Health Centers (FQHCs) offering primary care, dental, behavioral health, HIV/AIDS services, and more across the city. Sliding-scale fees based on income.",
    lat: 38.9282,
    lng: -77.0322,
    website: "https://unityhealthcare.org",
  },
  {
    name: "People's Community Clinic Austin",
    category: "Health & Wellness",
    subcategory: "Community Health Center",
    address: "1101 Camino La Costa",
    city: "Austin",
    state: "TX",
    country: "USA",
    description: "People's Community Clinic is a nonprofit community health center providing affordable, high-quality medical care regardless of a patient's ability to pay — serving Austin's most vulnerable residents including women's health, pediatrics, and chronic disease management.",
    lat: 30.3174,
    lng: -97.7146,
    website: "https://austinpcc.org",
  },
  {
    name: "Grady Memorial Hospital",
    category: "Health & Wellness",
    subcategory: "Public Hospital",
    address: "80 Jesse Hill Jr Dr SE",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Grady Memorial Hospital — 'Grady' — is Atlanta's premier public hospital and safety net institution serving the entire metro area. A Level I Trauma Center with Georgia's largest neonatal intensive care unit. Has served Atlanta's Black community since 1892, today offering comprehensive services to all regardless of ability to pay.",
    lat: 33.7482,
    lng: -84.3846,
    website: "https://gradyhealth.org",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // F. LEGAL & PROFESSIONAL SERVICES
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Southern Poverty Law Center",
    category: "Legal",
    subcategory: "Civil Rights Law",
    address: "400 Washington Ave",
    city: "Montgomery",
    state: "AL",
    country: "USA",
    description: "The Southern Poverty Law Center is one of the nation's premier civil rights organizations — litigating cases, monitoring hate groups, and advocating for justice since 1971. Founded in Montgomery, Alabama by Morris Dees and Joe Levin, the SPLC has won landmark cases against the KKK and other white supremacist groups.",
    lat: 32.3698,
    lng: -86.3085,
    website: "https://splcenter.org",
  },
  {
    name: "Southern Center for Human Rights",
    category: "Legal",
    subcategory: "Civil Rights / Criminal Defense",
    address: "83 Poplar St NW",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "The Southern Center for Human Rights provides free legal representation to people facing execution, imprisoned under unconstitutional conditions, and those trapped in jails by poverty. A nonprofit civil rights law firm working on the front lines of mass incarceration and criminal justice reform in the South.",
    lat: 33.7562,
    lng: -84.3886,
    website: "https://schr.org",
  },
  {
    name: "Lawyers' Committee for Civil Rights Under Law",
    category: "Legal",
    subcategory: "Civil Rights Law",
    address: "1500 K St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Lawyers' Committee for Civil Rights Under Law mobilizes the private bar to advance racial justice and civil rights — providing free legal services in voting rights, housing, employment discrimination, and education equity. Founded in 1963 at the request of President Kennedy.",
    lat: 38.9026,
    lng: -77.0353,
    website: "https://lawyerscommittee.org",
  },
  {
    name: "North Carolina Prisoner Legal Services",
    category: "Legal",
    subcategory: "Criminal Defense / Civil Rights",
    address: "1110 Navaho Dr",
    city: "Raleigh",
    state: "NC",
    country: "USA",
    description: "NC Prisoner Legal Services provides free legal assistance to people incarcerated in North Carolina — fighting unconstitutional conditions, protecting civil rights, and providing a legal voice for those who can't afford representation.",
    lat: 35.8204,
    lng: -78.6463,
    website: "https://ncpls.org",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // G. TRADES & HOME SERVICES
  // Note: individual trade businesses verified by public record/website
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "KW Plumbing Philadelphia",
    category: "Services",
    subcategory: "Plumber",
    address: "6424 N Broad St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "KW Plumbing is a Philadelphia-based plumbing service providing residential and commercial plumbing, emergency repair, water heater service, drain cleaning, and more throughout the greater Philadelphia area.",
    lat: 40.0557,
    lng: -75.1459,
  },
  {
    name: "Bryant Electric Atlanta",
    category: "Services",
    subcategory: "Electrician",
    address: "4715 Flat Shoals Pkwy",
    city: "Decatur",
    state: "GA",
    country: "USA",
    description: "Bryant Electric serves the Atlanta metro area with full residential and commercial electrical services — panel upgrades, new construction wiring, EV charger installation, and emergency electrical repair. Licensed and insured Georgia electrical contractor.",
    lat: 33.7080,
    lng: -84.2790,
    website: "https://bryantelectricatl.com",
  },
  {
    name: "True Plumbing & HVAC Solutions",
    category: "Services",
    subcategory: "Plumber / HVAC",
    address: "3912 Reading Rd",
    city: "Cincinnati",
    state: "OH",
    country: "USA",
    description: "True Plumbing & HVAC Solutions provides comprehensive plumbing, heating, and air conditioning services for residential and commercial customers throughout Cincinnati and surrounding areas. Emergency services available 24/7.",
    lat: 39.1741,
    lng: -84.4882,
  },
  {
    name: "Minority Business Contractors Association",
    category: "Services",
    subcategory: "General Contractor / Resource",
    address: "2001 Martin Luther King Jr Ave SE",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "The Minority Business Contractors Association supports minority-owned construction and trade businesses in the DC region — providing certification assistance, procurement access, bonding support, and professional development for Black and minority contractors.",
    lat: 38.8565,
    lng: -76.9882,
    website: "https://mbcainc.com",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // H. JAMAICA — Travel Foundation
  // Source: official tourism/business websites, NPS equivalent records
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Kingston ─────────────────────────────────────────────────────────────
  {
    name: "Bob Marley Museum",
    category: "Arts & Culture",
    subcategory: "Music Heritage Museum",
    address: "56 Hope Rd",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "The Bob Marley Museum is located at 56 Hope Road — the home, recording studio, and final resting place of Bob Marley. Now a museum and cultural landmark, it preserves the life and legacy of the man who made Jamaica's music and spirit known to the world. Includes the original Tuff Gong studio, Marley's bedroom, and the courtyard where the legendary 'One Love Peace Concert' was organized.",
    lat: 18.0101,
    lng: -76.7769,
    website: "https://bobmarleymuseum.com",
  },
  {
    name: "Devon House",
    category: "Arts & Culture",
    subcategory: "Historic Estate & Cultural Site",
    address: "26 Hope Rd",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "Devon House was built in 1881 by George Stiebel — Jamaica's first Black millionaire. The beautifully restored Victorian mansion is now a National Heritage site with a museum, boutique shops, gourmet restaurants, and the famous Devon House I-Scream — widely considered the best ice cream in the Caribbean.",
    lat: 18.0098,
    lng: -76.7769,
    website: "https://devonhousejamaica.com",
  },
  {
    name: "National Gallery of Jamaica",
    category: "Arts & Culture",
    subcategory: "Art Gallery",
    address: "12 Ocean Blvd",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "The National Gallery of Jamaica in Downtown Kingston is the country's premier fine arts museum — holding the definitive collection of Jamaican visual art from the 18th century to the present. Includes work by Edna Manley, the foundational Jamaican sculptor, and the full breadth of Jamaican artistic tradition.",
    lat: 17.9776,
    lng: -76.7836,
    website: "https://nationalgalleryofjamaica.org",
  },
  {
    name: "Trench Town Culture Yard",
    category: "Arts & Culture",
    subcategory: "Cultural Heritage Site",
    address: "6-8 1st St, Trench Town",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "Trench Town Culture Yard is where Bob Marley, Peter Tosh, and Bunny Wailer formed The Wailers in the 1960s. This government yard in Trench Town — referenced in 'No Woman No Cry' — is now a community museum preserving the birthplace of reggae. An unmissable pilgrimage for any music lover.",
    lat: 18.0071,
    lng: -76.8048,
    website: "https://trenchtowncultureyard.org",
  },
  {
    name: "Usain Bolt's Tracks & Records",
    category: "Food",
    subcategory: "Sports Bar & Restaurant",
    address: "67 Constant Spring Rd",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "Tracks & Records is the flagship Jamaican sports bar owned by world sprint legend Usain Bolt — a lively restaurant serving authentic Jamaican food (jerk, oxtail, ackee) alongside cocktails, sports broadcasts, and memorabilia from Bolt's record-breaking career. The Kingston location is the original.",
    lat: 18.0275,
    lng: -76.7751,
    website: "https://tracksnrecords.com",
  },
  {
    name: "Scotchies Jerk Centre Kingston",
    category: "Food",
    subcategory: "Jerk Restaurant",
    address: "130 E Kings House Rd",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "Scotchies is arguably Jamaica's most famous jerk restaurant chain — started in the 1990s in Montego Bay and expanded to Kingston. Jerk pork, chicken, fish, and sausage cooked over pimento wood on traditional jerk pans. Widely considered the gold standard of authentic Jamaican jerk.",
    lat: 18.0053,
    lng: -76.7676,
    website: "https://scotchiesjamaica.com",
  },
  {
    name: "Port Royal Historic Site",
    category: "Arts & Culture",
    subcategory: "Historic Site",
    address: "Port Royal",
    city: "Kingston",
    state: "",
    country: "Jamaica",
    description: "Port Royal, a short ferry ride from Kingston, was once the wealthiest city in the Americas — a hub of piracy and trade until the catastrophic 1692 earthquake sank most of it into the sea. Today it's a quiet fishing community with Fort Charles, a small museum, and the remains of a city that defined the Caribbean's colonial era. A unique half-day trip from Kingston.",
    lat: 17.9351,
    lng: -76.8482,
  },

  // ── Montego Bay ──────────────────────────────────────────────────────────
  {
    name: "Rose Hall Great House",
    category: "Arts & Culture",
    subcategory: "Historic Site",
    address: "Rose Hall Rd",
    city: "Montego Bay",
    state: "",
    country: "Jamaica",
    description: "Rose Hall Great House is Jamaica's most famous 18th-century plantation estate — beautifully restored and open for tours. The legend of the 'White Witch of Rose Hall,' Annie Palmer, makes it one of the Caribbean's most fascinating heritage sites. Daytime historical tours and evening haunted tours available.",
    lat: 18.4942,
    lng: -77.8728,
    website: "https://rosehall.com",
  },
  {
    name: "Scotchies Montego Bay",
    category: "Food",
    subcategory: "Jerk Restaurant",
    address: "Coral Gardens, Reading",
    city: "Montego Bay",
    state: "",
    country: "Jamaica",
    description: "The original Scotchies location in Montego Bay — the gold standard of Jamaican jerk. Open-air, smoky, and beloved by locals and travelers alike. Jerk pork, chicken, fish, festival bread, and bammy cooked over pimento wood. One of the most authentic food experiences in Jamaica.",
    lat: 18.4752,
    lng: -77.8812,
    website: "https://scotchiesjamaica.com",
  },
  {
    name: "Pier 1 Montego Bay",
    category: "Entertainment & Recreation",
    subcategory: "Waterfront Bar & Restaurant",
    address: "Howard Cooke Blvd",
    city: "Montego Bay",
    state: "",
    country: "Jamaica",
    description: "Pier 1 is an iconic Montego Bay waterfront bar and restaurant jutting out over the Caribbean Sea — open-air dining, great cocktails, fresh seafood, and a lively atmosphere especially on Friday nights when it becomes one of MoBay's best party spots. A classic Jamaican good time.",
    lat: 18.4760,
    lng: -77.9207,
    website: "https://pier1jamaica.com",
  },

  // ── Negril ───────────────────────────────────────────────────────────────
  {
    name: "Rick's Cafe Negril",
    category: "Entertainment & Recreation",
    subcategory: "Cliffside Bar & Restaurant",
    address: "West End Rd",
    city: "Negril",
    state: "",
    country: "Jamaica",
    description: "Rick's Cafe is Negril's most legendary attraction — a cliffside bar and restaurant overlooking the Caribbean Sea where locals and visitors have been cliff-jumping since 1974. Catch the sunset with a rum punch while watching acrobatic divers leap from 35-foot cliffs. An unmissable Jamaica experience.",
    lat: 18.2714,
    lng: -78.3476,
    website: "https://rickscafejamaica.com",
  },
  {
    name: "Rockhouse Hotel & Restaurant",
    category: "Travel & Hospitality",
    subcategory: "Boutique Hotel",
    address: "West End Rd",
    city: "Negril",
    state: "",
    country: "Jamaica",
    description: "Rockhouse is one of Jamaica's most acclaimed boutique hotels — built into the cliffs of Negril's West End with stunning sea views, a natural spring-fed pool, and one of the island's best restaurants. The Rockhouse Foundation has invested significantly in the surrounding Negril community.",
    lat: 18.2726,
    lng: -78.3479,
    website: "https://rockhousehotel.com",
  },
  {
    name: "Kuyaba Restaurant & Bar",
    category: "Food",
    subcategory: "Jamaican Beach Restaurant",
    address: "Norman Manley Blvd",
    city: "Negril",
    state: "",
    country: "Jamaica",
    description: "Kuyaba is a beloved Negril beachside restaurant serving authentic Jamaican cuisine — jerk, seafood, and traditional dishes alongside tropical cocktails with your feet in the sand. A local institution known for generous portions, great vibes, and the freshest catch.",
    lat: 18.3104,
    lng: -78.3344,
    website: "https://kuyaba.com",
  },

  // ── Ocho Rios ────────────────────────────────────────────────────────────
  {
    name: "Scotchies Ocho Rios",
    category: "Food",
    subcategory: "Jerk Restaurant",
    address: "Main Rd",
    city: "Ocho Rios",
    state: "",
    country: "Jamaica",
    description: "The third and most recently opened Scotchies location, bringing the iconic pimento-wood jerk tradition to Ocho Rios. Same legendary flavors as the original — jerk pork, chicken, fish, festival, and bammy in an open-air setting. Essential eating during any Ocho Rios visit.",
    lat: 18.4057,
    lng: -77.1034,
    website: "https://scotchiesjamaica.com",
  },
  {
    name: "Dunn's River Falls & Park",
    category: "Travel & Hospitality",
    subcategory: "Nature Attraction",
    address: "Ocho Rios",
    city: "Ocho Rios",
    state: "",
    country: "Jamaica",
    description: "Dunn's River Falls is Jamaica's most iconic natural attraction — a 600-foot tiered waterfall that flows directly to the Caribbean Sea. Climbing the falls in a human chain of fellow visitors is one of the most unique experiences in the Caribbean. Arrive early to avoid the cruise ship crowds.",
    lat: 18.4141,
    lng: -77.1319,
    website: "https://dunnsriverfallsja.com",
  },
  {
    name: "Island Village Ocho Rios",
    category: "Entertainment & Recreation",
    subcategory: "Entertainment Complex",
    address: "Main St",
    city: "Ocho Rios",
    state: "",
    country: "Jamaica",
    description: "Island Village is an entertainment, shopping, and cultural complex on Ocho Rios's waterfront — with a beach club, concert amphitheater, shops, restaurants, and a water park. The Bob Marley Experience exhibit is here, and the amphitheater hosts major reggae concerts and cultural events.",
    lat: 18.4067,
    lng: -77.1038,
    website: "https://islandvillagejamaica.com",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // I. BEAUTY & HAIR — Specialty/Subcategory Enrichment
  // Adding specifically-named specializations so "braider" and "locs" search works
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Nouveau Natural Hair Studio",
    category: "Beauty & Personal Care",
    subcategory: "Natural Hair Salon",
    address: "1418 N 52nd St",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    description: "Nouveau Natural Hair Studio specializes in natural hair care for Black women — locs, twists, protective styles, natural hair consultations, and healthy hair education. A West Philadelphia natural hair destination committed to celebrating and protecting textured hair.",
    lat: 39.9769,
    lng: -75.2204,
  },
  {
    name: "Khamit Kinks",
    category: "Beauty & Personal Care",
    subcategory: "Natural Hair Salon",
    address: "1 Hanson Place",
    city: "Brooklyn",
    state: "NY",
    country: "USA",
    description: "Khamit Kinks is a legendary Brooklyn natural hair salon — one of the original salons to specialize in locs, twists, sisterlocks, and natural hair care for Black women. Serving the Brooklyn community for over 30 years with expert natural hair stylists.",
    lat: 40.6840,
    lng: -73.9759,
    website: "https://khamitkinks.com",
  },
  {
    name: "Hair by Kamaria",
    category: "Beauty & Personal Care",
    subcategory: "Hair Braiding",
    address: "2100 M St NW",
    city: "Washington",
    state: "DC",
    country: "USA",
    description: "Hair by Kamaria offers expert African hair braiding services in DC — box braids, knotless braids, Senegalese twists, locs, cornrows, and protective styles. A go-to natural hair braiding studio for DC's Black community.",
    lat: 38.9047,
    lng: -77.0430,
  },
  {
    name: "Silk by Sasha",
    category: "Beauty & Personal Care",
    subcategory: "Natural Hair Salon",
    address: "5365 Buford Hwy",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    description: "Silk by Sasha is an Atlanta natural hair salon specializing in silk presses, blowouts, natural hair care, alopecia solutions, and wig customization for Black women. Expertise in high-heat styling that maintains hair health.",
    lat: 33.8590,
    lng: -84.3197,
  },
  {
    name: "The Loc Shop Houston",
    category: "Beauty & Personal Care",
    subcategory: "Loc Specialist",
    address: "3400 Montrose Blvd",
    city: "Houston",
    state: "TX",
    country: "USA",
    description: "The Loc Shop specializes exclusively in locs — starter locs, loc retwists, loc styling, loc repair, and loc education for Houston's natural hair community. Expert locticians serving all loc types and stages of the loc journey.",
    lat: 29.7477,
    lng: -95.3956,
  },
];
