/**
 * Phuket Knowledge Topics — v1
 *
 * 14 travel & cultural knowledge topics covering Phuket, Thailand, and the
 * broader Andaman region. Seeded via ensureKnowledgeTopics() which deduplicates
 * by lower-cased topic_name — safe to run on every boot.
 *
 * All topics: category = "travel", notificationPriority = "digest".
 */

import type { KnowledgeTopicSeed } from "../../data/knowledge-library-seed.js";

export const PHUKET_KNOWLEDGE_TOPICS_V1: KnowledgeTopicSeed[] = [
  {
    topicName: "Phuket History & Culture",
    category: "travel",
    description: `Phuket's cultural complexity is the product of 2,000 years of layered civilizations: Srivijayan maritime empire, Malay Muslim sultanates, Hokkien Chinese tin miners, British colonial influence through Penang, and the Thai royal state. The island's Peranakan (Baba-Nyonya) culture — born from Chinese-Malay intermarriage during the tin mining era — produced the Sino-Portuguese architecture, vegetarian festival, and fusion cuisine that make Phuket culturally distinct from anywhere else in Southeast Asia. Understanding this history transforms every beach, temple, and street market from a backdrop into a living document.`,
    keywords: [
      "Phuket history",
      "Peranakan culture Phuket",
      "Sino-Portuguese Old Phuket Town",
      "tin mining Thailand",
      "Srivijayan empire Andaman",
      "Phuket temples",
      "Thai Chinese heritage",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Thalang National Museum", domain: "thalangmuseum.go.th" },
      { name: "The Nation Thailand", domain: "nationthailand.com" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
    ],
  },
  {
    topicName: "Thai Buddhism for Travelers",
    category: "travel",
    description: `Theravada Buddhism is the living spiritual foundation of Thai society — not a tourist attraction but a 2,500-year-old tradition practiced daily by monks who wake before dawn, receive alms from the community at sunrise, and maintain the moral teachings that structure Thai family and civic life. Travelers who understand basic Buddhist concepts (merit-making, the wai gesture, the significance of the saffron robe, the role of the temple in community life) navigate Thai culture with far greater depth and receive far warmer reception from local communities. Dress codes at temples (covered shoulders and knees) are expressions of respect for a living faith, not bureaucratic rules.`,
    keywords: [
      "Thai Buddhism temples",
      "Theravada Buddhism Southeast Asia",
      "monk alms giving Thailand",
      "wai gesture respect",
      "merit making Thailand",
      "Buddhist temple etiquette",
      "wat Phuket",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Access to Insight — Theravada Buddhism", domain: "accesstoinsight.org" },
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Dhamma Wheel Buddhist Forum", domain: "dhammawheel.com" },
    ],
  },
  {
    topicName: "Phuket Vegetarian Festival",
    category: "travel",
    description: `The Phuket Vegetarian Festival (held each October–November for 9 days on the Chinese lunar calendar) is one of the most extraordinary religious events in Asia — a 200-year-old Taoist-Buddhist ceremony in which devotees believed to be possessed by deity gods (Ma Song) walk through fire and pierce their bodies with swords and skewers, apparently without pain, while the entire Thai-Chinese community observes strict vegetarian abstinence, dresses in white, and transforms Phuket Town into a city of incense and prayer. The festival was born in 1825 when a Chinese opera troupe's purification ceremonies ended an epidemic, and the grateful community adopted the practice permanently. It is simultaneously a profound religious experience and one of the most visually overwhelming spectacles available to any traveler — and the food alone (the vegetarian street market of Phuket Town during festival week) is worth the journey.`,
    keywords: [
      "Phuket Vegetarian Festival",
      "Nine Emperor Gods Festival",
      "Ma Song body piercing",
      "Jui Tui Shrine Phuket",
      "Thai Chinese festivals",
      "October festivals Thailand",
      "Taoist ceremonies Phuket",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Coconut Phuket", domain: "coconutphuket.com" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
    ],
  },
  {
    topicName: "Peranakan (Baba-Nyonya) Culture",
    category: "travel",
    description: `The Peranakan (Baba-Nyonya) culture — born from marriages between Hokkien Chinese traders and local Malay women across the Straits of Malacca region over the 17th–19th centuries — is one of the most distinctive hybrid cultures in Asia, present today in Phuket, Penang, Malacca, and Singapore. It produced a unique architectural style (Sino-Portuguese shophouses), a cuisine (nyonya cooking) that fuses Chinese techniques with Malay spices and ingredients, a distinctive dress tradition (the kebaya blouse paired with batik sarong), and a social identity that navigates between Chinese, Malay, and colonial European influences without fully belonging to any. Old Phuket Town, Penang's George Town, and Malacca's Jonker Street are the three best-preserved Peranakan urban environments in the world.`,
    keywords: [
      "Peranakan culture Phuket",
      "Baba Nyonya heritage",
      "Sino-Portuguese architecture",
      "nyonya cuisine Thailand",
      "Old Phuket Town heritage",
      "George Town Penang culture",
      "Chinese Malaysian culture",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Peranakan Museum Singapore", domain: "nhb.gov.sg" },
      { name: "Penang Global Tourism", domain: "visitpenang.gov.my" },
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Straits Times", domain: "straitstimes.com" },
    ],
  },
  {
    topicName: "Moken Sea Gypsy Heritage",
    category: "travel",
    description: `The Moken peoples — including the Urak Lawoi of Phuket and the broader Moken and Badjao communities across the Andaman Sea — have navigated these waters for at least 5,000 years, developing one of the most sophisticated maritime knowledge systems in human history without written instruments: reading currents, stars, tides, and animal behavior to navigate archipelagos with extraordinary precision. Their 2004 tsunami survival story — in which elders' traditional ecological knowledge allowed communities to reach high ground before the wave struck — made international news and prompted scientific study of indigenous environmental knowledge systems. The Urak Lawoi community at Rawai, Phuket is currently engaged in legal battles to protect their ancestral fishing waters and burial grounds from resort development, making this a living social justice issue rather than a heritage curiosity.`,
    keywords: [
      "Moken sea gypsies Thailand",
      "Urak Lawoi Phuket",
      "indigenous maritime cultures Andaman",
      "sea nomads Southeast Asia",
      "Moken tsunami survival",
      "Rawai village Phuket",
      "indigenous fishing rights Thailand",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "UNESCO Intangible Cultural Heritage", domain: "ich.unesco.org" },
      { name: "Survival International", domain: "survivalinternational.org" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
    ],
  },
  {
    topicName: "Andaman Sea Ecology & Travel",
    category: "travel",
    description: `The Andaman Sea is one of the world's most biodiverse marine environments — more species of reef fish per square kilometer than the Caribbean — sitting at the evolutionary boundary between the Indian Ocean and Pacific zones, where species from both oceans overlap. Dive sites around Phuket (Shark Point, King Cruiser wreck, Anemone Reef) and the Similan Islands National Park rank among the world's top ten; whale sharks seasonally visit between February and April. The 2004 tsunami's ecological impact, ongoing threats from rising ocean temperatures and tourism pressure, and the community conservation projects led by Buddhist temples and Malay fishing communities together make the Andaman a case study in the politics of paradise preservation.`,
    keywords: [
      "Andaman Sea diving Phuket",
      "Similan Islands snorkeling",
      "whale sharks Thailand",
      "coral reefs Phuket",
      "Phi Phi Islands marine park",
      "Phang Nga Bay ecology",
      "sustainable ocean travel Thailand",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "PADI Dive Travel", domain: "padi.com" },
      { name: "Thai National Parks", domain: "thainationalparks.com" },
      { name: "Reef Check Foundation", domain: "reefcheck.org" },
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
    ],
  },
  {
    topicName: "Thai Cuisine & Food Culture",
    category: "travel",
    description: `Thai cuisine is one of the world's great food traditions — a sophisticated balance of five flavors (sweet, salty, sour, bitter, spicy) shaped by centuries of Chinese, Malay, Indian, and Portuguese culinary influence layered onto indigenous agricultural and fishing traditions. Southern Thai cooking (the regional cuisine of Phuket and the Andaman coast) is distinctively more influenced by Malay and Indian spices than central Thai cooking, producing curries, coconut milk dishes, and street foods that have no equivalent elsewhere in the country. Understanding the food's cultural architecture — which dishes come from Chinese migrants, which from the Muslim fishing communities, which from the royal palace tradition — transforms eating from a pleasure into a cultural conversation with 500 years of history.`,
    keywords: [
      "Thai cuisine guide",
      "southern Thailand food culture",
      "Phuket street food",
      "Thai cooking traditions",
      "massaman curry history",
      "night market Thailand food",
      "Thai food cultural history",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Bangkok Post Food", domain: "bangkokpost.com" },
      { name: "Coconut Phuket", domain: "coconutphuket.com" },
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Michelin Guide Thailand", domain: "guide.michelin.com" },
    ],
  },
  {
    topicName: "Thai Massage & Wellness Traditions",
    category: "travel",
    description: `Thai massage (nuat thai) is a 2,500-year-old therapeutic system attributed to Jivaka Kumar Bhaccha — a physician described in Pali canon texts as the personal doctor of the Buddha — that combines acupressure, assisted yoga stretching, and rhythmic compression along energy lines (sen) to relieve tension, improve circulation, and restore the body's natural energy balance. The system was codified and preserved at Wat Pho in Bangkok (where the temple still operates a massage school) and has been practiced continuously within Thai Buddhist culture as both a healing art and an act of metta (loving-kindness). Thailand's wellness industry — spa tourism representing one of the country's largest tourism revenue streams — is built on this authentic tradition; understanding the difference between traditional nuad boran massage and commercialized adaptations helps travelers access the genuine cultural experience.`,
    keywords: [
      "Thai massage tradition",
      "nuad thai wellness",
      "Wat Pho massage school Bangkok",
      "Thai spa cultural history",
      "traditional Thai healing",
      "Phuket wellness tourism",
      "therapeutic massage Southeast Asia",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "UNESCO Intangible Cultural Heritage", domain: "ich.unesco.org" },
      { name: "Wat Pho Traditional Medical School", domain: "watpho.com" },
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
    ],
  },
  {
    topicName: "Muay Thai History & Culture",
    category: "travel",
    description: `Muay Thai (the art of eight limbs — fists, elbows, knees, and shins) is Thailand's national sport and martial art, developed over 600 years as a military combat system for the Siamese army and codified into a ceremonial sport tradition by the 18th century; the Wai Kru Ram Muay ceremony performed before every fight — a slow, meditative dance honoring the fighter's teachers, ancestors, and the spirit of the art — is one of the most beautiful ritual performances in any martial tradition. The headband (mongkon) worn during the Wai Kru was traditionally blessed by the fighter's teacher and carried into battle; the armband (prajioud) was torn from the fighter's mother's garment and worn as protection. Phuket is one of the world's great centers of Muay Thai training, with dozens of camps training fighters from across the world; stadium fights at Patong Boxing Stadium and Bangla Boxing Stadium run most evenings and are genuine cultural events rather than tourist shows.`,
    keywords: [
      "Muay Thai history Thailand",
      "Phuket Muay Thai training",
      "Thai boxing culture",
      "Wai Kru ceremony Muay Thai",
      "Patong Boxing Stadium",
      "martial arts Southeast Asia",
      "Muay Thai camps Phuket",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "World Muay Thai Federation", domain: "wmtf.net" },
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Muay Thai Authority of Thailand", domain: "muaythaiauthority.com" },
    ],
  },
  {
    topicName: "Songkran (Thai New Year) Festival",
    category: "travel",
    description: `Songkran — the Thai New Year celebrated on April 13–15 — is the world's largest water fight, but beneath the joyful chaos of millions of people dousing each other with buckets and water guns is one of the oldest and most culturally complex renewal ceremonies in Southeast Asia: the water symbolizes the washing away of bad luck, sins, and the troubles of the past year, drawn from the Sanskrit concept of purification that arrived in Thailand with Buddhism and Hinduism from India 1,500 years ago. The traditional Songkran involved the gentle pouring of scented water over the hands of elders as an act of respect and blessing — a practice still observed in temples and family gatherings while the streets become a national carnival. Chiang Mai's moat-side Songkran celebration and Bangkok's Silom Road festivities are the most famous, but Phuket's Patong Beach Songkran — where the entire beach strip becomes a multi-day water battle — draws tens of thousands of international travelers each April.`,
    keywords: [
      "Songkran Thai New Year",
      "Phuket water festival April",
      "Thai New Year traditions",
      "Songkran cultural meaning",
      "Thailand April festivals",
      "water festival Southeast Asia",
      "Buddhist New Year Thailand",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
      { name: "UNESCO Thailand", domain: "unescobkk.org" },
    ],
  },
  {
    topicName: "Loy Krathong Festival",
    category: "travel",
    description: `Loy Krathong — held on the full moon of the 12th lunar month (typically November) — is one of the most visually beautiful festivals in the world: across Thailand, thousands of people release small lotus-shaped boats (krathong) made of banana leaves, flowers, incense, and candles onto rivers, lakes, and the sea, offering gratitude to the water goddess Mae Khongkha and releasing the troubles of the year into the current. In Chiang Mai, Loy Krathong is celebrated simultaneously with the Yi Peng lantern festival, in which thousands of paper lanterns are released into the night sky — creating a sight that has no equivalent anywhere else on earth. In Phuket, the festival is celebrated at Nai Harn Lake and along the coast; watching thousands of candlelit boats drift out toward the Andaman horizon while lanterns rise into the sky above them is an experience of collective human beauty that is genuinely difficult to describe.`,
    keywords: [
      "Loy Krathong festival Thailand",
      "Yi Peng lantern festival",
      "Phuket Loy Krathong November",
      "Thai full moon festivals",
      "krathong traditions Thailand",
      "Buddhist festivals Southeast Asia",
      "Chiang Mai lantern festival",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
      { name: "Chiang Mai Tourism", domain: "tourismchiangmai.org" },
    ],
  },
  {
    topicName: "Thai Royal History & Buddhism",
    category: "travel",
    description: `The Thai monarchy's relationship to Buddhism is one of the defining structural features of Thai civilization — since the Sukhothai Kingdom of the 13th century, Thai kings have governed as Dharmaraja (righteous Buddhist kings), with their legitimacy rooted in Buddhist merit accumulated across lifetimes, their governance theoretically guided by the Dasavidha-rājadhamma (ten royal virtues), and their ceremonial life interwoven with Brahmin and Buddhist rites that link the palace to the cosmos. King Bhumibol Adulyadej (Rama IX), who reigned from 1946 to 2016 — one of the longest-reigning monarchs in history — was understood by Thai people not merely as a head of state but as a bodhisattva-king, a being of extraordinary merit whose life was devoted to the welfare of his people. Understanding this relationship — which is not superstition but a sophisticated political theology that has maintained social cohesion in a country that has experienced 20 coups since 1932 — is essential to understanding what you are seeing in every Thai temple, royal ceremony, and Buddhist observance.`,
    keywords: [
      "Thai royal family Buddhism",
      "Chakri dynasty history",
      "Dharmaraja Buddhist kingship",
      "King Bhumibol Thailand",
      "Thai monarchy culture",
      "Sukhothai Kingdom history",
      "royal ceremonies Thailand",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Royal Thai Government", domain: "thaigov.go.th" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
      { name: "The Nation Thailand", domain: "nationthailand.com" },
    ],
  },
  {
    topicName: "Phuket Architecture Heritage",
    category: "travel",
    description: `Phuket's Old Town contains one of the finest concentrations of Sino-Portuguese colonial architecture in Asia — a style born when Hokkien Chinese tin-mining families built in the shophouse tradition of their Fujian homeland and incorporated Portuguese and British colonial architectural elements (arched colonnaded walkways, stucco ornamentation, European-style façades) that they encountered through trade with colonial Penang and British-controlled Malacca. The five-foot walkway (kaki lima) — a covered pedestrian corridor built into every shophouse frontage — is a practical architectural innovation designed for the tropical climate, creating shade and shelter from the monsoon rains while connecting commercial buildings into a continuous covered street. Restoration efforts since the 1990s have preserved hundreds of buildings on Thalang, Dibuk, Krabi, and Phang Nga Roads; Old Phuket Town was submitted to UNESCO for World Heritage consideration in 2015 and is comparable in architectural quality to Penang's George Town (awarded World Heritage status in 2008).`,
    keywords: [
      "Sino-Portuguese architecture Phuket",
      "Old Phuket Town heritage buildings",
      "Phuket colonial architecture",
      "shophouse architecture Southeast Asia",
      "Peranakan buildings Phuket",
      "Thalang Road historic district",
      "Phuket UNESCO heritage",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "Tourism Authority of Thailand", domain: "tourismthailand.org" },
      { name: "Phuket Old Town Foundation", domain: "phuketoldtown.com" },
      { name: "UNESCO World Heritage", domain: "whc.unesco.org" },
    ],
  },
  {
    topicName: "2004 Indian Ocean Tsunami — Memory & Lessons",
    category: "travel",
    description: `The December 26, 2004 Indian Ocean tsunami — triggered by a 9.1-magnitude earthquake off Sumatra — killed over 227,000 people across 14 countries and fundamentally changed global understanding of oceanic disaster risk, indigenous ecological knowledge, and international emergency preparedness. Phuket's beaches (Patong, Karon, Kata) were severely impacted; the fishing village of Ban Nam Khem in Phang Nga Province lost more than half its population. The event produced two extraordinary lessons: the Indian Ocean Tsunami Warning System (now operational), and the documented survival of Moken and Urak Lawoi communities whose traditional knowledge of sea behavior allowed them to reach high ground before the wave struck — a validation of indigenous ecological science that had no technological equivalent at the time. Memorials at Ban Nam Khem (where a boat deposited inland by the wave is preserved) and across Phuket invite travelers to understand the disaster's human scale before celebrating the beaches it struck.`,
    keywords: [
      "2004 Indian Ocean tsunami Thailand",
      "Phuket tsunami memorial",
      "Ban Nam Khem memorial Phang Nga",
      "tsunami warning systems",
      "Moken indigenous tsunami survival",
      "Andaman coast disaster history",
      "December 2004 earthquake Thailand",
    ],
    notificationPriority: "digest",
    trustedSources: [
      { name: "UNESCO Pacific Science", domain: "ioc.unesco.org" },
      { name: "NOAA Tsunami Warning", domain: "tsunami.noaa.gov" },
      { name: "Bangkok Post", domain: "bangkokpost.com" },
      { name: "The Guardian", domain: "theguardian.com" },
    ],
  },
];
