import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import businessesRouter from "./businesses";
import travelRouter from "./travel";
import surveysRouter from "./surveys";
import savedPlacesRouter from "./saved-places";
import alertsRouter from "./alerts";
import moderationRouter from "./moderation";
import safetyContextRouter from "./safety-context";
import reviewsRouter from "./reviews";
import checkinsRouter from "./checkins";
import pointsRouter from "./points";
import eventRsvpsRouter from "./event-rsvps";
import pushTokenRouter from "./push-token";
import communityRouter from "./community";
import conversationsRouter from "./conversations";
import waitlistRouter from "./waitlist";
import contactRouter from "./contact";
import eventsRouter from "./events";
import usersRouter from "./users";
import groupsRouter from "./groups";
import adminRouter from "./admin";
import kinfolkRouter from "./kinfolk";
import wishlistRouter from "./wishlist";
import claimsRouter from "./claims";
import notificationsRouter from "./notifications";
import stripeRouter from "./stripe";
import adminUsersRouter from "./admin-users";
import mapsRouter from "./maps";
import ogRouter from "./og";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(businessesRouter);
router.use(travelRouter);
router.use(surveysRouter);
router.use(savedPlacesRouter);
router.use(alertsRouter);
router.use(moderationRouter);
router.use(safetyContextRouter);
router.use(reviewsRouter);
router.use(checkinsRouter);
router.use(pointsRouter);
router.use(eventRsvpsRouter);
router.use(pushTokenRouter);
router.use(communityRouter);
router.use(conversationsRouter);
router.use(waitlistRouter);
router.use(contactRouter);
router.use(eventsRouter);
router.use(usersRouter);
router.use(groupsRouter);
router.use(adminRouter);
router.use(kinfolkRouter);
router.use(wishlistRouter);
router.use(claimsRouter);
router.use(notificationsRouter);
router.use(stripeRouter);
router.use(adminUsersRouter);
router.use(mapsRouter);
router.use(ogRouter);

export default router;
