import { Router, type IRouter } from "express";
import path from "path";
import healthRouter from "./health";
import authRouter from "./auth";
import businessesRouter from "./businesses";
import travelRouter from "./travel";
import surveysRouter from "./surveys";
import savedPlacesRouter from "./saved-places";
import alertsRouter from "./alerts";
import moderationRouter from "./moderation";
import safetyContextRouter from "./safety-context";
import reviewsRouter from "./reviews";
import checkinsRouter from "./checkins";
import pointsRouter from "./points";
import eventRsvpsRouter from "./event-rsvps";
import pushTokenRouter from "./push-token";
import communityRouter from "./community";
import conversationsRouter from "./conversations";
import waitlistRouter from "./waitlist";
import contactRouter from "./contact";
import eventsRouter from "./events";
import usersRouter from "./users";
import groupsRouter from "./groups";
import adminRouter from "./admin";
import kinfolkRouter from "./kinfolk";
import wishlistRouter from "./wishlist";
import claimsRouter from "./claims";
import notificationsRouter from "./notifications";
import stripeRouter from "./stripe";
import adminUsersRouter from "./admin-users";
import mapsRouter from "./maps";
import ogRouter from "./og";
import jobsRouter from "./jobs";
import impactRouter from "./impact";
import submitBusinessRouter from "./submit-business";
import billingRouter from "./billing";
import cronRouter from "./cron";
import referralsRouter from "./referrals";
import contentReportsRouter from "./content-reports";
import verificationRouter from "./verification";
import dealsRouter from "./deals";
import storiesRouter from "./stories";
import redemptionsRouter from "./redemptions";
import mentorshipRouter from "./mentorship";
import reportsRouter from "./reports";
import travelFlightsRouter from "./travel-flights";
import connectionsRouter from "./connections";
import familyRouter from "./family";
import safetyCheckinsRouter from "./safety-checkins";
import locationSharesRouter from "./location-shares";
import meetupVerificationsRouter from "./meetup-verifications";
import safetyTipsRouter from "./safety-tips";
import skipFeedbackRouter from "./skip-feedback";
import businessesAnalyticsRouter from "./businesses-analytics";
import promoteRouter from "./promote";
import postNudgeRouter from "./post-nudge";
import userSettingsRouter from "./user-settings";
import spaceReportsRouter from "./space-reports";
import connectRouter from "./connect";
import communitySpacesRouter from "./community-spaces";
import journalsRouter from "./journals";
import platePassesRouter from "./plate-passes";
import listsRouter from "./lists";
import challengeApplicationsRouter from "./challenge-applications";
import categoryWaitlistRouter from "./category-waitlist";
import businessNominationsRouter from "./business-nominations";
import businessIdentityRouter from "./business-identity";
import broadcastsRouter from "./broadcasts";
import communityHealthRouter from "./community-health";
import journalInsightsRouter from "./journal-insights";
import savedLocationsRouter from "./saved-locations";
import disputesRouter from "./disputes";
import docusignRouter from "./docusign";
import smartPathwaysRouter from "./smart-pathways";
import knowledgeRouter from "./knowledge";
import marketplaceFeesRouter from "./marketplace-fees";
import trustRouter from "./trust";
import journeysRouter from "./journeys";
import entityConnectionsRouter from "./entity-connections";
import signalsRouter from "./signals";
import smartSearchRouter from "./smart-search";
import notificationsHubRouter from "./notifications-hub";
import knowledgeChannelsRouter from "./knowledge-channels";
import { recommendRouter } from "./recommend";
import captionsRouter from "./captions";
import communityBoundariesRouter from "./community-boundaries";
import businessResponseRouter from "./business-response";
import businessImprovementRouter from "./business-improvement";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(businessesRouter);
router.use(travelRouter);
router.use(surveysRouter);
router.use(savedPlacesRouter);
router.use(alertsRouter);
router.use(moderationRouter);
router.use(safetyContextRouter);
router.use(reviewsRouter);
router.use(checkinsRouter);
router.use(pointsRouter);
router.use(eventRsvpsRouter);
router.use(pushTokenRouter);
router.use(communityRouter);
router.use(conversationsRouter);
router.use(waitlistRouter);
router.use(contactRouter);
router.use(eventsRouter);
router.use(usersRouter);
router.use(groupsRouter);
router.use(adminRouter);
router.use(kinfolkRouter);
router.use(wishlistRouter);
router.use(claimsRouter);
router.use(notificationsRouter);
router.use(stripeRouter);
router.use(adminUsersRouter);
router.use(mapsRouter);
router.use(ogRouter);
router.use(jobsRouter);
router.use(impactRouter);
router.use(submitBusinessRouter);
router.use(billingRouter);
router.use(cronRouter);
router.use(referralsRouter);
router.use(contentReportsRouter);
router.use(verificationRouter);
router.use(dealsRouter);
router.use(storiesRouter);
router.use(redemptionsRouter);
router.use(mentorshipRouter);
router.use(reportsRouter);
router.use(travelFlightsRouter);
router.use(connectionsRouter);
router.use(familyRouter);
router.use(safetyCheckinsRouter);
router.use(locationSharesRouter);
router.use(meetupVerificationsRouter);
router.use(safetyTipsRouter);
router.use(skipFeedbackRouter);
router.use(businessesAnalyticsRouter);
router.use(promoteRouter);
router.use(postNudgeRouter);
router.use(userSettingsRouter);
router.use(spaceReportsRouter);
router.use(connectRouter);
router.use(communitySpacesRouter);
router.use(journalsRouter);
router.use(platePassesRouter);
router.use(listsRouter);
router.use(challengeApplicationsRouter);
router.use(categoryWaitlistRouter);
router.use(businessNominationsRouter);
router.use(businessIdentityRouter);
router.use(broadcastsRouter);
router.use(communityHealthRouter);
router.use(journalInsightsRouter);
router.use(savedLocationsRouter);
router.use(disputesRouter);
router.use(docusignRouter);
router.use(smartPathwaysRouter);
router.use(knowledgeRouter);
router.use(marketplaceFeesRouter);
router.use(trustRouter);
router.use(journeysRouter);
router.use(entityConnectionsRouter);
router.use(signalsRouter);
router.use(smartSearchRouter);
router.use(notificationsHubRouter);
router.use(knowledgeChannelsRouter);
router.use(recommendRouter);
router.use(captionsRouter);
router.use(communityBoundariesRouter);
router.use(businessResponseRouter);
router.use(businessImprovementRouter);

router.get("/download/mobile-build.zip", (req, res) => {
  const filePath = path.join(process.cwd(), "mobile-build.zip");
  res.download(filePath, "mobile-build.zip");
});

export default router;
