export type DirectBusinessInput = { businessName: string; businessDescription: string; primaryCategory: string; specialties: string[]; communityTags: string[]; ownerName?: string; ownerRole?: string; ownerIdentityText?: string; locationLabel?: string; addressLine1?: string; city?: string; stateRegion?: string; postalCode?: string; countryCode: string; phone?: string; email?: string; websiteUrl?: string; instagramHandle?: string; facebookUrl?: string; tiktokHandle?: string };
const text = (value: unknown, max: number) => typeof value === "string" ? value.trim().slice(0, max) : undefined;
const list = (value: unknown, max: number) => Array.isArray(value) ? [...new Set(value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean))].slice(0, max) : [];
export function validateDirectBusiness(value: unknown): DirectBusinessInput {
  if (!value || typeof value !== "object") throw new Error("BUSINESS_BODY_REQUIRED"); const body = value as Record<string, unknown>;
  const businessName = text(body.businessName, 160), businessDescription = text(body.businessDescription, 3000), primaryCategory = text(body.primaryCategory, 80);
  if (!businessName || businessName.length < 2) throw new Error("BUSINESS_NAME_REQUIRED"); if (!businessDescription || businessDescription.length < 20) throw new Error("BUSINESS_DESCRIPTION_REQUIRED"); if (!primaryCategory) throw new Error("BUSINESS_CATEGORY_REQUIRED");
  return { businessName, businessDescription, primaryCategory, specialties: list(body.specialties, 12), communityTags: list(body.communityTags, 8), ownerName: text(body.ownerName,160), ownerRole:text(body.ownerRole,120), ownerIdentityText:text(body.ownerIdentityText,280), locationLabel:text(body.locationLabel,200), addressLine1:text(body.addressLine1,200), city:text(body.city,100), stateRegion:text(body.stateRegion,100), postalCode:text(body.postalCode,20), countryCode:text(body.countryCode,2) ?? "US", phone:text(body.phone,40), email:text(body.email,254), websiteUrl:text(body.websiteUrl,500), instagramHandle:text(body.instagramHandle,100), facebookUrl:text(body.facebookUrl,500), tiktokHandle:text(body.tiktokHandle,100) };
}
