/**
 * Expo config plugin — fix for expo-av EXEventEmitter.h missing in SDK 57+
 *
 * ROOT CAUSE:
 *   expo-av@16.0.8 imports <ExpoModulesCore/EXEventEmitter.h> in EXAV.h.
 *   ExpoModulesCore in SDK 57 removed that file from public headers.
 *   Xcode fails: "file not found / could not build Objective-C module EXAV".
 *
 * FIX STRATEGY:
 *   Inject the stub creation code INTO the existing `post_install do |installer|`
 *   block generated by expo prebuild. CocoaPods only allows one post_install block;
 *   adding a second one causes "Specifying multiple post_install hooks is unsupported".
 *
 *   The stub runs after `pod install` populates Pods/Headers/ but before Xcode
 *   compiles — the only safe window to place the missing header.
 */
const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "[exav-fix-v2]";

// Code injected immediately after "post_install do |installer|"
// Uses explicit string concat instead of heredoc to avoid Ruby parse issues.
const RUBY_INJECTION = `
  # ${MARKER} — EXEventEmitter.h stub for expo-av / ExpoModulesCore SDK 57 compat
  require 'fileutils'
  begin
    _exav_dir  = File.join(installer.sandbox.root, 'Headers', 'Public', 'ExpoModulesCore')
    _exav_file = File.join(_exav_dir, 'EXEventEmitter.h')
    unless File.exist?(_exav_file)
      FileUtils.mkdir_p(_exav_dir)
      _stub = "// EXEventEmitter.h stub — injected by withExpoAvFix\\n"
      _stub << "#pragma once\\n"
      _stub << "#import <Foundation/Foundation.h>\\n\\n"
      _stub << "@protocol EXEventEmitter <NSObject>\\n"
      _stub << "@required\\n"
      _stub << "- (NSArray<NSString *> *)supportedEvents;\\n"
      _stub << "@optional\\n"
      _stub << "- (void)startObserving;\\n"
      _stub << "- (void)stopObserving;\\n"
      _stub << "@end\\n"
      File.write(_exav_file, _stub)
      puts "[exav-fix] Created EXEventEmitter.h stub at #{_exav_file}"
    else
      puts "[exav-fix] EXEventEmitter.h already present — skipping."
    end
  rescue => e
    puts "[exav-fix] ERROR: #{e.class}: #{e.message}"
  end
`;

module.exports = function withExpoAvFix(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn("[withExpoAvFix] Podfile not found — skipping.");
        return config;
      }

      let podfile = fs.readFileSync(podfilePath, "utf8");

      if (podfile.includes(MARKER)) {
        console.log(`[withExpoAvFix] ${MARKER} already present — skipping.`);
        return config;
      }

      // Find the existing post_install block and inject code right after the opening line.
      // Expo prebuild always generates: "post_install do |installer|"
      const POST_INSTALL_OPEN = "post_install do |installer|";
      const idx = podfile.indexOf(POST_INSTALL_OPEN);

      if (idx === -1) {
        console.warn(
          "[withExpoAvFix] Could not find 'post_install do |installer|' in Podfile — skipping."
        );
        return config;
      }

      const insertAt = idx + POST_INSTALL_OPEN.length;
      const patched =
        podfile.slice(0, insertAt) +
        "\n" +
        RUBY_INJECTION +
        podfile.slice(insertAt);

      fs.writeFileSync(podfilePath, patched, "utf8");
      console.log(
        `[withExpoAvFix] Injected ${MARKER} into existing post_install block.`
      );

      return config;
    },
  ]);
};
