/**
 * Expo config plugin — fix for the react-native-maps pod name mismatch.
 *
 * ROOT CAUSE:
 *   react-native-maps@1.27.x ships react-native-maps.podspec with
 *   s.name = "react-native-maps". Expo autolinking generates:
 *     pod 'react-native-google-maps', :path => '.../react-native-maps'
 *   CocoaPods looks for react-native-google-maps.podspec by filename → fails.
 *
 * WHY ONLY PODFILE INJECTION WORKS:
 *   EAS order: expo prebuild → pnpm install --no-frozen-lockfile → pod install
 *   Any node_modules file created before the second pnpm install gets wiped.
 *   eas-build-post-install also runs before the second pnpm install.
 *   The Podfile is generated by expo prebuild and never touched by pnpm.
 *   Ruby in the Podfile runs during pod install — the only safe window.
 *
 * PREVIOUS BUG (builds 57/58):
 *   The skip condition `File.read(dst).include?('react-native-google-maps')` was
 *   returning true because the podspec's GitHub URL and subspec dependency lines
 *   contain 'react-native-google-maps'. So we skipped overwriting a cached copy
 *   that still had s.name = "react-native-maps". Fix: always overwrite, and check
 *   s.name specifically.
 */
const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "[rn-maps-fix-v6]";

const RUBY_FIX = `
# ${MARKER} — react-native-google-maps podspec fix (runs during pod install)
require 'fileutils'
begin
  _rn_maps_pnpm = File.expand_path(
    File.join('..', '..', '..', 'node_modules', '.pnpm'),
    File.dirname(File.expand_path(__FILE__))
  )
  puts "[rn-maps-fix] Scanning pnpm store: #{_rn_maps_pnpm}"
  _dirs = Dir.glob(File.join(_rn_maps_pnpm, 'react-native-maps@*', 'node_modules', 'react-native-maps'))
  puts "[rn-maps-fix] Found #{_dirs.length} react-native-maps dir(s)"
  _dirs.each do |maps_dir|
    src = File.join(maps_dir, 'react-native-maps.podspec')
    dst = File.join(maps_dir, 'react-native-google-maps.podspec')
    unless File.exist?(src)
      puts "[rn-maps-fix] Source not found: #{src}"
      next
    end
    content = File.read(src)
    # Log what s.name the source actually has
    src_sname_line = content.lines.find { |l| l =~ /\\bs\\.name\\b/ }
    puts "[rn-maps-fix] Source s.name: #{src_sname_line.to_s.strip}"
    # Build copy content — replace s.name with the correct pod name.
    # Use literal replacement first (handles exact format), then regex fallback.
    content_copy = content
      .gsub('s.name                 = "react-native-maps"', 's.name                 = "react-native-google-maps"')
      .gsub('s.name = "react-native-maps"',                  's.name = "react-native-google-maps"')
      .gsub("s.name = 'react-native-maps'",                  "s.name = 'react-native-google-maps'")
    # Regex fallback if none of the literals matched
    unless content_copy.match?(/s\\.name\\s*=\\s*["']react-native-google-maps["']/)
      content_copy = content_copy.gsub(/s\\.name\\s*=\\s*["'][^"']*["']/, 's.name = "react-native-google-maps"')
      puts "[rn-maps-fix] Used regex fallback for s.name replacement"
    end
    # Always write — never skip based on file content (the URL/deps also contain
    # 'react-native-google-maps' which would cause a false-positive skip)
    File.write(dst, content_copy)
    dst_sname_line = content_copy.lines.find { |l| l =~ /\\bs\\.name\\b/ }
    puts "[rn-maps-fix] Wrote #{dst}"
    puts "[rn-maps-fix] Copy s.name: #{dst_sname_line.to_s.strip}"
  end
rescue => e
  puts "[rn-maps-fix] ERROR: #{e.class}: #{e.message}"
  puts e.backtrace.first(3).join("\\n")
end

`;

module.exports = function withRnMapsPodfileFix(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn("[withRnMapsPodfileFix] Podfile not found — skipping.");
        return config;
      }

      let podfile = fs.readFileSync(podfilePath, "utf8");

      // Remove any older version of the fix block so we always inject the latest.
      // The block starts with "# [rn-maps-fix" and ends before the next blank
      // line that isn't part of our Ruby code. Simplest: strip everything from
      // the start marker through the closing "end\n\n" of our rescue block.
      if (podfile.includes("[rn-maps-fix") && !podfile.includes(MARKER)) {
        // Old version present — strip it. Our blocks always end with "end\n\n"
        podfile = podfile.replace(
          /# \[rn-maps-fix[^\]]*\][^\n]*\n[\s\S]*?^end\n\n/m,
          ""
        );
        console.log("[withRnMapsPodfileFix] Stripped old rn-maps-fix block.");
      }

      if (podfile.includes(MARKER)) {
        console.log(
          `[withRnMapsPodfileFix] ${MARKER} already present — skipping.`
        );
        return config;
      }

      fs.writeFileSync(podfilePath, RUBY_FIX + podfile, "utf8");
      console.log(
        `[withRnMapsPodfileFix] Injected ${MARKER} Ruby block into Podfile.`
      );

      return config;
    },
  ]);
};
