/**
 * Expo config plugin — fix for the react-native-maps duplicate pod conflict.
 *
 * ROOT CAUSE:
 *   Two autolinking macros run during `pod install`:
 *     1. use_react_native!  → reads react-native-maps.podspec → pod 'react-native-maps'
 *     2. use_expo_modules!  → reads package config        → pod 'react-native-google-maps'
 *
 *   Both pods point to the same source directory and compile the same AIR* .m files
 *   → 339 duplicate symbol errors → linker crash.
 *
 * FIX (shim pattern — build 74+):
 *   During `pod install`, BEFORE CocoaPods resolves pods, this Ruby block:
 *
 *     1. Creates react-native-google-maps.podspec — copy of the real podspec, with
 *        s.name changed to "react-native-google-maps". This is the REAL implementation.
 *
 *     2. OVERWRITES react-native-maps.podspec with a thin SHIM that has:
 *        - s.name = "react-native-maps"  (so use_react_native! finds it)
 *        - NO source_files               (compiles nothing → zero AIR* symbols)
 *        - s.dependency 'react-native-google-maps'  (pulls in the real impl)
 *
 *   Result:
 *     - pod 'react-native-maps'         → shim pod, 0 source files compiled
 *     - pod 'react-native-google-maps'  → real impl, compiles AIR* once
 *     → no duplicates → linker passes
 *
 * BUILD HISTORY:
 *   67-70: linker crash — podspecPath override caused both pods.
 *   71:    dependencies:{} in react-native.config.js; both pods still appeared. Crash.
 *   72:    platforms:{ios:null} disabled BOTH autolinkers → pod install failure.
 *   73:    JS text-removal of pod line; use_react_native! is a macro, line never exists
 *          as literal text → removal was no-op → pods still installed → linker crash.
 *   74+:   Ruby shim at pod-install time — this build.
 */
const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "[rn-maps-shim-v1]";

// Ruby block injected at the TOP of the Podfile.
// Runs synchronously when CocoaPods evaluates the Podfile (before pod resolution).
const RUBY_SHIM = `
# ${MARKER} — react-native-maps shim fix (runs during pod install, before pod resolution)
require 'fileutils'
begin
  _rn_maps_pnpm = File.expand_path(
    File.join('..', '..', '..', 'node_modules', '.pnpm'),
    File.dirname(File.expand_path(__FILE__))
  )
  puts "[rn-maps-shim] Scanning pnpm store: #{_rn_maps_pnpm}"
  _dirs = Dir.glob(File.join(_rn_maps_pnpm, 'react-native-maps@*', 'node_modules', 'react-native-maps'))
  puts "[rn-maps-shim] Found #{_dirs.length} react-native-maps dir(s)"
  _dirs.each do |maps_dir|
    src = File.join(maps_dir, 'react-native-maps.podspec')
    dst = File.join(maps_dir, 'react-native-google-maps.podspec')
    unless File.exist?(src)
      puts "[rn-maps-shim] Source not found: #{src}"
      next
    end
    orig = File.read(src)

    # ── Step 1: create react-native-google-maps.podspec (real implementation) ──
    google_content = orig
      .gsub('s.name                 = "react-native-maps"', 's.name                 = "react-native-google-maps"')
      .gsub('s.name = "react-native-maps"',                  's.name = "react-native-google-maps"')
      .gsub("s.name = 'react-native-maps'",                  "s.name = 'react-native-google-maps'")
    unless google_content.include?('react-native-google-maps')
      google_content = google_content.sub(/s\\.name\\s*=\\s*["'][^"']*["']/, 's.name = "react-native-google-maps"')
    end
    File.write(dst, google_content)
    puts "[rn-maps-shim] Wrote react-native-google-maps.podspec"

    # ── Step 2: overwrite react-native-maps.podspec with a no-source shim ────
    version_match = orig.match(/s\\.version\\s*=\\s*["']([^"']+)["']/)
    version = version_match ? version_match[1] : '1.0.0'
    platform_match = orig.match(/s\\.platform\\s*=\\s*:ios,\\s*["']([^"']+)["']/)
    ios_min = platform_match ? platform_match[1] : '15.0'
    homepage_match = orig.match(/s\\.homepage\\s*=\\s*["']([^"']+)["']/)
    homepage = homepage_match ? homepage_match[1] : 'https://github.com/react-native-maps/react-native-maps'
    shim = <<~SHIM
      # react-native-maps.podspec — SHIM (generated by withRnMapsPodfileFix.js)
      # No source files compiled. The real implementation is in react-native-google-maps,
      # which Expo autolinking already adds to the Podfile via use_expo_modules!.
      # We do NOT declare s.dependency 'react-native-google-maps' here because that
      # would trigger CocoaPods version resolution against a cached Podfile.lock.
      Pod::Spec.new do |s|
        s.name             = 'react-native-maps'
        s.version          = '#{version}'
        s.summary          = 'Shim — zero source files, no duplicate AIR* symbols'
        s.description      = 'Zero-source shim to prevent duplicate symbol linker errors.'
        s.homepage         = '#{homepage}'
        s.license          = { :type => 'MIT' }
        s.author           = { 'Shim' => 'shim@placeholder.com' }
        s.platform         = :ios, '#{ios_min}'
        s.source           = { :path => '.' }
        s.source_files     = []
      end
    SHIM
    File.write(src, shim)
    puts "[rn-maps-shim] Overwrote react-native-maps.podspec with shim (version=#{version})"
  end
rescue => e
  puts "[rn-maps-shim] ERROR: #{e.class}: #{e.message}"
  puts e.backtrace.first(5).join("\\n")
end

`;

module.exports = function withRnMapsPodfileFix(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn("[withRnMapsPodfileFix] Podfile not found — skipping.");
        return config;
      }

      let podfile = fs.readFileSync(podfilePath, "utf8");

      // Strip any old version of our marker block.
      const oldMarkers = [
        "[rn-maps-fix",
        "[rn-maps-shim",
      ];
      for (const m of oldMarkers) {
        if (podfile.includes(m) && !podfile.includes(MARKER)) {
          // Remove old block: from the comment line through the closing `end\n\n`
          podfile = podfile.replace(
            new RegExp(`# \\[${m.slice(1).replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&")}[\\s\\S]*?^end\\n\\n`, "m"),
            ""
          );
          console.log(`[withRnMapsPodfileFix] Stripped old ${m} block.`);
        }
      }

      if (podfile.includes(MARKER)) {
        console.log(
          `[withRnMapsPodfileFix] ${MARKER} already present — skipping injection.`
        );
      } else {
        podfile = RUBY_SHIM + podfile;
        console.log(
          `[withRnMapsPodfileFix] Injected ${MARKER} Ruby shim block into Podfile.`
        );
      }

      fs.writeFileSync(podfilePath, podfile, "utf8");
      return config;
    },
  ]);
};
