/**
 * Expo config plugin — fix for the react-native-maps duplicate pod conflict.
 *
 * ROOT CAUSE:
 *   use_react_native!  → pod 'react-native-maps'         (RN CLI autolinking)
 *   use_expo_modules!  → pod 'react-native-google-maps'  (Expo autolinking)
 *   Both compile the same AIR* .m files → 339 duplicate symbols → linker crash.
 *
 * FIX (two-part, build 77+):
 *
 *   Part 1 — top of Podfile, runs before pod resolution:
 *     Creates react-native-google-maps.podspec (copy of real podspec with name changed)
 *     so Expo autolinking's 'pod react-native-google-maps' resolves correctly.
 *     react-native-maps.podspec is left UNTOUCHED (CocoaPods must validate it normally).
 *
 *   Part 2 — injected INTO Expo's existing post_install block (NOT a second block):
 *     Sets EXCLUDED_SOURCE_FILE_NAMES='*' on the react-native-maps Xcode target.
 *     This tells the Xcode compiler to compile zero source files from that target.
 *     libreact-native-maps.a is built but empty.
 *     react-native-google-maps compiles all AIR* symbols exactly once.
 *     Linker: empty lib + full lib = no duplicates.
 *
 * WHY NOT A SEPARATE post_install BLOCK:
 *   CocoaPods (v1.15+) used by EAS does NOT support multiple post_install blocks —
 *   it raises an error during Podfile evaluation. Injecting into Expo's existing
 *   block (the one generated by expo prebuild) is the only safe approach.
 *
 * BUILD HISTORY:
 *   67-70: podspecPath override → both pods added.
 *   71:    empty dependencies:{} → both pods still added by macro expansion.
 *   72:    platforms:{ios:null} → both autolinkers killed → pod not found.
 *   73:    JS text removal no-op (macros, not literals) → both pods linked → crash.
 *   74:    Ruby shim + s.dependency → version conflict with cached Podfile.lock.
 *   75:    Ruby shim without dependency → empty pod rejected by CocoaPods validation.
 *   76:    Separate post_install block → conflict with Expo's block → pod install fail.
 *   77+:   Inject into Expo's post_install (this build).
 */
const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// ── Part 1: Ruby block injected at TOP of Podfile ────────────────────────────
// Runs synchronously during Podfile evaluation, before CocoaPods resolves pods.
// Creates react-native-google-maps.podspec from the real react-native-maps.podspec.
const TOP_MARKER = "# [rn-maps-fix-top]";
const TOP_RUBY = `${TOP_MARKER}
require 'fileutils'
begin
  _pnpm = File.expand_path(
    File.join('..', '..', '..', 'node_modules', '.pnpm'),
    File.dirname(File.expand_path(__FILE__))
  )
  puts "[rn-maps] pnpm store: #{_pnpm}"
  _dirs = Dir.glob(File.join(_pnpm, 'react-native-maps@*', 'node_modules', 'react-native-maps'))
  puts "[rn-maps] found #{_dirs.length} react-native-maps location(s)"
  _dirs.each do |d|
    src = File.join(d, 'react-native-maps.podspec')
    dst = File.join(d, 'react-native-google-maps.podspec')
    next unless File.exist?(src)
    c = File.read(src)
    c = c.gsub(/s\\.name\\s*=\\s*["']react-native-maps["']/, 's.name = "react-native-google-maps"')
    File.write(dst, c)
    puts "[rn-maps] wrote react-native-google-maps.podspec"
  end
rescue => e
  puts "[rn-maps] Part1 error: #{e.class}: #{e.message}"
end
`;

// ── Part 2: code injected INTO Expo's post_install block ─────────────────────
// We search for Expo's "post_install do |installer|" line and insert our lines
// immediately after it. No second post_install block is created.
const POST_MARKER = "# [rn-maps-fix-post]";
const POST_LINES = `  ${POST_MARKER}
  begin
    installer.pods_project.targets.each do |t|
      next unless t.name == 'react-native-maps'
      t.build_configurations.each { |c| c.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] = '*' }
      puts '[rn-maps] react-native-maps: EXCLUDED_SOURCE_FILE_NAMES=* (zero AIR* compiled)'
    end
  rescue => e
    puts "[rn-maps] Part2 error: \#{e.class}: \#{e.message}"
  end`;

module.exports = function withRnMapsPodfileFix(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn("[withRnMapsPodfileFix] Podfile not found — skipping.");
        return config;
      }

      let podfile = fs.readFileSync(podfilePath, "utf8");

      // ── Part 1: inject top block ───────────────────────────────────────────
      if (podfile.includes(TOP_MARKER)) {
        console.log("[withRnMapsPodfileFix] Part1 top block already present.");
      } else {
        podfile = TOP_RUBY + "\n" + podfile;
        console.log("[withRnMapsPodfileFix] Injected Part1 top block.");
      }

      // ── Part 2: inject into Expo's existing post_install block ─────────────
      if (podfile.includes(POST_MARKER)) {
        console.log("[withRnMapsPodfileFix] Part2 post_install injection already present.");
      } else {
        // Expo's Podfile has exactly one: "post_install do |installer|"
        // We insert our lines immediately after that opening line.
        const postInstallLine = "post_install do |installer|";
        if (podfile.includes(postInstallLine)) {
          podfile = podfile.replace(
            postInstallLine,
            postInstallLine + "\n" + POST_LINES
          );
          console.log("[withRnMapsPodfileFix] Injected Part2 into Expo's post_install block.");
        } else {
          console.warn(
            "[withRnMapsPodfileFix] WARNING: 'post_install do |installer|' not found in Podfile. " +
            "Part2 EXCLUDED_SOURCE_FILE_NAMES fix was NOT applied. " +
            "Build may fail at link time with duplicate symbol errors."
          );
        }
      }

      fs.writeFileSync(podfilePath, podfile, "utf8");
      return config;
    },
  ]);
};
