// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CommunityBoundaries.tsx": () => import("../components/mockups/CommunityBoundaries.tsx"),
  "./components/mockups/Task101PinDemo.tsx": () => import("../components/mockups/Task101PinDemo.tsx"),
  "./components/mockups/hero-modes/DarkMode.tsx": () => import("../components/mockups/hero-modes/DarkMode.tsx"),
  "./components/mockups/hero-modes/LightMode.tsx": () => import("../components/mockups/hero-modes/LightMode.tsx"),
  "./components/mockups/profiles/BizBroadcasts.tsx": () => import("../components/mockups/profiles/BizBroadcasts.tsx"),
  "./components/mockups/profiles/BizFeaturedVideo.tsx": () => import("../components/mockups/profiles/BizFeaturedVideo.tsx"),
  "./components/mockups/profiles/BizIdentity.tsx": () => import("../components/mockups/profiles/BizIdentity.tsx"),
  "./components/mockups/profiles/BizOwnerDashboard.tsx": () => import("../components/mockups/profiles/BizOwnerDashboard.tsx"),
  "./components/mockups/profiles/BizPinnedHighlights.tsx": () => import("../components/mockups/profiles/BizPinnedHighlights.tsx"),
  "./components/mockups/profiles/BusinessEditProfile.tsx": () => import("../components/mockups/profiles/BusinessEditProfile.tsx"),
  "./components/mockups/profiles/BusinessOwnerProfile.tsx": () => import("../components/mockups/profiles/BusinessOwnerProfile.tsx"),
  "./components/mockups/profiles/BusinessOwnerProfileVisitor.tsx": () => import("../components/mockups/profiles/BusinessOwnerProfileVisitor.tsx"),
  "./components/mockups/profiles/CommunityPage.tsx": () => import("../components/mockups/profiles/CommunityPage.tsx"),
  "./components/mockups/profiles/CommunityProfile.tsx": () => import("../components/mockups/profiles/CommunityProfile.tsx"),
  "./components/mockups/profiles/CommunityProfileVisitor.tsx": () => import("../components/mockups/profiles/CommunityProfileVisitor.tsx"),
  "./components/mockups/theme-compare/DarkModeHero.tsx": () => import("../components/mockups/theme-compare/DarkModeHero.tsx"),
  "./components/mockups/theme-compare/LightModeHero.tsx": () => import("../components/mockups/theme-compare/LightModeHero.tsx"),
  "./components/mockups/surveys/BlackOwnedSurvey.tsx": () => import("../components/mockups/surveys/BlackOwnedSurvey.tsx"),
  "./components/mockups/surveys/GeneralSurvey.tsx": () => import("../components/mockups/surveys/GeneralSurvey.tsx"),
  "./components/mockups/slides/Slide01Opening.tsx": () => import("../components/mockups/slides/Slide01Opening.tsx"),
  "./components/mockups/slides/Slide05TrustScore.tsx": () => import("../components/mockups/slides/Slide05TrustScore.tsx"),
  "./components/mockups/slides/Slide17WhyNow.tsx": () => import("../components/mockups/slides/Slide17WhyNow.tsx")
};
