// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CommunityBoundaries.tsx": () => import("../components/mockups/CommunityBoundaries.tsx"),
  "./components/mockups/hero-modes/DarkMode.tsx": () => import("../components/mockups/hero-modes/DarkMode.tsx"),
  "./components/mockups/hero-modes/LightMode.tsx": () => import("../components/mockups/hero-modes/LightMode.tsx"),
  "./components/mockups/profiles/BusinessOwnerProfile.tsx": () => import("../components/mockups/profiles/BusinessOwnerProfile.tsx"),
  "./components/mockups/profiles/BusinessOwnerProfileVisitor.tsx": () => import("../components/mockups/profiles/BusinessOwnerProfileVisitor.tsx"),
  "./components/mockups/profiles/CommunityPage.tsx": () => import("../components/mockups/profiles/CommunityPage.tsx"),
  "./components/mockups/profiles/CommunityProfile.tsx": () => import("../components/mockups/profiles/CommunityProfile.tsx"),
  "./components/mockups/profiles/CommunityProfileVisitor.tsx": () => import("../components/mockups/profiles/CommunityProfileVisitor.tsx"),
  "./components/mockups/surveys/BlackOwnedSurvey.tsx": () => import("../components/mockups/surveys/BlackOwnedSurvey.tsx"),
  "./components/mockups/surveys/GeneralSurvey.tsx": () => import("../components/mockups/surveys/GeneralSurvey.tsx"),
  "./components/mockups/theme-compare/DarkModeHero.tsx": () => import("../components/mockups/theme-compare/DarkModeHero.tsx"),
  "./components/mockups/theme-compare/LightModeHero.tsx": () => import("../components/mockups/theme-compare/LightModeHero.tsx")
};
