/**
 * Mapping With Melanin™ — Master Business Category Taxonomy
 *
 * This is the SINGLE SOURCE OF TRUTH for all category/subcategory values
 * across the platform: API validation, mobile filters, web dropdowns,
 * business onboarding, map filters, KinfolkAI, and Excel import sheets.
 *
 * To add or rename a category: edit here only. All consumers import from this file.
 */

export interface BusinessCategory {
  /** URL-safe slug, lowercase-hyphenated */
  id: string;
  /** Display name shown in UI */
  name: string;
  /** Subcategories within this category */
  subcategories: string[];
}

export const BUSINESS_CATEGORY_TAXONOMY: BusinessCategory[] = [
  {
    id: "food-and-drink",
    name: "Food & Drink",
    subcategories: [
      "Restaurants",
      "Cafés & Coffee",
      "Bakeries",
      "Desserts & Sweets",
      "Food Trucks & Mobile Food",
      "Catering",
      "Bars & Lounges",
      "Juice & Smoothies",
      "Specialty Foods",
      "Meal Prep",
      "Grocery & Markets",
      "Private Chefs",
    ],
  },
  {
    id: "beauty-and-personal-care",
    name: "Beauty & Personal Care",
    subcategories: [
      "Hair Salons",
      "Barbershops",
      "Braiders & Natural Hair",
      "Nail Salons & Nail Artists",
      "Makeup Artists",
      "Estheticians & Skincare",
      "Spas",
      "Massage",
      "Lashes & Brows",
      "Beauty Supply",
      "Cosmetics & Beauty Brands",
      "Mobile Beauty Services",
    ],
  },
  {
    id: "health-and-wellness",
    name: "Health & Wellness",
    subcategories: [
      "Primary Care & Medical Practices",
      "Dental",
      "Mental Wellness & Therapy",
      "Physical Therapy",
      "Chiropractic",
      "Nutrition & Dietitians",
      "Fitness & Gyms",
      "Personal Trainers",
      "Yoga & Pilates",
      "Wellness Centers",
      "Doula & Birth Services",
      "Holistic Wellness",
      "Pharmacies",
      "Home Health & Caregiving",
    ],
  },
  {
    id: "shopping-and-retail",
    name: "Shopping & Retail",
    subcategories: [
      "Clothing & Fashion",
      "Shoes & Accessories",
      "Jewelry",
      "Gifts",
      "Home Décor",
      "Furniture",
      "Books & Bookstores",
      "Art & Collectibles",
      "Specialty Retail",
      "Children's Retail",
      "Pet Products",
      "Online Shops",
    ],
  },
  {
    id: "travel-and-hospitality",
    name: "Travel & Hospitality",
    subcategories: [
      "Hotels & Resorts",
      "Bed & Breakfasts",
      "Vacation Rentals",
      "Travel Agencies & Advisors",
      "Tour Operators",
      "Tour Guides",
      "Transportation Services",
      "Luggage & Travel Products",
      "Travel Experiences",
    ],
  },
  {
    id: "arts-culture-and-entertainment",
    name: "Arts, Culture & Entertainment",
    subcategories: [
      "Museums",
      "Galleries",
      "Cultural Centers",
      "Performing Arts",
      "Theaters",
      "Music & Live Entertainment",
      "DJs",
      "Entertainment Venues",
      "Nightlife",
      "Festivals",
      "Attractions",
      "Gaming & Recreation",
      "Photography",
      "Videography",
    ],
  },
  {
    id: "professional-services",
    name: "Professional Services",
    subcategories: [
      "Accounting & Tax",
      "Legal Services",
      "Insurance",
      "Financial Services",
      "Business Consulting",
      "Marketing & Advertising",
      "Public Relations",
      "Graphic Design & Branding",
      "Web & App Development",
      "IT & Technology Services",
      "Printing",
      "Translation & Language Services",
      "Staffing & Recruiting",
      "Virtual Assistants",
    ],
  },
  {
    id: "home-and-property-services",
    name: "Home & Property Services",
    subcategories: [
      "Real Estate Agents & Brokers",
      "Property Management",
      "Contractors",
      "Construction",
      "Electricians",
      "Plumbing",
      "HVAC",
      "Landscaping & Lawn Care",
      "Cleaning Services",
      "Interior Design",
      "Moving Services",
      "Handyman Services",
      "Home Inspection",
      "Roofing",
      "Pest Control",
    ],
  },
  {
    id: "automotive-and-transportation",
    name: "Automotive & Transportation",
    subcategories: [
      "Auto Repair",
      "Auto Detailing",
      "Car Wash",
      "Tire Services",
      "Auto Dealers",
      "Auto Body & Collision",
      "Towing & Roadside Assistance",
      "Car Rental",
      "Chauffeur & Private Driver",
      "Transportation Companies",
    ],
  },
  {
    id: "events-and-celebrations",
    name: "Events & Celebrations",
    subcategories: [
      "Event Planning",
      "Wedding Planning",
      "Event Venues",
      "Party Rentals",
      "Decorators",
      "Florists",
      "Balloon Artists",
      "DJs & Entertainment",
      "Photographers",
      "Videographers",
      "Caterers",
      "Cakes & Desserts",
      "Invitations & Stationery",
      "Photo Booths",
    ],
  },
  {
    id: "education-and-learning",
    name: "Education & Learning",
    subcategories: [
      "Childcare & Daycare",
      "Preschools",
      "Tutoring",
      "Test Preparation",
      "Colleges & Universities",
      "HBCUs",
      "Trade & Vocational Schools",
      "Professional Training",
      "Music Lessons",
      "Dance Schools",
      "Art Classes",
      "Language Instruction",
      "Educational Programs",
    ],
  },
  {
    id: "children-and-family",
    name: "Children & Family",
    subcategories: [
      "Childcare",
      "Children's Activities",
      "Indoor Play",
      "Camps",
      "Family Entertainment",
      "Parenting Services",
      "Children's Parties",
      "Youth Programs",
      "Children's Retail",
      "Maternity & Baby Services",
    ],
  },
  {
    id: "community-and-nonprofit",
    name: "Community & Nonprofit",
    subcategories: [
      "Nonprofits",
      "Community Organizations",
      "Foundations",
      "Mutual Aid",
      "Advocacy Organizations",
      "Youth Organizations",
      "Senior Services",
      "Community Centers",
      "Cultural Organizations",
      "Professional Associations",
      "Chambers & Business Organizations",
    ],
  },
  {
    id: "faith-and-spirituality",
    name: "Faith & Spirituality",
    subcategories: [
      "Churches",
      "Mosques",
      "Synagogues",
      "Temples",
      "Spiritual Centers",
      "Faith-Based Organizations",
      "Religious Bookstores & Retail",
      "Faith-Based Community Services",
    ],
  },
  {
    id: "media-and-creative-services",
    name: "Media & Creative Services",
    subcategories: [
      "Content Creators",
      "Influencers & Cultural Ambassadors",
      "Podcasts",
      "Radio",
      "Publications & Magazines",
      "Writers & Authors",
      "Photography",
      "Videography",
      "Production Companies",
      "Recording Studios",
      "Music Production",
      "Creative Studios",
    ],
  },
  {
    id: "sports-and-recreation",
    name: "Sports & Recreation",
    subcategories: [
      "Sports Clubs",
      "Recreational Centers",
      "Coaches & Training",
      "Youth Sports",
      "Golf",
      "Swimming",
      "Martial Arts",
      "Dance & Movement",
      "Outdoor Recreation",
      "Adventure Experiences",
    ],
  },
  {
    id: "pets-and-animal-services",
    name: "Pets & Animal Services",
    subcategories: [
      "Veterinarians",
      "Pet Grooming",
      "Pet Boarding",
      "Dog Walking & Pet Sitting",
      "Pet Training",
      "Pet Daycare",
      "Pet Stores & Supplies",
    ],
  },
  {
    id: "technology-and-digital-services",
    name: "Technology & Digital Services",
    subcategories: [
      "Software Companies",
      "App Developers",
      "Web Developers",
      "IT Support",
      "Cybersecurity",
      "AI & Automation",
      "SaaS",
      "Digital Products",
      "Technology Consulting",
    ],
  },
  {
    id: "financial-and-business-services",
    name: "Financial & Business Services",
    subcategories: [
      "Banks & Credit Unions",
      "Financial Advisors",
      "Bookkeeping",
      "Tax Preparation",
      "Lending & Financing",
      "Mortgage Services",
      "Credit Services",
      "Business Funding",
      "Investment Services",
    ],
  },
  {
    id: "legal-and-government-services",
    name: "Legal & Government Services",
    subcategories: [
      "Attorneys & Law Firms",
      "Mediation",
      "Notary Services",
      "Immigration Services",
      "Legal Document Services",
      "Government Offices",
      "Public Services",
    ],
  },
  {
    id: "agriculture-and-specialty-producers",
    name: "Agriculture & Specialty Producers",
    subcategories: [
      "Farms",
      "Farmers Markets",
      "Urban Farms",
      "Specialty Growers",
      "Floriculture",
      "Food Producers",
      "Beverage Producers",
      "Agricultural Products",
    ],
  },
  {
    id: "other-services",
    name: "Other Services",
    subcategories: [
      "Laundry & Dry Cleaning",
      "Tailoring & Alterations",
      "Shoe Repair",
      "Locksmiths",
      "Shipping & Mailing",
      "Storage",
      "Funeral & Memorial Services",
      "Personal Concierge",
      "Other",
    ],
  },
];

/** Flat list of all main category names — for API validation and dropdowns */
export const MAIN_CATEGORY_NAMES: string[] = BUSINESS_CATEGORY_TAXONOMY.map((c) => c.name);

/** Map of category name → subcategory array — for dependent dropdowns */
export const SUBCATEGORY_MAP: Record<string, string[]> = Object.fromEntries(
  BUSINESS_CATEGORY_TAXONOMY.map((c) => [c.name, c.subcategories])
);

/** Flat list of ALL subcategory names across every category */
export const ALL_SUBCATEGORY_NAMES: string[] = BUSINESS_CATEGORY_TAXONOMY.flatMap((c) => c.subcategories);

/**
 * Legacy category names from before the master taxonomy was introduced.
 * Accepted during API validation so existing businesses are never broken.
 * New submissions should use MAIN_CATEGORY_NAMES only.
 */
export const LEGACY_CATEGORY_NAMES: string[] = [
  "Food & Beverage",
  "Shopping & Retail",
  "Home & Real Estate",
  "Home Improvement",
  "Automotive",
  "Technology",
  "Creative Services",
  "Events & Entertainment",
  "Family & Education",
  "Pet Services",
  "Community & Nonprofits",
  "Government & Public Resources",
  "Online & Mobile Businesses",
  "Home Services",
  "Real Estate & Housing",
  "Community & Nonprofit",
  "Restaurant & Food",
  "Retail & Shopping",
  "Education & Coaching",
  "Arts & Culture",
  "Restaurants & Nightlife",
  "Hotels & Stays",
  "Cultural Landmarks",
  "Beauty & Wellness",
  "Health & Fitness",
  "Beauty & Grooming",
  "Arts & Entertainment",
  "Education & Childcare",
  "Community Events",
  "Black Professionals",
];

/** Full valid set: new taxonomy + legacy names. Use this for API validation. */
export const ALL_VALID_CATEGORY_NAMES: string[] = [
  ...MAIN_CATEGORY_NAMES,
  ...LEGACY_CATEGORY_NAMES,
];
