/*
 * Mapping With Melanin — Corrected Kinfolk Chat Handler
 *
 * Suggested placement:
 *   server/routes/kinfolk-chat.ts
 *
 * This handler intentionally does NOT use a legacy/free-form `business_discovery`
 * classifier after the Universal Search Router runs. `intentClass` is always the
 * validated Router intent, and `provenanceNote` is determined server-side.
 */

import crypto from 'node:crypto';
import { Router } from 'express';
import { z } from 'zod';

// Replace these imports with the existing project modules. Keep the existing
// requireAuthenticatedUser middleware and existing AI provider client.
import { requireAuthenticatedUser } from '../auth/require-authenticated-user';
import { createUniversalSearchPlan } from '../kinfolk/universal-search-router-service';
import { getDeliveryProfile } from '../kinfolk/delivery-profile-repository';
import { retrieveEvidence } from '../kinfolk/evidence-retrieval-service';
import { buildDeliveryInstructions, buildAdaptiveAnswerSystemPrompt } from '../kinfolk/adaptive-tone-and-audience-filter';
import { invokeKinfolkModel } from '../kinfolk/model-service';
import { getOrCreateKinfolkSession } from '../kinfolk/session-service';
import { checkAiPool } from '../kinfolk/usage-pool-service';
import { writeKinfolkAuditEvent } from '../kinfolk/audit-service';

export type KinfolkIntentClass =
  | 'general_knowledge'
  | 'business_discovery'
  | 'culture_entertainment'
  | 'travel_discovery'
  | 'legal_regulated'
  | 'medical_health'
  | 'financial_regulated'
  | 'safety_emergency'
  | 'education_guidance'
  | 'community_discovery';

export interface SourceSummary {
  id: string;
  label: 'MWM verified listing' | 'Library-verified evidence' | 'Current source' | 'Community experience';
  title: string;
  url?: string;
  verifiedAt?: string;
}

export interface KinfolkChatResponse {
  sessionId: string;
  reply: string;
  intentClass: KinfolkIntentClass;
  provenanceNote?: string;
  sources: SourceSummary[];
  followUpSuggestions: string[];
  recommendations: unknown[] | null;
  smartPromotion: null;
  taskAction: null;
}

const bodySchema = z.object({
  message: z.string().trim().min(1).max(4_000),
  // Client may send a session identifier for continuity but it is never required
  // for authentication and never determines access to the chat route.
  sessionId: z.string().uuid().optional(),
  neighborVoice: z.boolean().optional().default(false),
});

const HIGH_CONSEQUENCE_INTENTS = new Set<KinfolkIntentClass>([
  'legal_regulated',
  'medical_health',
  'financial_regulated',
  'safety_emergency',
]);

function isHighConsequence(intent: KinfolkIntentClass): boolean {
  return HIGH_CONSEQUENCE_INTENTS.has(intent);
}

/**
 * This is a server-side safeguard, not a model prompt. It protects the exact
 * failure observed in production: a Thailand visa/documents question must not
 * be returned as `business_discovery` after routing.
 */
function enforceHighConsequenceClassification(plan: {
  intent: KinfolkIntentClass;
  domainTags: string[];
  consequence: 'low' | 'medium' | 'high';
  sourcePolicyId: string;
  citationMode: 'none' | 'recommended' | 'required';
}): typeof plan {
  const tags = new Set(plan.domainTags.map((tag) => tag.toLowerCase()));
  const travelPolicyOrVisa = tags.has('visa') || tags.has('entry_requirements') || tags.has('government_policy');

  if (travelPolicyOrVisa) {
    return {
      ...plan,
      intent: 'legal_regulated',
      consequence: 'high',
      sourcePolicyId: 'legal-authoritative-v1',
      citationMode: 'required',
    };
  }

  return plan;
}

/**
 * The note is deterministic and is never generated by the model. The UI may
 * render it in an amber provenance box; the API always returns it when present.
 */
function buildProvenanceNote(input: {
  intent: KinfolkIntentClass;
  sourceCount: number;
  sourcePolicyId: string;
}): string | undefined {
  if (input.intent === 'medical_health') {
    return input.sourceCount > 0
      ? 'General health information from the sources shown. It is not medical advice or a diagnosis.'
      : 'General health information only. Please verify decisions with a qualified clinician and current authoritative sources.';
  }

  if (input.intent === 'legal_regulated') {
    return input.sourceCount > 0
      ? 'General legal and travel information from the sources shown. Requirements can change; verify with the relevant official authority before acting.'
      : 'General legal and travel information only. Entry requirements can change; verify with an official government or embassy source before acting.';
  }

  if (input.intent === 'financial_regulated') {
    return 'General financial information only. It is not individualized investment, tax, insurance, or financial advice.';
  }

  if (input.intent === 'safety_emergency') {
    return 'For an immediate emergency, contact local emergency services. Confirm current alerts with official local authorities.';
  }

  return undefined;
}

function toSourceSummaries(evidence: Awaited<ReturnType<typeof retrieveEvidence>>): SourceSummary[] {
  return evidence
    .filter((item) => item.permittedForResponse)
    .map((item) => ({
      id: item.id,
      label:
        item.origin === 'MWM_DIRECTORY'
          ? 'MWM verified listing'
          : item.origin === 'LIBRARY'
            ? 'Library-verified evidence'
            : item.origin === 'LIVE_WEB'
              ? 'Current source'
              : 'Community experience',
      title: item.title,
      url: item.url,
      verifiedAt: item.verifiedAt,
    }));
}

function buildFollowUps(intent: KinfolkIntentClass, highConsequence: boolean): string[] {
  if (highConsequence) {
    return [
      'Show me the official source for this.',
      'What should I verify before I act on this?',
    ];
  }

  if (intent === 'travel_discovery') {
    return ['Help me plan this day.', 'Show me community-loved options nearby.'];
  }

  return ['Tell me more.', 'What should I explore next?'];
}

export function createKinfolkChatRouter(): Router {
  const router = Router();

  router.post('/api/kinfolk/chat', requireAuthenticatedUser, async (req, res) => {
    const requestId = crypto.randomUUID();

    try {
      const parsed = bodySchema.safeParse(req.body);
      if (!parsed.success) {
        res.status(400).json({ error: 'INVALID_KINFOLK_CHAT_REQUEST' });
        return;
      }

      const userId = req.user!.id;
      const { message, sessionId: requestedSessionId } = parsed.data;

      // Preserve the existing entitlement/pool behavior, but ensure its failure
      // is logged and never silently relabeled as an authentication error.
      const pool = await checkAiPool(userId);
      if (!pool.allowed) {
        res.status(429).json({
          error: 'KINFOLK_USAGE_LIMIT_REACHED',
          message: 'KinfolkAI is temporarily unavailable for this account. Please try again later.',
        });
        return;
      }

      const session = await getOrCreateKinfolkSession({
        userId,
        requestedSessionId,
      });

      const rawPlan = await createUniversalSearchPlan({
        userId,
        message,
        sessionId: session.id,
      });
      const plan = enforceHighConsequenceClassification(rawPlan);

      const [deliveryProfile, evidence] = await Promise.all([
        getDeliveryProfile(userId),
        retrieveEvidence({
          plan,
          // Do not pass raw cross-session sensitive history. The evidence service
          // receives only the normalized, router-approved request context.
          normalizedQuestion: rawPlan.normalizedQuestion,
        }),
      ]);

      const delivery = buildDeliveryInstructions(deliveryProfile, plan);
      const systemPrompt = buildAdaptiveAnswerSystemPrompt(delivery, plan);
      const sourceSummaries = toSourceSummaries(evidence);

      const modelResult = await invokeKinfolkModel({
        requestId,
        sessionId: session.id,
        message,
        systemPrompt,
        intent: plan.intent,
        evidence,
        permittedTools: plan.permittedTools,
        // The provider must be configured with an actual OpenAI API endpoint and
        // valid model name. Do not use a Replit-local proxy in Railway.
      });

      const response: KinfolkChatResponse = {
        sessionId: session.id,
        reply: modelResult.reply,
        // IMPORTANT: this value is the router output. Do not use modelResult's
        // informal classification or a legacy UI default.
        intentClass: plan.intent,
        provenanceNote: buildProvenanceNote({
          intent: plan.intent,
          sourceCount: sourceSummaries.length,
          sourcePolicyId: plan.sourcePolicyId,
        }),
        sources: sourceSummaries,
        followUpSuggestions: buildFollowUps(plan.intent, isHighConsequence(plan.intent)),
        recommendations: modelResult.recommendations ?? null,
        smartPromotion: null,
        taskAction: null,
      };

      await writeKinfolkAuditEvent({
        requestId,
        userId,
        sessionId: session.id,
        intentClass: response.intentClass,
        sourcePolicyId: plan.sourcePolicyId,
        evidenceCount: sourceSummaries.length,
        status: 'completed',
        // Never log `message`, raw preference data, or source body text.
      });

      res.status(200).json(response);
    } catch (error) {
      // Log the actual classified failure server-side with requestId; send only a
      // stable public message. Do not leak provider errors, tokens, or user data.
      await writeKinfolkAuditEvent({
        requestId,
        userId: req.user?.id ?? null,
        sessionId: null,
        intentClass: null,
        sourcePolicyId: null,
        evidenceCount: 0,
        status: 'failed',
        errorName: error instanceof Error ? error.name : 'UnknownError',
        errorCode: (error as { code?: string })?.code ?? null,
      }).catch(() => undefined);

      res.status(500).json({
        error: 'KINFOLK_RESPONSE_UNAVAILABLE',
        message: 'Kinfolk is having trouble answering that right now. Please try again in a moment.',
        requestId,
      });
    }
  });

  return router;
}

/*
 * Required client contract:
 *
 * type ChatMessage = {
 *   role: 'user' | 'assistant';
 *   content: string;
 *   intentClass?: KinfolkIntentClass;
 *   provenanceNote?: string;
 *   sources?: SourceSummary[];
 * };
 *
 * The UI must render `provenanceNote` as a distinct response-level note—not
 * append it invisibly into reply text. It must also render source labels from
 * `sources` without claiming community experience is a verified source.
 */
